### ISSUE TITLE
Stop show new tv-show from a week ago

### ISSUE THREAD

**Issue by Anian-igor** [croneter/PlexKodiConnect#546] opened 2018-10-07 17:55 UTC
Hello.
Still have issue on beta-version 2.4.6 and plex 1.13.8.5395.

I have PKC on my android TV, Windows and Android table. A week ago PKC stop show new tv-show. But film show correct. I trying to recreate database and totaly reinstall kodi on windows machine but with no luck. 
https://gist.githubusercontent.com/Anian-igor/9e321f1de8081776a436d53e7a1f1466/raw/0e0294fa08737cecbece28caaefad2c3fff8a65a/kodi.log

**Comment by croneter** [comment] 2018-10-07 18:00
Duplicate of #544 - please use that issue

**Closed by croneter** 2018-10-07 18:00 UTC
