### ISSUE TITLE
Wrong language on transcoding

### ISSUE THREAD

**Issue by gaunab** [croneter/PlexKodiConnect#284] opened 2017-04-30 20:11 UTC
When I choose videos to be transcoded on the server they are always english - no matter which language I choose in the appearing dialog in kodi.

**Comment by dagobertstyle** [comment] 2017-04-30 20:25
Yes, I have the same problem.

**Comment by croneter** [comment] 2017-05-01 08:39
Duplicate of #278

**Closed by croneter** 2017-05-01 08:39 UTC
