### ISSUE TITLE
Watched subtitle issue

### ISSUE THREAD

**Issue by dhaos21** [croneter/PlexKodiConnect#1162] opened 2020-04-03 12:04 UTC
I have subtitles enabled for all media, If i watch a episode via plexkodiconnect the subtitles get deactivated for all future watches of that episode. Be it watching though kodi again or via the plex app.

If i watch a episode via the plex app then this does not happen.

**Comment by croneter** [comment] 2020-04-03 14:17
Where are subtitles disabled? On other Plex clients?

**Comment by dhaos21** [comment] 2020-04-03 14:22
Yes, if you go into other plex clients and try to play it afterwards the subtitles show as selected "none", you have to reselect them. Only happens if you finish watching something via plexkodiconnect.

**Comment by dhaos21** [comment] 2020-04-06 21:05
Ok looked more into this and according to tautulli when watching via plexkodiconnect it show as i am not playing any subtitles (when they are appearing on kodi)

![Untitled](https://user-images.githubusercontent.com/3837650/78605030-b3f43980-7852-11ea-9f22-fc6fc249d9c8.png)

**Comment by croneter** [comment] 2020-09-20 13:46
Duplicate of #1191, so head over there

**Closed by croneter** 2020-09-20 13:46 UTC
