### ISSUE TITLE
Noticed it again this morning. All tv shows are empty. Here's the latest log since I've noticed it.

### ISSUE THREAD

**Issue by wormvortex** [croneter/PlexKodiConnect#1697] opened 2021-11-06 22:07 UTC
Noticed it again this morning. All tv shows are empty. Here's the latest log since I've noticed it.

https://paste.kodi.tv/ecedexotug.kodi

_Originally posted by @wormvortex in https://github.com/croneter/PlexKodiConnect/issues/1350#issuecomment-955976035_

**Comment by croneter** [comment] 2021-11-07 10:41
Completely unnecessary duplicate of #1350

**Closed by croneter** 2021-11-07 10:41 UTC

**Comment by wormvortex** [comment] 2021-11-07 11:16
Apologies! I didn't realise that reference in new issue meant it created a new post. Thought it was just marking that the issue is still present.

**Comment by croneter** [comment] 2021-11-07 11:34
No worries 😉

**Comment by croneter** [comment] 2021-11-07 11:34
Think I might've found something, see #1350
