### ISSUE TITLE
Multiple Plex Managed Users do not (always) work

### ISSUE THREAD

**Issue by rklinger76** [croneter/PlexKodiConnect#1099] opened 2020-01-14 11:59 UTC
I have a plex server running on ubuntu in my home. in my living room there is an intel nuc device with kodi on libreelec and i'm logged in with my plex user. 
I added my dad as a managed user on my plex server and he is using Kodi on libreelec on a intel nuc device. he is logged in with the managed user account but the watched status and on deck are always mixed with my account. when he is watching an episode than this tv show would be “on my deck”. we use different computer names and different names in the plexkodiconnect addon but this still happens. 
if he would use the normal plex client on windows 10 (not kodi, not pkc) it would show up as being watched by him and not by me (so its working normal).

**Comment by croneter** [comment] 2020-01-14 17:08
Please share a DEBUG log file of e.g. A movie showing up on your pkc On Deck when it shouldn't. See here: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

Guess it's enough to just start watching a movie on another device with the other user

**Comment by R91g** [comment] 2020-01-22 14:24
> I have a plex server running on ubuntu in my home. in my living room there is an intel nuc device with kodi on libreelec and i'm logged in with my plex user.
> I added my dad as a managed user on my plex server and he is using Kodi on libreelec on a intel nuc device. he is logged in with the managed user account but the watched status and on deck are always mixed with my account. when he is watching an episode than this tv show would be “on my deck”. we use different computer names and different names in the plexkodiconnect addon but this still happens.
> if he would use the normal plex client on windows 10 (not kodi, not pkc) it would show up as being watched by him and not by me (so its working normal).

I use the option share library with friends (no plex pass necessary) and works perfects.
Don't use the option managed user, try share library

**Comment by MattSidney** [comment] 2020-05-22 05:11
I have also hit an issue similar to this. 
I have my profile which is linked to my plex account.
I then have a kids profile that is linked to the kids managed user. Sometimes and I am not sure how the two get mixed up and the kids profile can access everything in my profile. 
I am trying to figure out the steps to repro but it happens sporadically meaning the logs get overwritten by the time I have noticed. It recovers with a reset and repair.

**Comment by croneter** [comment] 2020-05-22 06:27
What happens if you just reboot Kodi and login to the Kids Kodi profile again? Does that fix the issue or is nothing special happening?

**Comment by croneter** [comment] 2020-05-22 06:28
Also, Kodi saves old profiles as `kodi.log.old`. even if debug logging is disabled, these logs might help me in finding the culprit

**Comment by JPM-git** [comment] 2020-05-28 14:13
I notice a pattern to this issue, that i also have.

When i add a movie to the other profile, on a lib the this user don't have acess it seams to simple "scan" all libraries.

also the other user never have login on that specific device, so it seams that it's a "simple" scan lib's without having permissions.

Also trying to play any of the media on that libs will sooner or later reboot kodi(sometimes 5sec, other almost 30)

**Comment by MattSidney** [comment] 2020-05-28 21:50
So the issue persists over logouts/restarts of kodi. 
In this log https://pastebin.com/wk2Zx3mj I am simply logging into the kids profile and playing an episode of something that they should not have access too.

**Comment by MattSidney** [comment] 2020-05-28 22:06
fixed by resetting kodi database

**Comment by MattSidney** [comment] 2020-06-01 06:16
@JPM-git looks like our two issues are slightly different. 

@croneter is there any additional logging that could be helpful to capture?

**Comment by MattSidney** [comment] 2020-06-04 09:48
@croneter I captured a log where this actually happens. 
Loads kids profile
```
2020-06-04 11:46:41.568 T:11672  NOTICE: special://profile/ is mapped to: special://masterprofile/profiles/kids/
```
kids user loaded
```
2020-06-04 11:46:48.340 T:10632   DEBUG: PLEX.account: Loaded user kids, 27177674 with plex token ES_NG... and pms token EUPBv...
```
seems it is reloaded 
```
2020-06-04 11:47:07.544 T:10632   DEBUG: PLEX.account: Loaded user kids, 27177674 with plex token ES_NG... and pms token ES_NG...
2020-06-04 11:47:07.544 T:10632   DEBUG: PLEX.account: User is restricted Home user: True
```
some stuff happens then a full sync triggered 
```
2020-06-04 11:47:08.193 T:21824   DEBUG: PLEX.sync: ##===--- Starting FullSync ---===##
```
Adds a movie that should not be available to this user
```
2020-06-04 11:47:09.025 T:15268  NOTICE: PLEX.movies: ADD movie plex_id: 1 - ¡Three Amigos!
```

logs up to this point here: https://pastebin.com/5Bkre0cD

So then between starting an episode 
```
2020-06-04 11:47:32.943 T:11672   DEBUG: CGUIWindowVideoBase::OnPlayMedia smb://192.168.1.5/01_tv/Hey Duggee/Season 02/Hey Duggee - S02E15 - The Pizza Badge WEBDL-720p.mkv
```
And it finishing 
```
2020-06-04 11:54:59.585 T:17392   DEBUG: CSaveFileState::DoWork - Marking video item smb://192.168.1.5/01_tv/Hey Duggee/Season 02/Hey Duggee - S02E15 - The Pizza Badge WEBDL-720p.mkv as watched
```
The watched status changes for all of the Hey Duggee items to match the master profile - main plex user. 
The full log for this is too large to add to pastebin aparently. Let me know if it is relevant or if you are unable to find enough info in the first log and I can try to trim it

**Comment by MattSidney** [comment] 2020-06-07 03:28
Another note is that the plex server appears to not be getting feedback on episodes being watched since the issue highlighted in the previous comments logs.

**Comment by croneter** [comment] 2020-06-08 19:02
@MattSidney Your Kodi log could prove very useful. Can you just rename it to Kodi.log.txt and drop it here, thus uploading it to github.com entirely?

**Comment by MattSidney** [comment] 2020-06-08 23:34
@croneter unfortunately the file is too large to attach raw so I compressed it. See attached. 
[Kodi.log.txt.zip](https://github.com/croneter/PlexKodiConnect/files/4749096/Kodi.log.txt.zip)

**Comment by croneter** [comment] 2020-06-09 10:10
This bug is really a pain to troubleshoot 😢 

Does PKC **beta** version 2.12.1 help?

**Comment by croneter** [comment] 2020-06-11 07:05
Any news here whether 2.12.1 helps?

**Comment by MattSidney** [comment] 2020-06-11 22:00
Installed however it is hard to know yet if it has helped as the bug sometimes takes a while to rear it's head. Will keep you updated if the issue repeats

**Comment by MattSidney** [comment] 2020-06-19 10:06
@croneter I have captured another log when using 2.12.1 
Looks like it occurred again see: https://pastebin.com/S5wmDXwr
I was able to play 11.22.63 from kids profile and all shows were displayed as if in the dad profile

**Comment by MattSidney** [comment] 2020-07-01 08:23
@croneter  let me know if there is any testing I can perform. Still have the installation in the failed state

**Comment by croneter** [comment] 2020-07-11 14:12
This bug is driving me nuts. Are you 100% positive that you reset your Kodi library?

Could you be so kind and reset everything, even the PKC settings, just in case? Navigate to the PKC Settings, Advanced, then "Reset the Kodi DB...", then YES and YES again to start from scratch

**Comment by MattSidney** [comment] 2020-08-13 22:30
Actually just went through a fresh install on both the server and htpc
server now running linxu, htpc on windows 10. Will test and report if the issue persists.

**Comment by croneter** [comment] 2020-09-20 11:26
Closing this as it seems fixed. Let me know here if this is not the case

**Comment by MattSidney** [comment] 2020-09-21 01:04
Actually stopped using the plugin as it was continuing to happen. 
Moved to Plex client.

**Comment by a-lexdl** [comment] 2020-10-07 21:57
Hi
Using Kodi 18.7 and PKC 2.12.3 here, and I can confirm the issue is still very much here.
I do have 2 users on my plex (one with full access, and one managed with restricted libraries for the kid)
After a few weeks of everything going OK, PKC suddenly decided a few days ago to start syncing everything, even the libraries it is not supposed to. 

Is there any way to help you fix that issue? Not being able to trust profile separation is kind of a big issue.

**Comment by rajil** [comment] 2020-12-11 04:15
I can confirm this to. The client is supposed to be a managed user. After few days, the full library showed up. I had to logout the 'managed user' in plexkodiconnect and log back in again.

**Comment by Casburggraaf** [comment] 2021-01-07 09:34
I have the same problem to. If I go to settings of pkc it shows the good Plex profile. But the library is of the main Plex user. And if I watch some media Plex logs it as the main user and not the user that logged in into pkc user

**Comment by croneter** [comment] 2021-01-09 16:22
This should **FINALLY** be fixed with PKC Beta version 2.12.7. Kindly report back whether that's the case, please

**Comment by croneter** [comment] 2021-01-11 13:57
Any updates, anyone? 😉 Is this issue finally solved?

**Comment by Casburggraaf** [comment] 2021-01-11 14:03
For me, there was no way to trigger this problem, it just accord once every 1-2 moths. But no problems so far!

**Comment by croneter** [comment] 2021-01-12 08:09
I'm closing this issue for now as it should be solved with PKC version 2.12.7 and onwards. Looking forward to hearing back from you all!

**Closed by croneter** 2021-01-12 08:09 UTC

**Comment by Casburggraaf** [comment] 2021-01-12 08:40
If this works I would love to buy you a beer if that's possible!

**Comment by croneter** [comment] 2021-01-12 09:12
@Casburggraaf 
A beer is always welcome 😆 . Check the "Sponsor"-button here on Github. Thanks in advance

**Comment by Casburggraaf** [comment] 2021-01-12 09:48
Done! thanks for the work on PKC!

**Comment by croneter** [comment] 2021-01-12 11:12
Thanks a lot for the beer @Casburggraaf ❤️
