### ISSUE TITLE
Hebrew subtitles marked as Unknown

### ISSUE THREAD

**Issue by smoresmores** [croneter/PlexKodiConnect#342] opened 2017-09-18 07:07 UTC
I am not sure from what release number exactly that started to happen. But I think from about 2-3 weeks ago. Maybe 1.8.11 or 1.8.12. Seems like it happens to others (@ElDuderinos) as well: https://feathub.com/croneter/PlexKodiConnect/+2
The subtitles are marked as unknown and when I choose them they do not appear.

**Comment by croneter** [comment] 2017-09-23 16:19
I downloaded a Hebrew subtitle from opensubtitles.org (an SRT one) and saved it with the added extension `.heb.srt`. Let Plex rescan that particular video item to let the PMS pick up the new subtitle. See e.g. http://forums.plex.tv/discussion/61901/how-to-display-hebrew-subtitles-correctly

Worked fine for Addon Paths (if you use direct paths, you can check e.g. by using the Plex context menu, then `Start Playback via PMS`) and for Direct Paths. 

How do you feed the subtitles into Plex? Do they work on other Plex clients, e.g. Plex for Android? If yes to both, do share a debug log according to https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by Pavuucek** [comment] 2017-09-27 20:30
I think the problem is in this commit: 8af180968b41f0600a440cceb5967b1ce6d7e4e2 from 11.8.2017.
Before subtitles got downloaded into files like subtitle01.eng.srt, subtitle00.cze.ssa, but after this commit subtitle files are named like this: subtitle00.slovenčina.ssa, subtitle01.čeština.srt.
As you can see there are accented characters in file names and that is what kodi may have problems with.
I did some testing and while subtitles worked fine on windows, android couldn't load any subtitles at all, complaining with errors like these:
`21:32:07.025 T:18446744072731240752  NOTICE: Opening stream: 0 source: 1024
21:32:07.026 T:18446744072731240752   ERROR: OpenStream - Unable to create subtitle parser`

So I think 8af180968b41f0600a440cceb5967b1ce6d7e4e2 should be reverted. At least for now.

**Comment by croneter** [comment] 2017-09-28 12:13
Thanks @Pavuucek !

**Comment by Pavuucek** [comment] 2017-09-28 16:21
That sort of fixed it :-)
The subtitles are at least loading and displaying correctly, but they're still marked as unknown, have to be selected manually to display and subtitle dialog doesn't recoginize them.
![capture2](https://user-images.githubusercontent.com/1253845/30976838-24f6ebae-a476-11e7-8b10-45c70a7b384d.PNG)
I think everything worked just fine when there was only a thee letter language code in subtitle file name instead of full language name. Kodi recognized it and there were no problems with it.

**Comment by croneter** [comment] 2017-09-28 16:43
Then the Kodi specs on naming subtitles that I read were just plain wrong. I'm gonna revert the commits. Many thanks @Pavuucek !

**Closed** 2017-10-02 16:20 UTC
