### ISSUE TITLE
TV Cast images not displaying

### ISSUE THREAD

**Issue by pheare** [croneter/PlexKodiConnect#331] opened 2017-08-07 17:24 UTC
For TV shows, once you get down to the episode information screen, the cast images do not appear.

This is happening with all skins, so not a skin issue. TV Cast does show up when using the plex for kodi add-on, so it looks like tv show cast should be available.

Actors for movies, show as expected.

**Comment by dazedcrazy** [comment] 2017-08-20 13:44
Works fine here **PKC > TV Shows > On Deck > Episode** https://i.imgur.com/yQ0ofBC.jpg
It will show the TV shows cast not the episode cast as plex does not support cast at the episode level. There is a feature request for it here https://forums.plex.tv/discussion/comment/1464284

**Comment by croneter** [comment] 2017-09-08 11:15
Works here, too, so I cannot reproduce your issue. 

Maybe try a database reset: go to the PKC settings, Advanced, `Reset the Kodi database...` (in red). Then hit YES, YES, NO

Closing as I cannot reproduce

**Closed by croneter** 2017-09-08 11:15 UTC

**Comment by croneter** [comment] 2019-05-03 07:01
Make sure that you can see cast posters on the Plex side! If not, then it's a Plex issue and you probably need to select a different metadata agent in the Plex PMS settings.

https://www.reddit.com/r/Addons4Kodi/comments/bjv3zk/missing_cast_posters_for_movies_using/

> So I think I found the source of the problem, but I’ll need to wait until tomorrow to test. When I noticed there was some cast posters appearing but not all, I went to my Plex server and compared. The missing cast members were the same. I never really noticed it before because they aren’t as prominently displayed in Plex as they are in Kodi. Apparently if you don’t choose TheMovieDB as your cast source you won’t get the photos. I made the change and refreshed the metadata on the Plex side and they updated.

> Cast photos didn’t update on the Kodi side but the movie posters did. I’m doing a full metadata refresh right in Plex. Tomorrow morning I’m going to re-add PKC and see if it pulls them this time.
