### ISSUE TITLE
How to install PKC on Nexus?

### ISSUE THREAD

**Issue by Sparh4wk** [croneter/PlexKodiConnect#1844] opened 2022-05-30 17:44 UTC
Hi,

just want to ask you, how to actually install PKC on Kodi Nexus.
I tried add both matrix stable and beta repo (cant find Nexus repo, but mb Im just blind), but both giving me error Could not connect to repository.

So I tried to install newest version 3.6.14, but it needs some dependency, so I cant install it.

Thanks for help and thanks for doing amazing job on this superb addon.

With regards

Sparhawk

**Comment by croneter** [comment] 2022-05-31 13:02
Should work just fine following https://github.com/croneter/PlexKodiConnect/wiki/Installation

Barring any hickups from Kodi Nexus - it's still in an Alpha state so things can and will break frequently. Try the "official" Alpha version from www.kodi.tv, not the lastest one (nightly).

**Comment by croneter** [comment] 2022-05-31 16:16
Ah OK, so it's an issue with the Kodi repository of PKC, not PKC itself. Thanks!!

**Comment by bokkoman** [comment] 2022-06-13 19:26
I can't install it either.
Tried the manual way, but installing the 2 dependencies fails with error that it can't find python 2.1.0.

**Comment by bokkoman** [comment] 2022-06-14 06:01
@Sparh4wk 
how did you manage to install it on the Maven kodinerds build? Since I am getting python missing errors.

**Comment by Sparh4wk** [comment] 2022-06-14 06:27
@bokkoman you need to install versions for matrix, cause they need python 3 and not 2.1.0.

**Comment by bokkoman** [comment] 2022-06-14 06:45
> @bokkoman you need to install versions for matrix, cause they need python 3 and not 2.1.0.

Where do i find these?
I followed the docs for manual installation, but apparently that links to the old versions.

**Comment by Sparh4wk** [comment] 2022-06-14 06:46
![image](https://user-images.githubusercontent.com/7014826/173511154-f5e153a9-10dd-4cc6-8fcb-258e5ee1651a.png)

https://github.com/croneter/plugin.video.plexkodiconnect.movies/archive/refs/tags/3.0.2.zip
https://github.com/croneter/plugin.video.plexkodiconnect.tvshows/archive/refs/tags/3.0.2.zip

**Comment by bokkoman** [comment] 2022-06-14 06:53
Ah i see, you needed to download the releases.
I followed the exact guide, by downloading the zip by pressing CODE.

**Comment by brando56894** [comment] 2022-08-16 14:58
I just had to figure this out on my own, I installed both Matrix repositories (stable and beta) and Kodi (Nerds build, Nexus Alpha 2) kept complaining that it couldn't connect to the repo. I read through the log and it said
 
```
ERROR <general>: Repository add-on repository.plexkodiconnect does not have any directory and won't be able to update/serve addons! Please fix the addon.xml definition

ERROR <general>: Repository add-on repository.plexkodiconnect uses old schema definition for the repository extension point! This is no longer supported, please update your addon to use <dir> definitions.
```

I managed to fix it by adding the requested \<dir> tags around \<info>, \<checksum>, and \<datadir> like so 
```	
<extension point="xbmc.addon.repository" name="PlexKodiConnect Repository Kodi 19 Matrix">
	<dir>
		<info compressed="false">https://raw.githubusercontent.com/croneter/binary_repo/master/stable_py3/addons.xml</info>
		<checksum>https://raw.githubusercontent.com/croneter/binary_repo/master/stable_py3/addons.xml.md5</checksum>
		<datadir zip="true">https://raw.githubusercontent.com/croneter/binary_repo/master/stable_py3/</datadir>
	</dir>
</extension>
```
After doing that everything worked as intended. I just finished installing it and it linked without issue and then synced all my content in about 30 seconds.

**Comment by bokkoman** [comment] 2022-08-16 15:09
> 

Can you PR that? If that makes it work on nexus like it would in matrix.

**Comment by brando56894** [comment] 2022-08-16 16:38
I was about to, but https://github.com/croneter/PlexKodiConnect/blob/master/addon.xml looks a lot different than the one I have installed. I added https://croneter.github.io/pkc-source as a source in my file manager, then installed one of the Matrix repos and then edited the file that was installed, which is only 19 lines, so I'm not exactly sure where to place the tags in the larger one.

I'm on the Nvidia Shield btw, but I don't think that makes a difference in this case.

**Comment by bokkoman** [comment] 2022-08-16 16:57
> I was about to, but https://github.com/croneter/PlexKodiConnect/blob/master/addon.xml looks a lot different than the one I have installed. I added https://croneter.github.io/pkc-source as a source in the kodi file manager, then installed one of the Matrix repos and then edited **addons/repository.plexkodiconnect/addons.xml**, which is only 19 lines, so I'm not exactly sure where to place the tags in the larger one.
> 
> I'm on the Nvidia Shield btw, but I don't think that makes a difference in this case.

I think you need to look at this one:
https://github.com/croneter/repository.plexkodiconnect/blob/master/repo/addons.xml

**Comment by cscoppafox** [comment] 2022-10-29 00:31
> I managed to fix it by adding the requested <dir> tags around <info>, <checksum>, and <datadir> like so


This still works .... thanks!!!

Without the change you can't install PKC on Nexus Alpha 3

**Comment by bokkoman** [comment] 2022-12-27 15:48
Latest nightly doesn't work.
After launching Kodi i get an error message from PKC telling me it doesn't work and need to check the forums.

**Comment by croneter** [comment] 2022-12-27 20:02
@bokkoman On principal, don't use the nightly, use the release candidate. Too much breaks still on the Kodi (and not PlexKodiConnect) side of things.

Having said that, share a DEBUG log file and I might be able to help you, see https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by croneter** [comment] 2022-12-27 20:04
Closing this issue as one should be able to easily install using the normal instructions, see https://github.com/croneter/PlexKodiConnect/wiki/Installation

**Closed by croneter** 2022-12-27 20:04 UTC
Labels: Kodi 20 Nexus
