### ISSUE TITLE
4K playback in add-on mode is very choppy and PKC direct path issues

### ISSUE THREAD

**Issue by pabba50** [croneter/PlexKodiConnect#127] opened 2016-10-18 22:47 UTC
as in title.
worked flawlessly and smooth when I used Direct Paths.
for other problems, DP don't work anymore for me.
is there a way to fix this?

**Comment by croneter** [comment] 2016-10-19 05:39
This is most probably a Plex Media Server issue (e.g. your server not having enough CPU power). I don't think there's anything PKC could do about this except you configuring **Direct Paths** to work properly. 

How about some more info?

Direct Paths just stopped working from one day to the other? (If so, then grab [some log files](https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug)!). Or did you change your network setup?

**Comment by pabba50** [comment] 2016-10-19 08:21
I am using Kodi on my Sony Android TV.
on my first install of Kodi and PKC everything was working perfectly with direct paths.
then I messed up trying the v.17 beta (thinking I had a working backup, which then turned out as corrupt) and from there, nothing was as smooth as before.
you may remember I posted my direct paths problem on the Kodi forum some weeks ago.

the network setup has not been changed. I run Plex server on a mac mini, the media files are on USB3 drives. I use a gigabit switch.
the choppy playback only happens with 4K videos, but as said before, it was playing perfectly with direct paths.
also, DP had almost instant playback, which now with add-on mode takes 5-10 seconds to start playing.

I have memories of inserting a couple of lines of code in the advanced xml file or something for Kodi, but I'm not sure about this. do you think it could be related to this issue?

about the log files, should I capure it after trying to play a 4K file?

**Comment by croneter** [comment] 2016-10-19 09:04
OK, I see only 1 solution: you need to use PKC Direct Paths. (I think your PMS is not powerful enough to otherwise serve you 4k content). Log files don't really help at this point

Can you completely reset your Kodi without a lot of hassle? That would probably be easiest. To do that, follow "The Manual Reset" on http://www.kodijunkie.com/kodi-setup/how-to-restore-kodi-to-default-settings/

Alternatively, simply delete your advancedsettings.xml. This will reset it.

**Comment by pabba50** [comment] 2016-10-19 09:22
I would like to keep my settings and skin and shortcuts.
would the Kodi reset erase everything? is there a way I can keep the settings?

what should the Path replacement be?

**Comment by croneter** [comment] 2016-10-19 09:57
Then remove the changes you have made to advancedsettings.xml - they might be the cause. 

Settings for DP are extremely dependent on your exact setup. You DID have a working set of settings :-). Remember that? That would be a good starting point. 

* Switch to Direct Paths in PKC
* Checkout your Path replacements in the settings, use your old, once-working settings
* Go to Advanced, enable PKC Debug logging
* Then reset your Kodi DB in the PKC settings, Advanced (2x YES, 1x NO).
* Try to play a Plex movie. What does the Kodi log tell you?

**Comment by pabba50** [comment] 2016-10-19 11:27
right now there is not advancedsettings.xml file present.
I remember I added something related to cache, but I don't remember anything else.

I found a way to access the system files on my TV via a FTP server, so now everything related to system files hould be easier.
if I delete the kodi folders for resetting, is it also true that if I restore them, Kodi will be restored as before?

**Comment by croneter** [comment] 2016-10-19 11:50
If you say that there is no advancedsettings.xml in your [**userdata folder**](http://kodi.wiki/view/userdata), then that means that Kodi uses the **standard advancedsettings.xml** from `kodi/system/`. You probably changed that one - which you should not have but instead created a new advancedsettings.xml in your userdata folder. 

You changed something related to the Kodi cache. This stinks like it could be the cause for video playback stuttering

Theoretically, you can backup the 2 folders `userdata` and `addons` as mentioned in the link in my previous post. Then simple copy them back if something went wrong. 
**BUT** you seem to have changed the Kodi system standard. So you would need to backup/reset that, too!

I suggest that you backup the two folders above. Then uninstall Kodi complete and reinstall (thus having a clean advancedsettings.xml). Then try PKC with direct paths. I need answers to all my questions in the bullet list above

**Comment by pabba50** [comment] 2016-10-19 11:53
I think the .kodi/system/ folder is empty.
is that the right location?

![screen shot 2016-10-19 at 13 51 51](https://cloud.githubusercontent.com/assets/22482186/19517750/49f36392-9603-11e6-9fa2-3cc8329a8743.jpg)

I just saved the two folders, I just want to check for the advancedsettings.xml

**Comment by croneter** [comment] 2016-10-19 11:59
Try to search for `advancedsettings.xml` ;-)

**Comment by pabba50** [comment] 2016-10-19 12:01
I tried, but my FTP client only allows searching in the current folder, not Root-wise.
I looked everywhere but it seems that file doesn't exist.
could you point the exact absolute path to me?

**Comment by croneter** [comment] 2016-10-19 12:08
Seems like you deleted it. And that I was wrong - there is no standard "system" advancedsettings.xml. Quote from Kodi wiki

> The advancedsettings.xml file, which does not exist by default, can be created by a user in their userdata folder.

**Comment by pabba50** [comment] 2016-10-19 12:10
so now I have a backup of the two folders.
should I reset Kodi and then try DP in PKC?

**Comment by croneter** [comment] 2016-10-19 12:12
Go for it! 

If it's not working from the beginning, please answer every bullet from my previous post above

**Comment by pabba50** [comment] 2016-10-19 12:22
ok just reinstalled PKC and selected direct paths at first run.
now it asks me about transform UNC paths: YES or NO?

**Comment by croneter** [comment] 2016-10-19 12:31
Dude, please read https://github.com/croneter/PlexKodiConnect/wiki/Direct-Paths

If your Plex Media Server is installed on a Windows machine, probably choose YES

**Comment by pabba50** [comment] 2016-10-19 12:49
PMS is on a mac, and I read the guide and activated SMB sharing, etc.
I also reset PKC and at the restart there's this:

![img_2918](https://cloud.githubusercontent.com/assets/22482186/19519198/2bbb446e-960b-11e6-8e6b-76f43c2b5071.jpg)

**Comment by croneter** [comment] 2016-10-19 12:54
* Deactivate transform UNC paths since you're not using Windows
* Is your PMS on the same machine as Kodi? If no, read https://github.com/croneter/PlexKodiConnect/wiki/Direct-Paths again to replace your paths (they are local right now)
* Can you use Kodi to navigate to your Plex media folder (where the movies are stored)? In Kodi, go to Video -> Files -> browse to your media folder

**Comment by pabba50** [comment] 2016-10-19 13:40
> Deactivate transform UNC paths since you're not using Windows

OK

> Is your PMS on the same machine as Kodi? If no, read https://github.com/croneter/PlexKodiConnect/wiki/Direct-Paths again to replace your paths (they are local right now)

it is not on the same machine. it's on a Mac Mini.
I read again the guide and I set up the paths like this:
![img_2919](https://cloud.githubusercontent.com/assets/22482186/19520787/b2ace404-9611-11e6-956e-8002fe43c06e.jpg)

but after reset, it doesn't play:
![img_2920](https://cloud.githubusercontent.com/assets/22482186/19520794/ba720d2c-9611-11e6-9fd0-9a45ddd11949.jpg)

> Can you use Kodi to navigate to your Plex media folder (where the movies are stored)? In Kodi, go to Video -> Files -> browse to your media folder

no, if I use BROWSE it says "Erro 2 share not available"
if I add it manually (Add network location) it tells me Connection Timed Out or also Broken Pipe

**Comment by croneter** [comment] 2016-10-19 13:55
Forget the PKC settings for the moment, you need to be able to use Kodi to browse to your Plex media files using Videos -> Files -> ... (last bullet above). If you don't manage to do that, PKC doesn't have a chance to work 

It's best if you "move" your movies and other Plex media to a smb directory, away from the `/Volumes/...`

* You did not follow the PKC Wiki's (**How-to set everything up**)(https://github.com/croneter/PlexKodiConnect/wiki/Direct-Paths#how-to-set-everything-up). Please do that and 
    * setup a Mac smb shared folder. 
    * change the Plex link from your old `/Volumes/` folder to `smb://` 

It's all there. Please follow it

**Comment by croneter** [comment] 2016-10-19 13:58
By the way, no way that your setup EVER worked with direct paths in the past...

**Comment by pabba50** [comment] 2016-10-19 14:00
I swear it worked perfectly, 4K was smooth and instant.

however, I edited the PMS library (just Movies for now) with this setting:
![screen shot 2016-10-19 at 15 59 49](https://cloud.githubusercontent.com/assets/22482186/19521755/2d715f8c-9615-11e6-9349-2084605676bf.jpg)

did I understand correctly?

**Comment by croneter** [comment] 2016-10-19 14:02
Seems like it, I don't know your setup! 

Finish the instructions to the end. The PMS will complain if there are suddenly no movies anymore. Once you're done you can test the Plex side with e.g. Plex for Android by playing a movie.

**Comment by pabba50** [comment] 2016-10-19 14:15
in my setup, 192.168.1.5 is the mac mini where PMS is installed.
if I edit the ADD FOLDERS in PMS and point it to the smb://192.168.1.5 would it work?
I mean, it's the same computer trying to reach a network location inside itself?

**Comment by croneter** [comment] 2016-10-19 14:17
Exactly and yes it should work if you followed the instructions. PLUS **other** computers like your TV can access the folder, too - that's the whole point

**Comment by pabba50** [comment] 2016-10-19 14:22
it seems it doesn't work.
after this step:
`Remove Old Content Location
Once everything is completed and you've verified that things are working correctly and you can access your content, you can remove the old content location for your Libraries. To do so, Edit the Library and remove the old/previous folder location.`

I remove the old folder reference and when I enter the Movies section in plex web, it says
`The library has no content yet. Click here to add content to the library.`

the IP and paths are correct: smb://192.168.1.5/Big4/Movies
in fact, using another machine and connecting to that address is working and the folder is mounted.
WTF is wrong in my setup. I can't figure it out :(

**Comment by croneter** [comment] 2016-10-19 14:31
Google is your friend. Does this help? https://forums.plex.tv/discussion/58993
Otherwise please ask in the Plex PMS for Mac forum

We can take this up again once you managed to let the PMS see your movies under `smb://192....`

In fact, you're pretty much done then. Deactivate (!!) everything in the PKC settings under `Customize Paths`

**Comment by pabba50** [comment] 2016-10-19 14:37
thanks for the link.
what I was mentioning before is this:

![screen shot 2016-10-19 at 16 34 11](https://cloud.githubusercontent.com/assets/22482186/19523156/f34c67d4-9619-11e6-9b9a-13d8cf735ab8.png)

my "Big4" hd is not a NAS so it doesn't have its own IP address.
so of course the same machine can't mount an address which is its own.
I feel like I'm in a loop :(

**Comment by croneter** [comment] 2016-10-19 14:43
You **can** access `smb://192.168.1.5/Big4/Movies` from another computer in the same network and you see the Plex movie files, correct? Then all is well. 
I'm no Mac expert, you "just" need to figure out how you can access that network resource from your Mac. That's what the link above is for

**Comment by pabba50** [comment] 2016-10-19 19:25
using the official Plex app on my Android TV works without issues. does this count for anything in this case?
it seems the SMB problem is a bug between kodi and the mac. I'm still investigating and doing tests

**Comment by croneter** [comment] 2016-10-19 19:44
Thanks for the update. Unfortunately, a working plex app doesn't say anything about direct paths. Does 4k also work? 

So did you succeed in remapping the plex file paths if the plex app works now?

**Comment by pabba50** [comment] 2016-10-19 20:11
4K works, just some stuttering every now and then. (kodi was better at this)

I can't put smb paths inside plex. on your latest link:
![screen shot 2016-10-19 at 22 11 02](https://cloud.githubusercontent.com/assets/22482186/19535663/f7f1dc54-9648-11e6-80d1-efde41d91f9a.jpg)

and direct "add file" via smb gives error for some reason.
still investigating... :(

**Comment by pabba50** [comment] 2016-10-20 08:54
doing some more tests: I installed Kodi 17 alpha 3 on my android TV.
I am now able to add the SMB mount in the kodi video, and the files are playing.

but when I add PKC, and set it up with direct paths, the same problems appear ("The file is no longer available").

**Comment by croneter** [comment] 2016-10-20 09:25
If possible, I would use Kodi 16 Jarvis - much more stable!

Again, I understand that you **CAN** access `smb://192.168.1.5/Big4/Movies` from another computer in the same network and you see the Plex movie files, correct?

If so, then change the folders on the Plex Media Server back as they were orginially, e.g. to `/Volumes/Big4k`

Then go to PKC settings, Customize Paths.
* Toggle `Replace Plex UNC paths \myNas with smb://myNas` OFF
* Toggle `Replace Plex paths /volume1/media or \myserver\media with custom SMB paths smb://mystuff` ON and plugin:
    * `Original Plex path to replace`: use the one from above, e.g. `/Volumes/Big4k`
    * `Replace Plex path with`: plug in `smb://192.168.1.5/Big4`

Make sure you're using Direct Paths in the Sync Settings. Then go to Advanced and hit `Partial or full reset of Database and PKC`, then YES, YES and NO

**Comment by pabba50** [comment] 2016-10-20 10:33
just tried what you wrote.
I still get the "file no longer available" message :(

I am going to show my libraries on PMS and their folders, so maybe you can have a better idea of my setup and tell me more exactly? I don't know

![screen shot 2016-10-20 at 12 32 50](https://cloud.githubusercontent.com/assets/22482186/19556434/6f362c02-96c1-11e6-8b0f-deee2e06b178.jpg)
![screen shot 2016-10-20 at 12 32 47](https://cloud.githubusercontent.com/assets/22482186/19556439/73c69f9a-96c1-11e6-8fe1-c7f6e4215a57.jpg)
![screen shot 2016-10-20 at 12 32 20](https://cloud.githubusercontent.com/assets/22482186/19556441/73f5002e-96c1-11e6-9b82-0039825cc5c3.jpg)
![screen shot 2016-10-20 at 12 32 28](https://cloud.githubusercontent.com/assets/22482186/19556443/73fb29b8-96c1-11e6-81c2-933c1d416a60.jpg)
![screen shot 2016-10-20 at 12 32 38](https://cloud.githubusercontent.com/assets/22482186/19556442/73f77a70-96c1-11e6-9f59-ebc4bf407fe9.jpg)

**Comment by croneter** [comment] 2016-10-20 11:11
* Enable debug logging in the PKC Settings under Advanced
* Restart Kodi
* Try playing a movie lying in `/Volumes/Big4`
* Share your Kodi log (see https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug)

That way I can see the other side of the problem

**Comment by pabba50** [comment] 2016-10-20 15:41
http://paste.ubuntu.com/23354186/

**Comment by pabba50** [comment] 2016-10-20 15:42
also, is this OK?

![img_2921](https://cloud.githubusercontent.com/assets/22482186/19567013/945ff4c4-96ec-11e6-8d4a-fb9596b7bb9a.jpg)

**Comment by croneter** [comment] 2016-10-20 16:23
In the last Screenshot, drop Movies two times! 

Also, I don't understand your log :-(. Did you really try to play a movie while recording the log? I don't see that at all. That's very unusual. Did Kodi give an error message? 

To avoid any potential Kodi beta issues, please downgrade to Jarvis. Sorry for the hassle :-(

**Comment by pabba50** [comment] 2016-10-20 17:58
> In the last Screenshot, drop Movies two times!

what you mean? my actual movies are stored in a subfolder of Big4 disk called "Movies". isn't that necessary?

**Comment by croneter** [comment] 2016-10-20 18:20
No it's not

**Comment by pabba50** [comment] 2016-10-20 18:33
if I downgrade to Jarvis it will be impossible for Kodi to connect to smb natively as I already tested yesterday. for some reason, on v.17 it works
do you still want me to downgrade?

**Comment by pabba50** [comment] 2016-10-20 18:47
new log: http://paste.ubuntu.com/23355088/

the error is the usual: "this file is no longer available. would you like..."

**Comment by croneter** [comment] 2016-10-20 18:51
Could you please from now on answer all my questions? 

In that case, don't downgrade yet. Try again to get a log file. Try playing something several times. Does Kodi give an error message?

**Comment by pabba50** [comment] 2016-10-20 18:52
yes, see my previous answer :( I don't know why the log doesn't have what you need

**Comment by croneter** [comment] 2016-10-20 18:52
Thanks :-). Didn't see your post

**Comment by croneter** [comment] 2016-10-20 19:10
Still nothing. 
* Please go to Advanced, then `Partial or full reset of Database and PKC`. Then YES, YES, NO
* After the restart, please try playing a movie in `/Volumes/Big4` (!!!) several times.
* Then please share the log again

**Comment by pabba50** [comment] 2016-10-20 20:04
just tried to play several times, still nothing.
I installed an ftp server on the android tv, so instead of going crazy with the Log plugin in kodi I just connect via FTP and fetch the log.
I can see the are 2 logs now, which you can download here:
https://we.tl/SAcRImHMsx

**Comment by croneter** [comment] 2016-10-20 20:14
Much better now
```
21:57:39 T:18446744072359603088  NOTICE: VideoPlayer: Opening: /Volumes/Big2/p/private_fantasies_ss_scene3_4k.mp4
```
Now please try to play a movie located in `/Volumes/Big4/Movies`

**Comment by pabba50** [comment] 2016-10-20 20:15
I did! was it the only entry in the whole log?
I tried playing several titles...

**Comment by croneter** [comment] 2016-10-20 20:16
No, you tried 2, none of them located where I told you
```
21:57:39 T:18446744072359603088  NOTICE: VideoPlayer: Opening: /Volumes/Big2/p/private_fantasies_ss_scene3_4k.mp4
21:57:50 T:18446744072359603088  NOTICE: VideoPlayer: Opening: /Volumes/500/test/test.mp4
```

**Comment by pabba50** [comment] 2016-10-20 20:18
I tried "Anomalisa"... 
wait I will try again

**Comment by pabba50** [comment] 2016-10-20 20:23
https://we.tl/u0EaXIHqFa

I tried: revenant, sicario, looper, and others.
I tried playing from the "home" screen (recently added) and from entering the main Movies section

**Comment by croneter** [comment] 2016-10-21 06:38
Very good news, the path substitution works (notice the IP, not `/Volume/` anymore):
```
22:20:27 T:18446744072360643472  NOTICE: VideoPlayer: Opening: smb://192.168.1.5/Big4/Movies/4K/View from a blue moon 4K.mp4
```
So your movie `View from a blue moon 4K.mp4` should soon be played on Kodi ;-). 

Bad news: smb on your Mac is screwed. 
```
22:20:27 T:18446744071991360400   ERROR: SMBDirectory->GetDirectory: Unable to open directory : 'smb://USERNAME:PASSWORD@192.168.1.5/Big4/Movies/4K'
                                            unix_err:'20' error : 'Broken pipe'
```
Please visit http://forum.kodi.tv/showthread.php?tid=214091&highlight=pipe and try the steps there. Look at the last post, seems most promising. Please ask follow up questions there. You're dealing with Kodi issues, not PKC issues now

**Comment by pabba50** [comment] 2016-10-21 07:31
you mean the post talking about NFS sharing?
I can try that, but would it be the same for PKC if SMB will never work, but NFS will?

**Comment by croneter** [comment] 2016-10-21 07:57
PKC does not care, what Kodi thinks is relevant. Kodi can work with both smb and nfs so you're good.

On the PKC side, you only need to change 
* `Replace Plex path with:`plug in  `nfs://192.168.1.5/Big4`

**Comment by pabba50** [comment] 2016-10-21 08:28
FYI: I am encountering problems with that NFS sharing. it seems there's something related to my media drives being in exFAT. I am now slowly transfering the media in order to do a fresh format in mac native HFS mode. maybe that's enough to solve all of this. I will keep you posted.

**Comment by croneter** [comment] 2016-10-21 08:39
Well, Direct Paths are sure a pain in the butt for you ;-). 

I do hope that direct paths will solve your video stuttering (and that the stuttering is not some Kodi or TV issue).

**Comment by pabba50** [comment] 2016-10-22 10:37
tried that last guide. it doesn't work. same as before. 😭😭😭😭

**Comment by croneter** [comment] 2016-10-22 11:06
Logs? Ask on the Kodi forum, thread I posted above. As already mentioned, this is a Kodi/Mac issue, not PKC

**Comment by pabba50** [comment] 2016-10-22 11:49
just out of curiosity: why was the 4K playback in Add-on mode choppy? what is the reason of the difference?

**Comment by croneter** [comment] 2016-10-22 12:16
I don't know what caused your 4k video stuttering. 
* Cause might be a slow Plex Media Server. There is some overhead for the PMS to stream to Kodi (as opposed to using PKC direct paths - here Plex simply hands over the file's path, Kodi grabs it directly)
* Cause might be something else, like you having changed a Kodi (video) setting

To solve this, you have these two venues to follow up. Again, I guarantee that your TV **never** used PKC direct paths but has always been using Add-on mode. So your chances of fixing this might be better trying to fix the Kodi settings - try the Kodi forum for help

**Comment by pabba50** [comment] 2016-10-22 12:26
you're right, but I swear I previously had a setup which didn't stutter with 4K files.
if you tell me I never had direct paths I believe you, but then my question is why and how didn't they stutter then? 
the problem only started when I installed the krypton beta and then reverted to jarvis.

so if there's a way to go back to add-on mode and making 4K playback smooth again, I would be very happy.
would you have a recommended configuration/setup to recommend?

anyway, I'd like to thank you for all you help, you're amazing :)

**Comment by croneter** [comment] 2016-10-22 12:34
Well thanks :-)

I cannot and will not help with Kodi setup issues, sorry. That's what the Kodi forum is there for... ;-)

So you're issue came up installing the Kody beta, then reverting. Hence I would try to wipe (!!) Kodi completely from your TV. Make tripple sure that there is no Kodi userdata folder anymore to guarantee that Kodi will start with fresh default settings. Then install Jarvis, and Jarvis only. Before adding any other plugins, install PKC in Add-on mode ;-). 

If Kodi is still stuttering then, let the video play (while stuttering). Have a look at your PMS. Is Plex using all your resources? Is the server and the machine responsive? If you don't notice anything off, then you have indeed some Kodi settings issue

**Comment by pabba50** [comment] 2016-10-22 12:46
there's something just new.
I tried again adding a network location just with "smb://macmini" (no IPs or anything else) and the share is mounted!
so when I click Movies and then Add File I can mount the macmini and I'm able to see the single files.
the files plays, but the 4K ones stop for buffering after a while.

then I cancelled the smb path replacement in PKC, and then reset PKC (yes yes no) hoping it would work.
but it doesn't. 
having now successfully mounted the smb share natively, is there any hope that PKC works for me in direct path?

**Comment by croneter** [comment] 2016-10-22 13:31
Then try 
* `Original Plex path to replace:` plug in `/Volumes`
* `Replace Plex path with:` plug in `smb://macmini`
* Make sure direct paths in selected
* Reset database again under Advanced

**Comment by croneter** [comment] 2016-10-22 13:37
"Plug in" means "type in". YES, type in exactly what I wrote above, no `/Big4`

**Comment by pabba50** [comment] 2016-10-22 13:49
it seems it is working now, however:

- 4K buffers after some seconds
- I no longer can see the subfolders in the MOVIE main section: every file is shown together. is there a way to maintain folder structure?

**Comment by croneter** [comment] 2016-10-22 14:45
4K buffers after some seconds: ask in the Kodi forum. Can't help you with this. Do give a hint what type of TV you're using. 

For the other thing, do read https://github.com/croneter/PlexKodiConnect/wiki/Video-Nodes-and-Skins

Closing this issue for PKC as you need to mess with Kodi now

**Closed by croneter** 2016-10-22 14:45 UTC
