### ISSUE TITLE
PKC loses video info

### ISSUE THREAD

**Issue by billwolfer** [croneter/PlexKodiConnect#970] opened 2019-08-12 22:59 UTC
PKC loses the video and audio info normally shown on the list view in the lower left hand corner. When it works, this shows video info, i.e. H.265 - UHD (4K) 2.35:1, followed by audio info, i.e. DTS-HD MA 7.1. Under that the running time of the film is shown. Pressing 'i' on the remote brings up an information page. 

Frequently however, PKC drops this info, and pressing the 'i' button or key does nothing.  I need to re-analyze the library on the Plex server to get it back. Unfortunately, this fix is only temporary, because PKC loses the info shortly after, around half an hour. 

I reset the Kodi database, and ran the following log which starts with PKC in the state of not having the info. I re-analyze the library, and then the info appears. About a half hour later, the info was gone, and I stopped the log. I'll attach the log with plex tokens edited out:

[kodi log.txt](https://github.com/croneter/PlexKodiConnect/files/3494631/kodi.log.txt)

**Comment by croneter** [comment] 2019-08-13 05:53
Thanks for the log. There's definitely something off:
```
2019-08-12 13:35:14.667 T:4072058880  NOTICE: Starting Kodi (18.3). Platform: Linux ARM (Thumb) 32-bit


2019-08-12 13:35:59.417 T:3591369440   DEBUG: PLEX.websocket_client: PMS_Websocket: Received message from PMS server: {u'TimelineEntry': [{u'itemID': 8730, u'title': u'Alita: Battle Angel', u'mediaState': u'analyzing', u'sectionID': 16, u'state': 5, u'updatedAt': 1565642162, u'identifier': u'com.plexapp.plugins.library', u'type': 1}], u'type': u'timeline', u'size': 1}
2019-08-12 13:35:59.419 T:3591369440   DEBUG: PLEX.websocket_client: PMS_Websocket: Received message from PMS server: {u'TimelineEntry': [{u'itemID': 8730, u'title': u'Alita: Battle Angel', u'mediaState': u'thumbnailing', u'sectionID': 16, u'state': 5, u'updatedAt': 1565642162, u'identifier': u'com.plexapp.plugins.library', u'type': 1}], u'type': u'timeline', u'size': 1}
2019-08-12 13:35:59.420 T:3591369440   DEBUG: PLEX.websocket_client: PMS_Websocket: Received message from PMS server: {u'TimelineEntry': [{u'itemID': 8730, u'title': u'Alita: Battle Angel', u'sectionID': 16, u'state': 5, u'updatedAt': 1565642162, u'identifier': u'com.plexapp.plugins.library', u'type': 1}], u'type': u'timeline', u'size': 1}

2019-08-12 13:36:07.122 T:3925070560   DEBUG: PLEX.sync.websocket: Message: {u'timestamp': 1565642159, u'state': 5, u'attempt': 0, u'plex_id': 8730, u'plex_type': u'movie'}
2019-08-12 13:36:07.198 T:3925070560   DEBUG: PLEX.sync.websocket: Processing new/updated PMS item: 8730
2019-08-12 13:36:07.285 T:3925070560  NOTICE: PLEX.movies: ADD movie plex_id: 8730 - Alita: Battle Angel


2019-08-12 14:35:35.073 T:3925070560  NOTICE: PLEX.sync: Doing scheduled full library scan
2019-08-12 14:35:36.645 T:3925070560  NOTICE: PLEX.sync.full_sync: Start synching playstate and userdata for every item
2019-08-12 14:35:36.656 T:3925070560   DEBUG: PLEX.sync.full_sync: Looking for items to delete

2019-08-12 14:35:38.352 T:3925070560   DEBUG: PLEX.movies: Removing movie with plex_id 8730, kodi_id: 3
2019-08-12 14:35:38.948 T:3925070560   DEBUG: PLEX.movies: Deleted movie 8730 from kodi database
```
During the first scheduled full library sync (every 60min), PKC decides that it needs to delete your items. 

Investigating. Could you please share your `MyVideosXXX.db` and `Plex.db` from the `database` folder in the Kodi userdata folder? Once when everything looks OK, once after things have gone sideways? Also share the debug log of this process again please so I can relate

**Comment by croneter** [comment] 2019-08-13 06:14
Did you try to completely reset PKC? In the PKC settings under `Advanced`, choose `Reset the Kodi database...`, then hit Yes, then Yes again

**Comment by billwolfer** [comment] 2019-08-13 06:14
Thanks for your help!

Could you please share your MyVideosXXX.db and Plex.db from the database folder
> in the Kodi userdata folder? Once when everything looks OK, once after
> things have gone sideways?


Can I access those files through SSH, and if so, can you tell me how? I've
gotten into the thing using Putty before, but I need to know the commands.
I am completely new to any sort of Linux stuff. I'll get those files to you
tomorrow. Thanks again.

**Comment by billwolfer** [comment] 2019-08-13 06:16
Yeah, I did that, but you told me to hit yes, then no, if I recall. I can
do the complete reset if needed tomorrow.

**Comment by croneter** [comment] 2019-08-13 07:00
Yes use SSH, easiest with https://winscp.net/eng/index.php when you use Windows. Navigate to the Kodi userdata folder: https://osmc.tv/wiki/general/exploring-kodi-file-locations/. Using Winscp, just drag and drop the files

**Comment by croneter** [comment] 2019-08-13 07:02
Obviously, try completely resetting PKC first 😉

**Comment by billwolfer** [comment] 2019-08-13 19:06
Have reset PKC completely, problem persists. How do I get you the plex.db and myvideos files? I tried drag and drop, but github says it doesn't support that file type.

**Comment by billwolfer** [comment] 2019-08-13 19:32
Github won't let me drag and drop the plex.db or video file, so let me try
to attach them here. Let me know if that works. Logs are in progress.

**Comment by billwolfer** [comment] 2019-08-13 20:16
Today's log:

[kodi log 8-13.txt](https://github.com/croneter/PlexKodiConnect/files/3498698/kodi.log.8-13.txt)

**Comment by billwolfer** [comment] 2019-08-13 23:07
requested files here: https://github.com/billwolfer/stuff

**Comment by croneter** [comment] 2019-08-17 07:58
Thanks for the files. Sorry, but I need the 2 `db` files twice: once BEFORE the issue occurs, so when you still see all the video info. Then again after the video infos disappeared. Plus I need the log again to make the connection between the `db` files and what Kodi/PKC is doing. 

Sorry for the hassle, but you've encountered a really, really weird bug here... 😞

**Comment by billwolfer** [comment] 2019-08-17 18:56
Before and after gets kind of weird since after is the normal state. So here are the two db files labeled 'with-info' and 'without-info.' 

So, in the log, it starts without info, I instruct Plex to re-analyze the library, it goes back to normal, displays the info, then runs until the info disappears. And like an idiot, I rebooted after turning off the debug log, so look at 'old log' in the log file. 

Again, 'with-info' is BEFORE the issue occurs, although when the log starts, the info isn't displaying. Thanks.

[without-info.zip](https://github.com/croneter/PlexKodiConnect/files/3512346/without-info.zip)
[with_info.zip](https://github.com/croneter/PlexKodiConnect/files/3512347/with_info.zip)
[Kodi log 8-17.txt](https://github.com/croneter/PlexKodiConnect/files/3512348/Kodi.log.8-17.txt)

**Comment by charlie2alpha** [comment] 2019-08-17 20:58
I think I've encountered the same or similar issue. For me, what happens is that the skin I'm using stops displaying the aspect ratio of the video on the info bar and it happens consistently if I start playback. If I refresh the metadata in Plex or do a database repair from PKC settings then that info is back but it's annoying to do that. The issue is cosmetic really as it won't prevent playback or anything but irritating at the same time!

**Comment by croneter** [comment] 2019-08-26 09:35
@billwolfer 
OK, I figured out what's wrong. **NONE** of your Plex libraries are marked to be synched to Kodi. But PKC synches them anyway if PKC receives a websocket message from the PMS that a particular movie has changed (PKC "background sync"):
So there's 2 issues really:
* PKC background sync should not pick up on items that are in sections that should NOT be synched to Kodi
* Items are still visible in Kodi even though PKC actually deleted them (but they're not showing the "video info" you mentioned)

# Quick workaround for now
Mark all your Plex libraries to be synched to Kodi by going into the PKC settings, then Sync, then "Choose libraries to sync to Kodi"

# Log details for the poor dev
```
2019-08-17 10:33:22.664 T:3902517984  NOTICE: PLEX.sync.sections: Done synching sections from the PMS: [{'index': 0, 'name': '4K UHD Movies', 'section_id': 16, 'section_type': 'movie', 'sync_to_kodi': False, 'last_sync': None}, {'index': 1, 'name': 'Misc. Videos', 'section_id': 12, 'section_type': 'movie', 'sync_to_kodi': False, 'last_sync': None}, {'index': 2, 'name': 'Movies', 'section_id': 8, 'section_type': 'movie', 'sync_to_kodi': False, 'last_sync': None}, {'index': 3, 'name': 'Music', 'section_id': 4, 'section_type': 'artist', 'sync_to_kodi': False, 'last_sync': None}, {'index': 4, 'name': 'TV Shows', 'section_id': 15, 'section_type': 'show', 'sync_to_kodi': False, 'last_sync': None}]

2019-08-17 10:33:24.024 T:3902517984  NOTICE: PLEX.sync.full_sync: Start synching playstate and userdata for every item
2019-08-17 10:33:24.056 T:3336499936  NOTICE: PLEX.sync.full_sync: User chose to not sync section {'index': 0, 'name': '4K UHD Movies', 'section_id': 16, 'section_type': 'movie', 'sync_to_kodi': False, 'last_sync': None}
2019-08-17 10:33:24.056 T:3336499936  NOTICE: PLEX.sync.full_sync: User chose to not sync section {'index': 1, 'name': 'Misc. Videos', 'section_id': 12, 'section_type': 'movie', 'sync_to_kodi': False, 'last_sync': None}
2019-08-17 10:33:24.057 T:3336499936  NOTICE: PLEX.sync.full_sync: User chose to not sync section {'index': 2, 'name': 'Movies', 'section_id': 8, 'section_type': 'movie', 'sync_to_kodi': False, 'last_sync': None}
2019-08-17 10:33:24.058 T:3336499936  NOTICE: PLEX.sync.full_sync: User chose to not sync section {'index': 4, 'name': 'TV Shows', 'section_id': 15, 'section_type': 'show', 'sync_to_kodi': False, 'last_sync': None}

2019-08-17 10:33:24.463 T:3902517984   DEBUG: PLEX.sync.full_sync: Looking for items to delete
2019-08-17 10:33:24.649 T:3902517984   DEBUG: PLEX.movies: Removing movie with plex_id 2430, kodi_id: 1

2019-08-17 10:33:47.258 T:3531588320   DEBUG: PLEX.websocket_client: PMS_Websocket: Received message from PMS server: {u'TimelineEntry': [{u'itemID': 2430, u'title': u'3:10 to Yuma', u'mediaState': u'analyzing', u'sectionID': 16, u'state': 5, u'updatedAt': 1566063228, u'identifier': u'com.plexapp.plugins.library', u'type': 1}], u'type': u'timeline', u'size': 1}
2019-08-17 10:33:47.293 T:3531588320   DEBUG: PLEX.websocket_client: PMS_Websocket: Received message from PMS server: {u'TimelineEntry': [{u'itemID': 2430, u'title': u'3:10 to Yuma', u'mediaState': u'thumbnailing', u'sectionID': 16, u'state': 5, u'updatedAt': 1566063228, u'identifier': u'com.plexapp.plugins.library', u'type': 1}], u'type': u'timeline', u'size': 1}
2019-08-17 10:33:47.295 T:3531588320   DEBUG: PLEX.websocket_client: PMS_Websocket: Received message from PMS server: {u'TimelineEntry': [{u'itemID': 2430, u'title': u'3:10 to Yuma', u'sectionID': 16, u'state': 5, u'updatedAt': 1566063228, u'identifier': u'com.plexapp.plugins.library', u'type': 1}], u'type': u'timeline', u'size': 1}
2019-08-17 10:33:53.009 T:3902517984   DEBUG: PLEX.sync.websocket: Message: {u'timestamp': 1566063227, u'state': 5, u'attempt': 0, u'plex_id': 2430, u'plex_type': u'movie'}
2019-08-17 10:33:53.065 T:3902517984   DEBUG: PLEX.sync.websocket: Processing new/updated PMS item: 2430
2019-08-17 10:33:53.079 T:3902517984  NOTICE: PLEX.movies: ADD movie plex_id: 2430 - 3:10 to Yuma

2019-08-17 11:33:32.739 T:3902517984   DEBUG: PLEX.sync.full_sync: Looking for items to delete
2019-08-17 11:33:32.785 T:3902517984   DEBUG: PLEX.movies: Removing movie with plex_id 2430, kodi_id: 1
2019-08-17 11:33:32.817 T:3902517984   DEBUG: PLEX.movies: Deleted movie 2430 from kodi database
```

**Comment by croneter** [comment] 2019-09-08 14:27
Does PKC **BETA** version 2.9.6 help? You might want to reset the Kodi database first, in the PKC settings under Advanced

**Comment by billwolfer** [comment] 2019-09-08 18:06
It's been working fine since I synced the libraries almost two weeks ago, so I'm kind of reluctant to fool with it. Do you want me to try the beta version anyway?

**Comment by croneter** [comment] 2019-09-08 18:24
Naw, should be fixed now :wink:

**Closed by croneter** 2019-09-08 18:24 UTC
