### ISSUE TITLE
Newly added tv episodes not showing

### ISSUE THREAD

**Issue by hstamas** [croneter/PlexKodiConnect#28] opened 2016-05-09 01:54 UTC
Newly added shows don't appear until a full scan is triggered either per the schedule or manually. I beleive new items should be picked up by the constant scanning?

**Comment by Deihmos** [comment] 2016-05-09 14:20
Same issues as this https://github.com/croneter/PlexKodiConnect/issues/23  

At least I am not the only one.

**Comment by hstamas** [comment] 2016-05-09 18:13
Sorry, I did not notice the same issue had been already posted. I can confirm the same behavior as Delhmos. If a TV episode was added nothing gets updated. Adding a movie will refresh both the TV and the Movie section to the PMS's current state. Reverted back to 1.1.15 as I thought I remember this working before but same issue. Both PKC and PMS logs were sent this morning.

**Comment by croneter** [comment] 2016-05-09 19:50
Duplicate of #23

**Closed by croneter** 2016-05-09 19:50 UTC
