### ISSUE TITLE
PMS unaware of playback when playing from playlists?

### ISSUE THREAD

**Issue by OttoWerse** [croneter/PlexKodiConnect#1774] opened 2022-01-15 14:03 UTC
## Describe the bug
When I watch series episodes (haven't tested movies yet) from a playlist created on PMS, the episodes will not be marked as watched in PMS. They also do not show up in the PMS dashboard as being currently played and PMS will not automatically pick subtitles (I have it set up to always show them if available in English). 

If I watch the same episodes from the "TV shows" menu the sync of the playback state works just fine and they will show up in the dashboard too. and they will be automatically set to show subtitles too. 

I already did a full Kodi database rebuild, but not a full reset, but my PKC runs on default settings AFAIK and I haven't messed with paths or anything. 

I am not really sure if this is a bug, or if I am doing something wrong. I am using a lot of playlists on my PMS to watch series in different orders than the TV release order (chronological for Star Wars - The Clone Wars for example, or DVD order for some others, etc.). To play them in Kodi, I just go to the "Videos" tab (I am on Matrix and using the default skin) and select playlists there. There it lists me all the playlists from my PMS and from then I just click play on the one I want to watch. If this is not the right way to play a PMS hosted playlist in PKC please do tell and forget this issue!

## To Reproduce
Steps to reproduce the behaviour:
1. Create a Playlist on your PMS with some episodes of some series you haven't watched yet on it
2. Play the playlist in Kodi from start to finish
3. Look at the series in PMP or PMS
4. The episodes will still be marked as unplayed

## Expected behaviour
The episodes should be marked as played.

## You need to attach a KODI LOGFILE!
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/7875082/kodi.log)

I first played the episode from the playlist once (skipped just before the end) and then twice from the TV shows menu entry (forgot to check for subtitles the first time) but didn't skip until the end on those plays (as they showed up in the PMS dashboard, and I already tested this before)

**Comment by croneter** [comment] 2022-01-20 07:34
Duplicate of #756

**Closed by croneter** 2022-01-20 07:34 UTC
