### ISSUE TITLE
Re-syncs on every start

### ISSUE THREAD

**Issue by kocane** [croneter/PlexKodiConnect#565] opened 2018-12-02 18:20 UTC
I just installed 2.5.1. It seems every time I restart LibreELEC it re-syncs the library. It results in duplicate items.  I've tried clearing both pkc and kodi database. It happens on several Raspberry Pi devices with LibreELEC 8.2.5.  I've also tried uninstalling PKC and left over files completely but the same thing seems to happen.

This is the log:
https://pastebin.com/pyNN1E3H

**Comment by croneter** [comment] 2018-12-02 18:35
By the way - there has always been a sync on startup...

**Comment by kocane** [comment] 2018-12-02 18:52
@croneter but it processes everything like initial sync - is that normal for the new version because I don't remember it being like that before. Seems like a lot for the raspi to proces each time a user switches profile.

**Comment by dazedcrazy** [comment] 2018-12-02 18:59
Everytime it resynces on startup it adds another copy of what it added before
![image](https://user-images.githubusercontent.com/9027988/49343583-22742680-f664-11e8-9b4b-eb9e9e92724f.png)
![image](https://user-images.githubusercontent.com/9027988/49343584-2607ad80-f664-11e8-9a00-1b6148aa6f1c.png)
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/2637247/kodi.log)
I got up to 5 copies of each episode before i reset the db and it started all over again.

**Comment by kocane** [comment] 2018-12-02 20:13
@croneter the sync doesn't seem faster that the initial sync :-/ 

and I'm still getting duplicate items:
![image](https://user-images.githubusercontent.com/7694813/49344410-04fc8800-f677-11e8-9f28-2ffac2828cb7.png)

@dazedcrazy posted in this issue with the same problem but seemingly removed his post...?

**Comment by dazedcrazy** [comment] 2018-12-02 20:17
@kocane no i made a separate post just to make things easier

**Comment by kocane** [comment] 2018-12-02 20:18
@dazedcrazy oh didn't notice.. good :-)

**Comment by croneter** [comment] 2018-12-03 07:00
Closing as full-sync on startup is by design (and necessary) and #566 addresses the duplicate issue

**Closed by croneter** 2018-12-03 07:00 UTC

**Comment by danjames92** [comment] 2018-12-03 18:12
Can you confirm that in past PKC releases a full sync was not necessary every reboot?

Is there a reason this has changed?

**Comment by milnash** [comment] 2018-12-03 18:21
I agree with danjames92. It's doing a full initial sync on reboot. Or it seems like full initial because it takes hours...
