### ISSUE TITLE
2.7.0 - Family account permissions not honoured

### ISSUE THREAD

**Issue by joswart** [croneter/PlexKodiConnect#723] opened 2019-02-13 13:31 UTC
After installing 2.7.0 and reconnecting to Plex, I get to appoint the right family member account.
After this all libraries (including the one, not available to this member of the family) are synchronized and playable. It seems plexkodiconnect uses the main account for its authentication and does not change it user to the family member.

This is a huge issue, with automatic updates. The kids HTPC is now able to play all non-kid movies.

Completely disconnecting from plex and going through the plex.com/pin - action again, fixes the issue.

**Comment by joswart** [comment] 2019-02-14 15:02
It seems that the combination of Leia and PKC 2.7.0 might be the issue here.

I just upgraded the last system in my house to leia. This one was already running on PKC 2.7.0. After the upgrade to Leia it started a resync. And although my user does not have access to all libraries, it did start syncing all libraries.

I confiremd in the PKC settings, that the user name used is indeed the non-privileged user.

**Comment by croneter** [comment] 2019-02-17 10:46
With 2.7.0, the sign-on process changed. Once you ARE using 2.7.0, I don't think you can manage to reproduce the issue that your account permissions are not honored.

I, for one, cannot reproduce your issue. Can you?

If not, this is a one-time issue due to the update from 2.6.x to 2.7.0. And I'll leave it at that...

**Comment by joswart** [comment] 2019-02-17 11:22
I have ran into the issue three times during upgrades. 

I am not 100% sure, but I think I also saw it when resetting everything (the red line in the PKC options). Since I really can’t have extended privileges on my system, I have currently pinned all kodis to 2.6.5.

If everything is as you described, a complete login cycle would be preferable on upgrade. Just to make sure.

**Comment by croneter** [comment] 2019-02-18 04:41
Please reproduce the bug and let me know how you did it

**Comment by croneter** [comment] 2019-02-22 14:32
Please reproduce the bug and let me know how you did it. Otherwise I will close this issue

**Comment by joswart** [comment] 2019-02-23 12:31
Leave it at that. I cannot reproduce it after the upgrade.  

Jord

**Comment by croneter** [comment] 2019-02-23 12:45
OK, thanks for checking. I thought I was too silly to reproduce it myself :wink:

**Closed by croneter** 2019-02-23 12:45 UTC
