### ISSUE TITLE
High Plex server CPU Usage even on idle with PKC enabled

### ISSUE THREAD

**Issue by fr500** [croneter/PlexKodiConnect#1205] opened 2020-07-28 19:44 UTC
## Describe the bug
Using this plugin causes high CPU usage on my PMS even if idle in the KODI main screen

IDLE:
![imagen](https://user-images.githubusercontent.com/1721040/88713040-4e1d0d80-d0e0-11ea-8524-607aba32285d.png)

If I kill KODI:
![imagen](https://user-images.githubusercontent.com/1721040/88713086-5d03c000-d0e0-11ea-9953-10cca9845c8b.png)

I figured it could be caused due to permanent background updating which I disabled since. Not sure what to do to reduce this unnecessary load

**Comment by croneter** [comment] 2020-07-29 05:11
How about sharing your Kodi DEBUG log for the timeframe you shared the screenshots above? 

PKC sync a TON of artwork through the PMS in the background after installation. That takes a couple of hours and probably causes CPU spike. Have you let Kodi sit overnight to see what happens?

**Comment by fr500** [comment] 2020-07-29 05:29
Seems to be my music database, it's... big yes.
So I disabled that since my server is so weak and has some cooling issues.

I can try to dig further in the weekend

EDIT: mhhh thought I uploaded a log but alas... I forgot, I'll try again.

**Comment by croneter** [comment] 2020-08-03 09:04
Closing this as it was very probably caused by PKC downloading all the metadata in the very beginning...

**Closed by croneter** 2020-08-03 09:04 UTC
