### ISSUE TITLE
The movies takes several minutes to start after launching it

### ISSUE THREAD

**Issue by Cyriltra** [croneter/PlexKodiConnect#383] opened 2017-12-30 13:09 UTC
Hi Croneter,

so I did a fresh reboot and start a debug log right after. I don't have the video extra addon.
After the reboot, I played 3 movies: the first 2 started almost immediately after I click on their respective poster. But the last one took several minutes (I click around 20h45 and it started close to 20h48). In the log it looks like there is a scan of the library happening.

[Here is the log file (70 MB)](https://file.io/0KPI9w)

Thank you

**Comment by Cyriltra** [comment] 2018-01-07 06:05
I think I know what is happening:
I usually watch movies with subtitles, so I download it, place it in the folder, then trigger a scan of Plex library to force the subtitles to be recognised, then play the movie.

I believe the full library scan also forces pkc to update all files, right ? (it's what I see in the logs).

Is it possible to cancel or pause this update when a movie is about to start ?

Thank you

**Comment by croneter** [comment] 2018-01-07 08:17
I don't think your problem is caused by a PKC sync. Because the sync would immediately cancel on playback start.
I'm currently completely rewriting the playback startup code. Hope your issue will be solved then

**Comment by croneter** [comment] 2018-01-07 10:00
@Cyriltra 
Your log file is already not online anymore. Could you please upload it again here directly on Github? Thx

**Comment by Cyriltra** [comment] 2018-01-07 11:26
Hi, file is too big to host on github. [here is it again](https://file.io/1rvUwB)
Thank you

**Comment by croneter** [comment] 2018-02-05 20:25
Does the new 2.0.0 beta version help?

**Comment by croneter** [comment] 2018-02-08 10:23
Please re-open this issue if it's not fixed with PKC > 2.0.2

**Closed by croneter** 2018-02-08 10:23 UTC

**Comment by Cyriltra** [comment] 2018-02-08 14:20
Hi, I would like to try but how to update to 2.0.2 beta ?

**Comment by croneter** [comment] 2018-02-08 14:30
Install the BETA repository from here: https://github.com/croneter/PlexKodiConnect

**Comment by Cyriltra** [comment] 2018-02-08 14:49
ok, it seems ok so far :)
I will continue to monitor logs for a while when watching movies to be sure

Thx
