### ISSUE TITLE
Kodi does not remember TV episode as completely watched

### ISSUE THREAD

**Issue by Sparh4wk** [croneter/PlexKodiConnect#362] opened 2017-11-13 10:42 UTC
Hi,

I have problem with PKC in Kodi.
Everything works great, except watched status.
When I regulary watch episode, it change to watched like this:

![image](https://user-images.githubusercontent.com/7014826/32721638-6cc0a320-c867-11e7-9871-724a5a4d501d.png)

but when I go back to shows list and back to the same series again, it will show it as unwatched:

![image](https://user-images.githubusercontent.com/7014826/32721658-82dd0e64-c867-11e7-8f95-d3aacde168bd.png)

only way to mark it as watched for real, is marked series not a episode.
Any clue on this one?

**Comment by croneter** [comment] 2017-11-13 11:05
* Does this happen every time you finish watching something?
* On the last picture: is the episode partially watched (so you can continue watching, e.g. at minute 34). Or is completely unwatched and you'd start watching again at the beginning. 
* I don't understand `only way to mark it as watched for real, is marked series not a episode.` Could you please explain what you mean?
* Are you using the default Kodi skin Confluence?

**Comment by Sparh4wk** [comment] 2017-11-13 11:58
1. yes
2. completely unwatched and you started from beginning
3. like this:

![image](https://user-images.githubusercontent.com/7014826/32724625-568f67ac-c872-11e7-870e-acced0c593a7.png)

4. yes Im using default skin

**Comment by croneter** [comment] 2017-11-13 12:02
OK, thanks. 
* Does this only happen for TV episodes, not for movies?
* If you STAY on the Kodi screen after you've finished watching an episode, everything works fine? Only if you navigate a level up (e.g. going to the Kodi TV shows overview) and then come immediately back, this issue happens?

**Comment by Sparh4wk** [comment] 2017-11-13 12:05
1. only for tv episodes, movies are fine
2. yes, if I stay on episodes overview I can see it mark as watched.. but after I go anywhere else and then go back to episodes overview, its not marked :(

**Comment by croneter** [comment] 2017-11-13 12:09
OK, this is a weird Kodi bug then. Seems like Kodi caches an episode view/listing, PKC updates the watched status, then Kodi does not refresh its cached listing for some reason. Widgets are not affected, I guess. 

Sorry, nothing I can do from the PKC side of things as far as I can see. Plus I think this is a "fringe case" 😉

**Comment by abrenoch** [comment] 2017-11-17 19:09
I'm noticing the same behavior here - if there is anything I can contribute to possibly help please let me know!

**Comment by Draic** [comment] 2017-12-02 23:07
I have this issue aswell. Kodi will not remember watch status if you leave and re-enter the episodes overview. Only if PKC triggers a sync with the plex server (depending on settings in PKC, or after a reboot), this will get corrected. So I would have thought this is a problem with how PKCs constant background sync works

**Comment by Sparh4wk** [comment] 2017-12-04 20:08
yep it doesnt seems to be a kodi isue, but we will see.

**Comment by d0ogie** [comment] 2017-12-11 23:34
Just adding a +1 for this exact behavior, which I see across 4 NVIDIA SHIELD TV devices very consistently. I'm also switching from Emby and did not see it there.

What it amounts to is a delay in watched status update, which you can really cause some interesting behavior by doing the following:

-Partially watch a TV episode and stop playback. Kodi marks state as nn% watched.
-Context menu -> mark as watched. Nothing changes in Kodi - still marked nn% - however PMS shows correctly marked as watched
-Context menu -> still being presented with "Mark as Watched"

Particulars:
NVIDIA SHIELD TV, SPMC 16.7.2

PMS (on LAN, no cloudflare/proxy/etc getting in the way here):
CentOS 7.4
Name        : plexmediaserver
Arch        : x86_64
Version     : 1.10.0.4523

**Comment by Sparh4wk** [comment] 2017-12-18 07:29
@croneter so it seems its not kodi bug.. can you please look at it, if you have some spare free time? thanks

**Comment by hstamas** [comment] 2018-01-07 04:16
I left Plex/PKC for Emby precisely  because of this behavior. With 2 toddlers running around, I start and stop shows often. Not being able to resume reliably or having shows that I’ve already watched all of the sudden be marked unwatched was driving me nuts. Recently tried this setup again and I see it’s still happening unfortunately. I REALLY want this to work as I much prefer a Plex backend but the  Emby/Emby for Kodi combo works so much more reliably in this instance.

**Comment by Draic** [comment] 2018-01-09 06:52
I just want to add that it is happening for movies just aswell, unlike previously claimed. Plex gets proper updates on the progress of the files (how much minutes you are into a movie/episode), but once playback finishes, it will just not mark the file as played. I do not understand why this is a difficult problem to fix. Some explanation could help provide better informations/logs to pinpoint the issue. 

This is NOT a kodi bug.

**Comment by CraftyClown** [comment] 2018-02-04 00:09
I can confirm the same behaviour with both TV shows and Movies.

**Comment by Draic** [comment] 2018-02-06 22:37
I tested beta 2.0.1. Watched state seems to be broken completely now. Items are not marked as watched neither in kodi, nore in plex (in earlier versions atleast plex received the correct watch state).

**Comment by croneter** [comment] 2018-02-07 07:27
@Draic please share your DEBUG logs as explained here on the wiki. Works perfectly fine here for me!

**Comment by croneter** [comment] 2018-02-07 07:28
Actually, please open a new github issue please

**Closed by croneter** 2018-02-07 07:28 UTC
