### ISSUE TITLE
Database Compressing Continually

### ISSUE THREAD

**Issue by heinj98** [croneter/PlexKodiConnect#348] opened 2017-09-27 00:10 UTC
There was a bug request #238 that was fixed by doing a database reset.  This didn't work in my case.  What did work was turning off the 'enable background sync' that is set to occur every 5 seconds.  When watching a movie you couldn't tell anything was going on, but if you were looking at your movie library it was causing the spinner circle to come up every 5 seconds and make the experience unusable.  Disabling this option solved the problem.

**Comment by croneter** [comment] 2017-09-27 05:47
* Did you try to do another database reset? 😉 
* Could you share Kodi debug logs of this occuring according to https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by croneter** [comment] 2017-10-02 06:38
Any news here?

**Comment by RickDB** [comment] 2017-10-06 08:31
Do notice a Kodi UI refresh every 5s which messes up list item position which is new, how I can reproduce it here consistently:

- In Kodi settings set jump to first unwatched episode
- Open a series season you have partially watched and navigate a bit thru the list
- You will notice some sort of background refresh where after it will jump to the first unwatched episode

But can also notice it with normal navigation thru TV shows, it will get a background refresh and might be set to a incorrect list position (last known before refresh).

Almost like something is triggering a xbmc.refresh() or that Kodi 17.4 changed this behavior because setup config here has been pretty static for the past few months, will try to collect some logs soon but didn't notice anything useful yet.

**Comment by croneter** [comment] 2017-10-06 12:08
Ouh not good. Please enable kodi debug logging. I should be able to spot repeated PKC "refreshes" easily

**Comment by croneter** [comment] 2017-10-14 09:14
Any news here?

**Comment by RickDB** [comment] 2017-10-16 08:56
After PMS update can't replicate it anymore, what seemed to be happening is that PMS was tripping over files with incorrect mediainfo which caused it to enter a re-scanning loop and triggering a notification on the PKC side as if it were a modified / new entry.

But looks to be fixed on Plex end and if it returns will let you know :)

**Comment by croneter** [comment] 2017-10-16 09:28
Awesome, thanks for the update. Just reopen this issue should it happen again

**Closed by croneter** 2017-10-16 09:28 UTC

**Comment by Crono141** [comment] 2017-11-09 02:00
This issue is still happening. Have a raspberry pi 3 with PKC and every 5 seconds I get the dreaded compressing database of doom. My server is fully up to date.

**Comment by croneter** [comment] 2017-11-09 18:04
@Crono141 
Please share your Plex media server log here. Chances are that the PMS keeps scanning a certain (damaged) file and thus causes these refreshes.

**Comment by sebastiaanluca** [comment] 2017-11-09 22:25
@Crono141 Best to just check your activity log on the web page of you plex media server. If it keeps spewing out scanned entries, something's wrong on the side of Plex.
