### ISSUE TITLE
Native skin support

### ISSUE THREAD

**Issue by bkury** [croneter/PlexKodiConnect#745] opened 2019-02-23 19:52 UTC
Hi,

I've already implemented plexkodiconnect in my skin and noticed the following issue with inprogress/ondeck widgets:
```
<content target="videos">$INFO[Window(Home).Property(Plex.nodes.XX.ondeck.content)]</content>
```
This is only working for TV sections and not movie sections. I have also tried (Plex.nodes.XX.inprogress.content) which also doesn't return the correct movie items. Am I missing something?

Thanks for your work on this addon!

**Comment by croneter** [comment] 2019-02-24 10:37
The nodes are a mess, honestly. I'm currently reworking them.

**Comment by bkury** [comment] 2019-02-24 17:18
I see, thanks for your quick reply! Happy to test when you are done ....

**Comment by croneter** [comment] 2019-03-11 17:42
All good with beta 2.7.5?

**Comment by bkury** [comment] 2019-03-11 18:20
Widgets not showing up for me, tested on a complete fresh kodi/plexkodiconnect installation:
```
KODI 18.2+git20190310 
PlexKodiConnect 2.7.5

$INFO[Window(Home).Property(Plex.nodes.0.ondeck.content)]
$INFO[Window(Home).Property(Plex.nodes.0.recent.content)]

are these properties still correct?
```

kodi.log:
```
2019-03-11 19:08:58.821 T:139948647495424   ERROR: GetDirectory - Error getting /home/plexkodiconnect/.kodi/userdata/library/video/Plex-2/2_ondeck.xml
2019-03-11 19:08:58.821 T:139948647495424   ERROR: GetDirectory - Error getting /home/plexkodiconnect/.kodi/userdata/library/video/Plex-2/2_recent.xml
2019-03-11 19:08:58.821 T:139948647495424   ERROR: GetDirectory - Error getting /home/plexkodiconnect/.kodi/userdata/library/video/Plex-1/1_ondeck.xml
2019-03-11 19:08:58.821 T:139948647495424   ERROR: GetDirectory - Error getting /home/plexkodiconnect/.kodi/userdata/library/video/Plex-1/1_recent.xml

but all xml files are actually there and have proper syntax/content:
-rw-rw-r-- 1 plexkodiconnect plexkodiconnect 355 Mar 11 19:04 /home/plexkodiconnect/.kodi/userdata/library/video/Plex-2/2_ondeck.xml
```

**Comment by bkury** [comment] 2019-03-11 22:04
I did some more testing and noticed the following issues:

Home menu item:
---
```
<onclick>$INFO[Window(Home).Property(Plex.nodes.0.path)]</onclick>
```
This path opens up the node root/overview (On Deck, Recently Added, ...) instead of going directly to the "all" content section. (worked before 2.7.5)

OnDeck section:
---
Container.Content() not set in the OnDeck section, works fine with every other section (Recently Added, Recommended, Random, ..)

**Comment by croneter** [comment] 2019-03-17 17:12
Working now with 2.7.7?

**Comment by croneter** [comment] 2019-03-17 19:25
Where's your source code anyway? Then I could test myself :laughing:

**Comment by bkury** [comment] 2019-03-18 05:14
I've made a small modified version of home.xml for estuary which adds 3 plex nodes and some "debug" output for you to test with: (replace estuary's home.xml with this one) :
http://openht.org/download/Home.xml.zip

Here is the issue, currently `$INFO[Window(Home).Property(Plex.nodes.0.ondeck.content)]` returns the file path of plexkodiconnect's node xml file e.g. `/home/plexkodiconnect/.kodi/userdata/library/video/Plex-2/2_ondeck.xml` (this won't work with skins or kodi's dynamic content feature)

To make it work, `$INFO[Window(Home).Property(Plex.nodes.0.ondeck.content)]` should actually return the plugin path which is already in that xml node file e.g. `plugin://plugin.video.plexkodiconnect?plex_type=movie&amp;section_id=2&amp;key=%2Flibrary%2Fsections%2F2%2FonDeck&amp;mode=browseplex`

Thanks!

**Comment by croneter** [comment] 2019-03-18 05:21
This is On Deck only? The other nodes all work?

**Comment by bkury** [comment] 2019-03-18 05:37
None of the nodes work, e.g. `$INFO[Window(Home).Property(Plex.nodes.0.RECENT.content)]` also returns the node xml filepath instead of the actual plugin path

**Comment by croneter** [comment] 2019-03-19 14:51
Other question: how do I/we document this, e.g. Here on the Github Wiki or in a separate Readme for other skinners?

**Comment by bkury** [comment] 2019-03-19 15:58
I would just add a "skin integration" wiki page and reference it in the README.md and/or forum threads. I'm happy to help you with that as soon as everything is working and I have some spare time.

**Comment by bartolomesoriano** [comment] 2019-03-19 18:01
@bkury,  sorry for the noob question.  Where did you get the info for the paths to use for On Deck, etc.? I am looking for just that to help me integrate PKC to Amber skin for Leia. Any help is greatly appreciated.

**Comment by bkury** [comment] 2019-03-20 06:26
@bartolomesoriano: 

If you want to get the folder path you are currently in (useful for dynamic content / widgets), you can do something like this:
- Add a "debug" label control to your MyVideoNav.xml ($INFO[ListItem.FolderPath]) or if it's a specific container like e.g. home menu use $INFO[Container(ID).ListItem.FolderPath]

If you want to get the direct path of an item (useful for direct link or playmedia() function) you can do something like this:
- Same as above but you have to use $INFO[ListItem.FileNameAndPath]
- You can also add an item to favorites (Context Menu --> Add to favourites) and then look it up in your favourites.xml file (USERDATAHOME/userdata/favourites.xml)


You probably don't need any of this to integrate plexkodiconnect into your skin, it's going to be pretty easy as soon as @croneter has fixed the nodes:

Home menu (PLEX sections):
---
```
<item id="xxx">
   <label>$INFO[Window(Home).Property(Plex.nodes.[0-20].title)]</label>
   <onclick>$INFO[Window(Home).Property(Plex.nodes.[0-20].path)]</onclick>
   <property name="type">$INFO[Window(Home).Property(Plex.nodes.[0-20].type)]</property>
</item>
```

Widgets
---
```
<control type="list">
   ...
   <content target="videos" limit="20">$INFO[Window(Home).Property(Plex.nodes.[0-20].[TARGET].content)]</content>

   e.g.
   <content target="videos" limit="20">$INFO[Window(Home).Property(Plex.nodes.0.ondeck.content)]</content>
</control>
```
Available targets: 
`ondeck / recent / recommended / genres / lastplayed / random / sets / all`

Hope this helps and let me know If you have any questions ...

**Comment by bartolomesoriano** [comment] 2019-03-20 09:05
Thank you so much @bkury! I appreciate the detailed info and will get to work with it.

**Comment by croneter** [comment] 2019-03-21 19:39
How about 2.7.8?

**Comment by bkury** [comment] 2019-03-21 20:34
Looks good to me!

So, instead of using full static paths you are now using "library://video/plex-xx" to point to your xml node files? I didn't know that you can use these node xml files with kodi's dynamic content feature directly, that's even better. Well done!

**Comment by croneter** [comment] 2019-03-21 20:43
Do you somehow need the Kodi type, e.g. 'movie', as well, by the way?

**Comment by bartolomesoriano** [comment] 2019-03-21 20:48
@croneter , if you mean PKC returning this info to Kodi so that you can determine what type of content is in the container, then, yes, this is really useful and important.

**Comment by bkury** [comment] 2019-03-21 20:59
> Do you somehow need the Kodi type, e.g. 'movie', as well, by the way?

Isn't this already working? I've tested it and everything seems to work fine ...

Home menu 
---
**$INFO[Window(Home).Property(Plex.nodes.[0-20].type)]**
Returns PLEX section content type (movies, episodes, ...)

Widgets
---
**$INFO[ListItem.DBType]**
Returns widget item content type (movie, episode, ..)

**Comment by bkury** [comment] 2019-03-29 17:04
**Found a small issue:**
OnDeck Section doesn't have Container.Content() set

How to replicate:
Estuary skin --> Home Menu --> Videos --> [PLEX NODE] --> OnDeck --> Container.Content is not set

Other sections (recently added, recommended, ..) are working fine and have Container.Content set properly.

Nice to have
---
These are just things which would be nice to have :

- Duration for TV Shows (ListItem.Duration) / Plex Server XML tag (e.g. duration="1034571")
- Option to sync theme audio files: 

Most TV Shows have a audio theme file (Plexserver XML: e.g. theme="/library/metadata/44030/theme/1553598481"). It would be nice to sync these files to your local device and then add a TV Show item property with a direct link to the audio file (e.g. ListItem.Property(theme)) --> [CACHE_DIR]/[ID]/theme.mp3

With this feature it would be possible to play a certain theme file while browsing TV Shows / Episodes.

---

Again, these are just ideas, everything else is working perfectly. Thanks again for your work on this addon!

**Comment by croneter** [comment] 2019-04-14 08:52
@bkury 
I can't really replicate the OnDeck issue. Seems to be working just fine, e.g. using the Embuary skin and pointing links and/or widgets to a PKC OnDeck node. 
Could you please shed some more light on this?

**Comment by bkury** [comment] 2019-05-23 12:33
> @bkury
> I can't really replicate the OnDeck issue. Seems to be working just fine, e.g. using the Embuary skin and pointing links and/or widgets to a PKC OnDeck node.
> Could you please shed some more light on this?

Sorry for the late response, didn't get a github notification for your reply ...

It's difficult to explain because not all skins are using conditions like this. I will add some debug code to estuary tomorrow, so you can see for yourself what I mean.

**Comment by croneter** [comment] 2019-06-05 07:16
All good here? Or is there still an issue?

**Comment by bkury** [comment] 2019-06-05 19:00
Sorry, I finally have some spare time ...

I have added some "Estuary" debug code for you to test with, just download and replace your existing Includes.xml file: [Download Includes.xml.zip](http://openht.org/download/Includes.xml.zip)

You should now have a "Container.Content, ListItem.DBType and ListItem.Duration" debug line at the top of the skin.

To replicate the issue navigate from your homescreen to:
- Videos --> [PLEX NODE] --> On Deck --> Item (Container.Content is not set --> NOT GOOD)
- Videos --> [PLEX NODE] --> Recently Added --> Item (Container.Content is set correctly --> GOOD)

ListItem.Duration
---
As already mentioned, plex provides a duration tag for TV shows which would be nice to have when browsing plex nodes. (but to be honest I don't know if it's even possible to set ListItem.Duration for a tv show item or if this tag is only available for episodes)

Audio Theme File Syncing:
---
Have you thought about that? Again, this is nothing major or important, it's just another step to a complete plex experience/integration ...

Thanks again for your work!

**Comment by croneter** [comment] 2019-06-30 06:25
Sorry it took so long

What I don't understand: what path is `Container` actually? 🙈 

Current code DOES set e.g. `<Container>.Content`, but apparently the path for Container is off. It currently points to the video library xml: `library://video/Plex-<id>/<ondeck-xml>`. See line 349 here: https://github.com/croneter/PlexKodiConnect/blob/master/resources/lib/library_sync/sections.py

**Comment by bkury** [comment] 2019-06-30 07:54
Sorry, I always try to explain things from a skin coding perspective ... let me try that again:
(In this case: Node 4, TV Shows)

Let's compare the 2 node xml files :
```
special://library/video/Plex-4/4_recent.xml     (WORKING)
special://library/video/Plex-4/4_ondeck.xml   (NOT WORKING)
```
4_recent.xml is type "filter" (WORKING) whereas 4_ondeck.xml is type "folder" (NOT WORKING). As far as I know, type "folder" can't have a content type set.

It's always better to use type "filter" when linking to actual content, type "folder" is only useful when linking to another menu like you did with "4_more.xml".

So, 4_ondeck.xml should be changed from type="folder" to type="filter", you can use the following rule to only display inprogress stuff:
```
<rule field="inprogress" operator="true" />
```

I hope this helps to clear things up, thanks!

**Comment by bkury** [comment] 2019-06-30 10:14
In addition to the change above there is another thing I would suggest to fix this problem on an addon level.

resources/lib/entrypoint.py (line 172, def show_listing)
```
    if content_type == 'video':
        xbmcplugin.setContent(int(sys.argv[1]), 'videos')
    elif content_type == 'audio':
        xbmcplugin.setContent(int(sys.argv[1]), 'artists')
    elif plex_type in (v.PLEX_TYPE_PLAYLIST, v.PLEX_TYPE_CHANNEL):
        xbmcplugin.setContent(int(sys.argv[1]), 'videos')
    elif plex_type:
        xbmcplugin.setContent(int(sys.argv[1]),
                              v.MEDIATYPE_FROM_PLEX_TYPE[plex_type])
```
change priority/order to:
```
    if plex_type in (v.PLEX_TYPE_PLAYLIST, v.PLEX_TYPE_CHANNEL):
        xbmcplugin.setContent(int(sys.argv[1]), 'videos')
    elif plex_type:
        xbmcplugin.setContent(int(sys.argv[1]),
                              v.MEDIATYPE_FROM_PLEX_TYPE[plex_type])
    elif content_type == 'video':
        xbmcplugin.setContent(int(sys.argv[1]), 'videos')
    elif content_type == 'audio':
        xbmcplugin.setContent(int(sys.argv[1]), 'artists')
```
There is no reason to guess_content_type() if plex_type is already set. With this change even direct path links like ```plugin://plugin.video.plexkodiconnect?plex_type=movie&amp;section_id=2&amp;key=%2Flibrary%2Fsections%2F2%2FonDeck&amp;mode=browseplex``` should have the correct content_type set.

**Comment by croneter** [comment] 2019-07-01 05:26
Great, filter xml nodes don't support plugin:// paths. That will need some more work

**Comment by bkury** [comment] 2019-07-01 08:12
Hmm, may I ask what you want to do? I don't see the need of filter nodes with plugin:// path support ... [ID]-ondeck.xml is the only node which should be changed from "type=folder" to "type=filter", all other nodes are fine?

Did I miss something?

**Comment by croneter** [comment] 2019-07-01 15:38
The `More....` nodes are shown via plugin://, as well as e.g. the Plex Hub. But I know what to do - just need the time 😉

**Comment by croneter** [comment] 2019-07-07 16:15
@bkury Does BETA version 2.8.8 help? Cheers for the adjusted skin file, that helped a lot!! 😆

**Comment by bkury** [comment] 2019-07-07 17:46
There are some issues with 2.8.8:

- It breaks the home menu items added with ```Window(Home).Property(Plex.nodes.0.path)```, the link will open the root directory of the node instead of going directly to the media.

- ```Window(Home).Property(Plex.nodes.[id].ondeck.content)``` is still a plugin link (e.g. plugin://plugin.video.plexkodiconnect/?mode=browse...) , should link to e.g. "library://video/plex-[ID]/[ID]_ondeck.xml)

- ```Window(Home).Property(Plex.nodes.[id].recent.content)``` is working fine, links to library://video/Plex-[id]/[id]_recent.xml

**Comment by bkury** [comment] 2019-07-07 19:33
By the way, I've updated my skin ... feel free to test 2.8.8 with it:
https://bit.ly/night4kodi

**Comment by croneter** [comment] 2019-07-13 14:38
Try beta version 2.8.10

* `Window(Home).Property(Plex.nodes.0.path)` should be fixed. 
* `Window(Home).Property(Plex.nodes.[id].ondeck.content` points to plugin paths, that's correct as PKC cannot replicate the Plex On Deck 100%. You'd need to use `Plex.nodes.[id].pkc_ondeck.content` for the faster PKC nodes that might not display the exact same items that e.g. Plex Web shows

**Comment by bkury** [comment] 2019-07-13 15:56
> `Window(Home).Property(Plex.nodes.0.path)` should be fixed.

Looks good!

> * `Window(Home).Property(Plex.nodes.[id].ondeck.content` points to plugin paths, that's correct as PKC cannot replicate the Plex On Deck 100%. You'd need to use `Plex.nodes.[id].pkc_ondeck.content` for the faster PKC nodes that might not display the exact same items that e.g. Plex Web shows

Thanks for the hint, going to use pkc_ondeck from now on. 
One question though, it seems like ``Plex.nodes.[id].pkc_ondeck.content`` is only available for movie nodes, TV nodes don't have a pkc_ondeck.xml file, bug?

**Comment by croneter** [comment] 2019-07-13 16:35
Nope, not a bug, there is simply no way to replicate Plex On Deck using Kodi library functionality. If you know of one - happy to implement!

**Comment by croneter** [comment] 2019-07-13 16:36
Hmmm, should I switch and call the nodes 'ondeck' and the original Plex one 'plex_ondeck'? That way you can always point to 'ondeck'

**Comment by bkury** [comment] 2019-07-13 17:29
> Hmmm, should I switch and call the nodes 'ondeck' and the original Plex one 'plex_ondeck'? That way you can always point to 'ondeck'

Yes, that would be really helpful ... thanks! 

About plex on deck functionality:
The in progress episodes stuff isn't that hard to do if you generate a smartplaylist for it:
```
<smartplaylist type="episodes">
        <name>InProgress</name>
        <match>all</match>

        <rule field="tag" operator="is">
                <value>TV Shows</value>
        </rule>

        <rule field="inprogress" operator="true" />

        <order direction="descending">lastplayed</order>
</smartplaylist>
```
But I don't think that there is a way to replicate the "show first episode of a new season when TV show continues" feature.

**Comment by croneter** [comment] 2019-07-14 05:44
> About plex on deck functionality:
> The in progress episodes stuff isn't that hard to do if you generate a smartplaylist for it:
Nope, that does not work. It only returns episodes that are halfway watched. There IS no native Plex On Deck-like functionality for tv shows, see here: https://forum.kodi.tv/showthread.php?tid=343864

**Comment by croneter** [comment] 2019-07-14 11:03
Done in 2.8.11. 

Anything else? Otherwise I'll close this issue 😉

**Comment by bkury** [comment] 2019-07-14 11:09
> > About plex on deck functionality:
> > The in progress episodes stuff isn't that hard to do if you generate a smartplaylist for it:
> 
> Nope, that does not work. It only returns episodes that are halfway watched. There IS no native Plex On Deck-like functionality for tv shows, see here: https://forum.kodi.tv/showthread.php?tid=343864

Yes, unfortunately, I noticed that too after playing around with smartplaylists trying to replicate the plex on deck functionality. Anyway, this is not going to happen without KODI devs adding "real" inprogress and continue episode filter rules, (I would create a KODI feature request for that but I already know that nobody would care or reply :-)

Let's just stick with plex on deck and thanks for renaming all nodes to "ondeck"

> Anything else? Otherwise I'll close this issue 

Not really, everything seems to be fine now, also I think I bothered you enough :-) 
Thanks so much for your help and support!

**Comment by croneter** [comment] 2019-07-14 11:26
Thanks for integrating PlexKodiConnect :wink:

**Comment by croneter** [comment] 2019-07-14 11:39
@bkury Could you please add a PlexKodiConnect wiki section on skinning so other skinners can profit as well? Currently, nothing is really documented

**Comment by bkury** [comment] 2019-07-14 11:57
> @bkury Could you please add a PlexKodiConnect wiki section on skinning so other skinners can profit as well? Currently, nothing is really documented

Sure, I've already documented most of the stuff, just need some time to make it look nice for the wiki (formatting)

And as a small thank-you:
I'm also working on a plexkodiconnect ``<include>`` file for "Estuary", so that the majority of plexkodiconnect users can use the default skin and still enjoy all features and widgets.

**Comment by croneter** [comment] 2019-07-14 12:30
Awesome!! Let me know if I can help somehow

**Comment by bkury** [comment] 2019-08-15 17:12
Just a small update: 
Sorry, I'm pretty busy at the moment but I didn't forget about it!

**Comment by bkury** [comment] 2019-08-30 00:49
All right, estuary plexkodiconnect integration is almost done. A friend of mine is already testing it but we encountered a problem.

It's a little bit difficult to explain but basically is seems like using KODIs database for widgets isn't a good idea after all, if you have a large plex library.

It pretty much comes down to this: 
KODI loads the skin and starts a thread for every widget control (inprogress/recently added/random) for every node. Now, my friend has 6 nodes, each node contains about 5-10k media items, so it seems like KODI is locking the database with querying ~10k items x 3 widgets (ondeck/recent/random) x 6 nodes which takes almost 1 minute (100% cpu) for the widgets to even show up.

What do you think? (going back to using direct plugin path links instead of kodi's db?)

**Comment by bkury** [comment] 2019-08-30 00:56
On another subject, may I use PlexKodiConnect in my upcoming all-in-one KODI "fork" ?

**Comment by croneter** [comment] 2019-08-30 06:58
Good to know that you are almost done. Seems to me like another Kodi issue :wink:. Having such a large library, this issue will pop up even if you are using Kodi natively without PKC. As most people won't have such a large library, I'd stick to the current solution with Kodi "native" widgets where ever possible

**Comment by croneter** [comment] 2019-08-30 06:59
You may, after you've updated the wiki with a how-to for skinners like promised above :stuck_out_tongue_closed_eyes:

**Comment by bkury** [comment] 2019-08-30 13:56
First revision:
https://github.com/croneter/PlexKodiConnect/wiki/Skin-integration

**Comment by croneter** [comment] 2019-09-14 15:44
@bkury Great, many thanks!!! I already appended some stuff.

**Closed by croneter** 2019-09-14 15:44 UTC
