### ISSUE TITLE
Yatse crashes Kodi when playing Movie

### ISSUE THREAD

**Issue by abedo2015** [croneter/PlexKodiConnect#981] opened 2019-09-02 21:57 UTC
Hi, I saw that someone has uploaded a similar question and I'm sorry that I'm asking a bit of a repeat, but I am having issues with starting a file on PKC with Yatse. Kodi will attempt to load the file and then immediately crash. I have provided the log file and any help would be greatly appreciated! Thank you.
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/3567144/kodi.log)

**Comment by croneter** [comment] 2019-09-03 06:09
Duplicate of #966

**Closed by croneter** 2019-09-03 06:09 UTC
