### ISSUE TITLE
There is a phenomenon in which only one video is viewed and then forced to exit

### ISSUE THREAD

**Issue by tjtnsgns** [croneter/PlexKodiConnect#1428] opened 2021-03-22 07:58 UTC
I am currently using Kodi 19stable and using the community site to get a plex server and use the pkc.
There is a phenomenon in which only one video is viewed and then forced to exit.
The settings have not been changed from the preferences.(This is also happening on your computer/smartphone/ardroid tv)
 It does not occur on the kodi flex addon.
 
_Links removed by @croneter_

**Comment by croneter** [comment] 2021-03-22 08:43
I'm very sorry - but you shared your Plex token, unfortunately. Anyone can now access your Plex Media Server. Please **immediately** follow https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug#i-published-my-plex-token-to-some-forum-or-github-anyone-can-now-access-my-plex-server I will delete the links to your logs in your post above - the log files will remain, though!!

If I understand you correctly, Kodi starts playback. Then crashes to desktop. Correct?

**Comment by croneter** [comment] 2021-03-22 08:48
I see that you have `script.plex` installed as well. 

PlexKodiConnect tells Kodi which file to play just fine:
```
PLEX.playback_decision: The playurl for DirectPlay is: http://<IP>:32400/library/parts/198630/1615898626/file.mp4?Accept=%2A%2F%2A&Connection=keep-alive&Content-Type=application%2Fx-www-form-urlencoded&Accept-Language=ko&X-Plex-Device=Linux&X-Plex-Model=4.9.180&X-Plex-Device-Name=Kodi+192.168.0.27&X-Plex-Platform=Generic&X-Plex-Platform-Version=1.0.0&X-Plex-Product=PlexKodiConnect&X-Plex-Version=3.1.0&X-Plex-Client-Identifier=8ffbae19-12d6-4909-a27c-d304dbc36486&X-Plex-Provides=client%2Ccontroller%2Cplayer%2Cpubsub-player&X-Plex-Token=<TOKEN>
```
BUT then `script.plex` interferes:
```
script.plex: Player - STARTED
...
script.plex: Player: Seek OSD opened
```
Please remove `script.plex` from your Kodi!

**Comment by tjtnsgns** [comment] 2021-03-22 11:16
Even though you deleted script.plex, it is still being forced to exit.

**Comment by croneter** [comment] 2021-03-22 12:36
Please share another DEBUG log without `script.plex`

**Comment by tjtnsgns** [comment] 2021-03-22 13:02
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/6182319/kodi.log)
 Android log

**Comment by tjtnsgns** [comment] 2021-03-23 11:35
Someone told me to reset addon, so I reset it. But then when I turned on all the addons, the same thing happened, and one by one, they were colliding with the Metadata Editor addons during the inspection.

**Comment by croneter** [comment] 2021-04-05 13:30
What do you mean with "Metadata Editor addons during the inspection"?

Do you use the Kodi add-on [`Metadata Editor`](https://kodi.wiki/view/Add-on:Metadata_Editor)? If so: do NOT do that. PlexKodiConnect grads all the necessary data from Plex. No need to do anything on the Kodi side of things! The editor probably interferes with PKC, e.g. does not find files like it expects, thus deleting movie and tv show entries in your Kodi database.

**Comment by croneter** [comment] 2021-04-17 12:12
Closing as there is no feedback form @tjtnsgns and the issue is not caused by PlexKodiConnect

**Closed by croneter** 2021-04-17 12:12 UTC
