### ISSUE TITLE
Error with high bitrate files (SB off)

### ISSUE THREAD

**Issue by kZyro** [croneter/PlexKodiConnect#467] opened 2018-05-14 17:07 UTC
Hi there,

I am running a Pi 3B with latest LibreElec and PKC. For a few weeks Plex server is sitting in a remote place now.
First of all: great work! Never had a problem when running everything in the same network. Unfortunately I'm having some issues with some particular files with the server beeing in a remote location.
90 percent of the media is just playing without any problems. Some media just does not want to start (directPlay). In particular I think it's media with a high bitrate. 
Here you see a part of my (Error)log:

ERROR: Error on dvdnav_open
ERROR: CVideoPlayer::OpenInputStream - error opening []
ERROR: Playlist Player: skipping unplayable item: 0, path []

ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://XXX.XXX.XXX.XXX:32400/library/parts/70427/1516411909/file.mkv?X-Plex-Platform=Linux&amp;X-Plex-Client-Platform=Linux&amp;Connection=keep-alive&amp;X-Plex-Device-Name=PlexKodiConnect&amp;X-Plex-Provides=client,controller,player,pubsub-player&amp;X-Plex-Token=XXXXXXXXX-Plex-Client-Identifier=XXXXXXXXXXX&amp;Accept=*/*&amp;X-Plex-Device=PlexKodiConnect&amp;X-Plex-Product=PlexKodiConnect&amp;Content-Type=application/x-www-form-urlencoded&amp;X-Plex-Version=2.0.22

ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 400

And so on... 
Doesn't matter which version I am running. Tested on stable and beta.
Hope you have an idea.
Thanks a lot!

**Comment by croneter** [comment] 2018-05-14 18:14
This is probably caused by the Plex Streaming Brain: https://support.plex.tv/articles/227715247-server-settings-bandwidth-and-transcoding-limits/

PKC attempts to direct play. The streaming brain has limits below the bitrate of a video failing.

**Comment by croneter** [comment] 2018-05-19 06:06
Any news here?

**Comment by croneter** [comment] 2018-05-26 16:55
I guess your problem is solved and I'm closing the issue here. Do come back and reopen if this is not the case.

**Closed by croneter** 2018-05-26 16:55 UTC
