### ISSUE TITLE
FR - Library Selection at Sync

### ISSUE THREAD

**Issue by breezytm** [croneter/PlexKodiConnect#188] opened 2017-01-21 22:02 UTC
Is there a way, similar to "Music", users can be prompt to check with Libraries they wish to sync. Specifically for those of the same kind. Since I am the administrator of my plex server; I have a bunch of libraries that I do not wish to sync. I figured since you are pulling the libraries and correctly naming them under "Videos > Files", there must be a way to exclude Libraries.

**Comment by croneter** [comment] 2017-01-22 09:23
I can't stress enough that you can separate all your libraries of one kind using a skins video nodes. See https://github.com/croneter/PlexKodiConnect/wiki/Video-Nodes-and-Skins

Duplicate of #112

**Closed by croneter** 2017-01-22 09:23 UTC
