### ISSUE TITLE
Sync stuck on 99%

### ISSUE THREAD

**Issue by breezytm** [croneter/PlexKodiConnect#1045] opened 2019-11-05 21:01 UTC
Hi, 
Let me start by saying thank you for this great add-on. I am experiencing this issue where my sync is stuck on 99%. I believe the issue is related to a specific movie since it skims three all the other movies except that one. It is Brooklyn's Finest. Not sure if the "s is the problem. 

If you can not reproduce this and need some logs I can reset my database and try again. So far stopping Kodi and reopen it has allowed it to move on and successfully complete a partial sync

**Comment by croneter** [comment] 2019-11-06 05:04
I need debug log files: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

If possible, please also share the metadata of the movie in question by using Plex Web, navigating to the movie, then hit the three dots... at the top right, then Vie metadata or something like that, then view xml

**Comment by breezytm** [comment] 2019-11-07 14:19
I am out of the country and will be for about a week so logs will be a little hard to provide. However, please see the media info.

[25121.zip](https://github.com/croneter/PlexKodiConnect/files/3820057/25121.zip)

**Comment by croneter** [comment] 2019-11-07 17:23
Metadata looks good as far as I can tell. I do need the debug log...

**Comment by croneter** [comment] 2019-11-14 13:28
Still need a debug log showing the sync being stuck...

**Comment by croneter** [comment] 2019-11-24 08:33
Duplicate of #1063, see there for progress/more info

**Closed by croneter** 2019-11-24 08:33 UTC
