### ISSUE TITLE
Nvidia Shield TV 16GB (2017) - Cant play anything

### ISSUE THREAD

**Issue by rcocchiararo** [croneter/PlexKodiConnect#459] opened 2018-04-30 23:03 UTC
I recently heard of this and decided to give plex another try (i own a lifetime plexpass, but left plex alone for a long time, first for emby, later for kodi + mariadb).

This option would be great for me and some devices that lack kodi (ipad mainly).

My PMS is in an Nvidia shield tv (2017), and plex works fine. (its the 16gb model, so my media is on a synology ds116, and i have attached it on the shield's settings).

Kodi is unable to play any media from plex (although it syncs everything).

I tried native and addon modes.

Also tried adding the ip/username/password of my nas.

Is the shield tv with a NAS even supported? (i ask this because the media is added as /storage/path instead of network paths on PMS on the shield tv.

I tried the stable and beta versions of the addon.

Full debug log:
https://www.dropbox.com/s/xui86lqsgmisw3b/kodi.log?dl=0
Extract of many playback attempts (no debug enabled)
https://www.dropbox.com/s/2nwe2tmd2hjjn6b/non%20debug%20log.txt?dl=0

**Comment by croneter** [comment] 2018-05-01 05:40
PKC uses an empty video file to let playback fail in order to set-up its own playback. This empty video file failes for you
```
NOTICE: VideoPlayer: Opening: C:\Users\rcocc\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\empty_video.mp4
ERROR: DXVA::CProcessorHD::IsFormatSupported: Unsupported format 105 for 1.
```
Really wierd! I cannot reproduce this. Will try to make a new empty video file. Thanks for the log!

**Comment by croneter** [comment] 2018-05-02 17:58
No, that does not seem to be the problem. 

Please try the latest beta version again and be sure to completly reset PKC in its settings under `Advanced`, then `Reset the Kodi database...` (in red at the very end). Then hit YES and YES and let Kodi restart and resync. 

Kodi basically throws lots of errors like these:
```
ERROR: CCurlFile::Open failed with code 404 for https://192.168.88.229:32400/library/parts/5480/1523575704/file.mkv?X-Plex-Platform=Windows&X-Plex-Client-Platform=Windows&Connection=keep-alive&X-Plex-Device-Name=PlexKodiConnect&X-Plex-Provides=client%2Ccontroller%2Cplayer%2Cpubsub-player&X-REMOVED&Accept=%2A%2F%2A&X-Plex-Device=PlexKodiConnect&X-Plex-Product=PlexKodiConnect&Content-Type=application%2Fx-www-form-urlencoded&X-Plex-Version=2.0.21
ERROR: XFILE::CFileCache::Open - failed to open source <https://192.168.88.229:32400/library/parts/5480/1523575704/file.mkv?X-Plex-Platform=Windows&X-Plex-Client-Platform=Windows&Connection=keep-alive&X-Plex-Device-Name=PlexKodiConnect&X-Plex-Provides=client%2Ccontroller%2Cplayer%2Cpubsub-player&X-REMOVED&Accept=%2A%2F%2A&X-Plex-Device=PlexKodiConnect&X-Plex-Product=PlexKodiConnect&Content-Type=application%2Fx-www-form-urlencoded&X-Plex-Version=2.0.21>
ERROR: CVideoPlayer::OpenInputStream - error opening [https://192.168.88.229:32400/library/parts/5480/1523575704/file.mkv?X-Plex-Platform=Windows&X-Plex-Client-Platform=Windows&Connection=keep-alive&X-Plex-Device-Name=PlexKodiConnect&X-Plex-Provides=client%2Ccontroller%2Cplayer%2Cpubsub-player&X-REMOVED&Accept=%2A%2F%2A&X-Plex-Device=PlexKodiConnect&X-Plex-Product=PlexKodiConnect&Content-Type=application%2Fx-www-form-urlencoded&X-Plex-Version=2.0.21]
```
PKC did its job and passed an URL to Kodi. That's where it fails. 

Maybe try to force transcode by using the Plex context menu in Kodi?

**Comment by rcocchiararo** [comment] 2018-05-03 22:49
Still no dice.

https://www.dropbox.com/s/m4csiiu0pkfz6gr/kodiclean.log?dl=0

Thats the log, no debug enabled (forgot).

I had just formated my pc (went to a clean windows 10 1803 installation), so i made a clean windows store version of kodi and installed the newest beta as the first thing to try.

Are you sure this ADDON is compatible with the nvidia shield tv as the plex media server?

Maybe the way it handles its content is not compatible ? since the media is on a Synology NAS, but said NAS is attached to the Nvidia shield TV in the android settings app, and then plex sees it as a local storage (which has no network address).

Maybe i could somehow fool it using the NAS shared forlder path, but dunno how (using native instead of addon).

That, suposing that what i mention is the issue.

**Comment by croneter** [comment] 2018-05-04 05:40
First time I've seen this happening - seems like there's many others using Nvidia shield TV PMS. 
* Did you try to use force transcode? Please share the DEBUG log of you playing something using `Force transcode` from the Plex context menu in Kodi. 


Your PMS does not seem to find what you've just synced the Kodi:
````
Open failed with code 404 for https://192.168.88.229:32400/library/parts/5493/1524192090/file.mkv?X-Plex-Platform=Windows&X-Plex-Client-Platform=Windows&Connection=keep-alive&X-Plex-Device-Name=PlexKodiConnect&X-Plex-Provides=client%2Ccontroller%2Cplayer%2Cpubsub-player&X-replaced&Accept=%2A%2F%2A&X-Plex-Device=PlexKodiConnect&X-Plex-Product=PlexKodiConnect&Content-Type=application%2Fx-www-form-urlencoded&X-Plex-Version=2.0.22
```
Using Plex Web, navigate to your PMS. Open the movie/tv episode you tried to play for your last log file, then hit the three dots ... at the top right corner. Then `Show information`, then `Show xml`. A new window opens displaying the movie's XML. Please upload the XML content here.

**Comment by rcocchiararo** [comment] 2018-05-05 16:32
That log without debug included an attempt to play with force transcoding.

Here you have the xml and a log with debug and with force transcode.

[kodi.log](https://github.com/croneter/PlexKodiConnect/files/1976848/kodi.log)

[xml.txt](https://github.com/croneter/PlexKodiConnect/files/1976849/xml.txt)

Now, i might have noticed the true problem tho... last time i used plex it worked, now i cant play anything from my android or pc browser :P

**Comment by croneter** [comment] 2018-05-05 17:31
Let me close this issue then - because it has nothing to do with PlexKodiConnect...

**Closed by croneter** 2018-05-05 17:31 UTC
