### ISSUE TITLE
Can't re-play a video that has just been played

### ISSUE THREAD

**Issue by PadelzZ** [croneter/PlexKodiConnect#1358] opened 2021-02-23 07:11 UTC
Last night my Kodi got updated to the matrix build on my nvidia shield. I tried multiple things to get a movie or tv show episode to play but without succes. On my shield, i even started from scratch and installed PKC again.
I can start a media file but it will get stuck on loading the file, blue circle spinning around and nothing is happening.
This morning I wanted to check if in on my desktop it would work but i stumble on the same problem. I included logs from my desktop, I hope you can see and find what's going wrong.

https://pastebin.com/LtJmXZLk

**Comment by PadelzZ** [comment] 2021-02-24 10:07
On my desktop i was able to fix it by setting up using direct patch. But on my shield tv, it still does the same.
When using addon or direct paths, the moment i start playing a file. I keep getting the blue spinning wheel and nothing happens after that. I started from a completely fresh Kodi matrix installation

**Comment by croneter** [comment] 2021-02-24 11:38
You're using Direct Paths, not add on paths. See https://github.com/croneter/PlexKodiConnect/wiki/Direct-Paths-Explained

Apparently something changed due to the Kodi Matrix update so that Kodi (NOT pkc!) can't directly access your network shares anymore. 

Switch back to add on paths and reset the Kodi database in the pkc settings under Advanced. Or troubleshoot Kodi not being able to access your network share anymore.

There's nothing more I can do for you, sorry

**Comment by PadelzZ** [comment] 2021-02-24 11:52
When i use addon paths and start playing a file it will keep loading "Blue circle spinning"

**Comment by PadelzZ** [comment] 2021-02-24 12:11
> 2021-02-24 13:09:11.232 T:13378    INFO <general>: PLEX.playback_decision: PKC decided on playback method DirectPlay
2021-02-24 13:09:11.264 T:13378    INFO <general>: PLEX.playback_decision: Lets ask the PMS next
2021-02-24 13:09:11.265 T:13378    INFO <general>: PLEX.playback_decision: Asking PMS with maximal quality settings
2021-02-24 13:09:11.334 T:13378    INFO <general>: PLEX.playback_decision: PMS general decision None: None
2021-02-24 13:09:11.335 T:13378    INFO <general>: PLEX.playback_decision: PMS Direct Play decision None: None
2021-02-24 13:09:11.335 T:13378    INFO <general>: PLEX.playback_decision: PMS MDE decision 1000: Direct play OK.
2021-02-24 13:09:11.336 T:13378    INFO <general>: PLEX.playback_decision: PMS transcoding decision None: None
2021-02-24 13:09:11.338 T:13378    INFO <general>: PLEX.playback_decision: The playurl for DirectPlay is: https://192-168-0-208.bc2e55ab02f84b7a84b8b531b9c839bd.plex.direct:32400/library/parts/303061/1468776253/file.mp4?Accept=%2A%2F%2A&Connection=keep-alive&Content-Type=application%2Fx-www-form-urlencoded&Accept-Language=en&X-Plex-Device=Linux&X-Plex-Model=4.9.140-tegra-g7ad5124ecf88&X-Plex-Device-Name=Kodi+192.168.0.172&X-Plex-Platform=Generic&X-Plex-Platform-Version=1.0.0&X-Plex-Product=PlexKodiConnect&X-Plex-Version=3.0.11&X-Plex-Client-Identifier=416ec7dd-9921-4666-a599-99f5136e84bd&X-Plex-Provides=client%2Ccontroller%2Cplayer%2Cpubsub-player&X-Plex-Token=
2021-02-24 13:09:11.379 T:13378    INFO <general>: PLEX.api: Found external subs: []
2021-02-24 13:09:11.451 T:17054    INFO <general>: PLEX.MOVIES: PKC add-on for movies stopped
2021-02-24 13:09:11.451 T:17054    INFO <general>: CPythonInvoker(3, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect.movies/default.py): script successfully run
2021-02-24 13:09:11.468 T:13317    INFO <general>: VideoPlayer::OpenFile: plugin://plugin.video.plexkodiconnect.movies/?mode=play&plex_id=88578&plex_type=movie&filename=The Amazing Spider-Man 2-1080p-Blu-ray-H264-Man.mp4
2021-02-24 13:09:11.478 T:17076    INFO <general>: Creating InputStream
2021-02-24 13:09:11.607 T:17054 WARNING <general>: CPythonInvoker(3, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect.movies/default.py): the python script "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect.movies/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
2021-02-24 13:09:11.607 T:17054    INFO <general>: Python interpreter stopped

**Comment by croneter** [comment] 2021-02-24 12:39
Kindly share the entire debug log

**Comment by PadelzZ** [comment] 2021-02-24 15:36
[kodi.old.log](https://github.com/croneter/PlexKodiConnect/files/6037087/kodi.old.log)

**Comment by croneter** [comment] 2021-02-24 16:34
Looks like a Kodi bug, unfortunately:
```
PLEX.playback_decision: The playurl for DirectPlay is: https://192-168-0-208.bc2e55ab02f84b7a84b8b531b9c839bd.plex.direct:32400/library/parts/303061/1468776253/file.mp4?Accept=%2A%2F%2A&Connection=keep-alive&Content-Type=application%2Fx-www-form-urlencoded&Accept-Language=en&X-Plex-Device=Linux&X-Plex-Model=4.9.140-tegra-g7ad5124ecf88&X-Plex-Device-Name=Kodi+192.168.0.172&X-Plex-Platform=Generic&X-Plex-Platform-Version=1.0.0&X-Plex-Product=PlexKodiConnect&X-Plex-Version=3.0.11&X-Plex-Client-Identifier=416ec7dd-9921-4666-a599-99f5136e84bd&X-Plex-Provides=client%2Ccontroller%2Cplayer%2Cpubsub-player&X-Plex-Token=  
...
DEBUG <general>: ScanForExternalSubtitles: Searching for subtitles...
DEBUG <general>: CurlFile::Open(0x2ab95f90c8) https://192-168-0-208.bc2e55ab02f84b7a84b8b531b9c839bd.plex.direct:32400/library/parts/303061/1468776253/
DEBUG <general>: easy_acquire - Created session to https://192-168-0-208.bc2e55ab02f84b7a84b8b531b9c839bd.plex.direct
...
DEBUG <general>: ffmpeg[0x2a82e45180X]: [image2] Custom AVIOContext makes no sense and will be ignored with AVFMT_NOFILE format.
DEBUG <general>: ffmpeg[0x2a82e45180X]: [swscaler] No accelerated colorspace conversion found from yuv420p to bgra.
DEBUG <general>: ffmpeg[0x2a82e45180X]: [image2] Custom AVIOContext makes no sense and will be ignored with AVFMT_NOFILE format.
DEBUG <general>: ffmpeg[0x2a82e45180X]: [swscaler] No accelerated colorspace conversion found from yuv420p to bgra.
DEBUG <general>: ffmpeg[0x2a82e45180X]: [image2] Custom AVIOContext makes no sense and will be ignored with AVFMT_NOFILE format.
DEBUG <general>: ffmpeg[0x2a9e7b3e80X]: [image2] Custom AVIOContext makes no sense and will be ignored with AVFMT_NOFILE format.
DEBUG <general>: ffmpeg[0x2a82e45180X]: [swscaler] No accelerated colorspace conversion found from yuv420p to bgra.
DEBUG <general>: ffmpeg[0x2a82e45180X]: [image2] Custom AVIOContext makes no sense and will be ignored with AVFMT_NOFILE format.
DEBUG <general>: ffmpeg[0x2a9e7b3e80X]: [swscaler] No accelerated colorspace conversion found from yuv420p to bgra.
DEBUG <general>: ffmpeg[0x2a82e45180X]: [swscaler] No accelerated colorspace conversion found from yuv420p to bgra.
DEBUG <general>: ffmpeg[0x2a82e45180X]: [image2] Custom AVIOContext makes no sense and will be ignored with AVFMT_NOFILE format
...
```
The last block repeats and keeps repeating 😞 . This seems related to the module `ffmpeg`.

From the Plex/PlexKodiConnect side of things, everything seems to be working just fine. Kindly take this up with the Kodi team please.

**Comment by Drubei** [comment] 2021-02-24 17:14
I ran into this similar problem last week on my Shield.  It is a Kodi issue.  What I did was remove the network shared location in Kodi and then add them back again.  Set network credentials in PKC again, then repair database in PKC advanced settings.  This solved the problem for me.

**Comment by PadelzZ** [comment] 2021-02-24 17:42
> 
> 
> I ran into this similar problem last week on my Shield. It is a Kodi issue. What I did was remove the network shared location in Kodi and then add them back again. Set network credentials in PKC again, then repair database in PKC advanced settings. This solved the problem for me.

I'm not using a network shared location, i'm using native path (default) to play the files. Or am i missing something?

**Comment by croneter** [comment] 2021-02-24 17:51
> I'm not using a network shared location, i'm using native path (default) to play the files. Or am i missing something?

No, you're using add on paths

**Comment by PadelzZ** [comment] 2021-02-24 17:55
How come when i start the same media straight from a network source in video manager it plays straight and perfect normaly.
And when i use PKC to play the same file i have that infinite loop, does PKC force to use the FFMPEG?

**Comment by croneter** [comment] 2021-02-24 18:12
That's weird indeed! Did you try to force transcode?

**Comment by croneter** [comment] 2021-03-01 09:21
Any update here, @PadelzZ ?

**Comment by PadelzZ** [comment] 2021-03-01 14:07
i rolled back to Kodi 18.9 for now, in this version everything is working fine. Maybe in the future i wil try to update to the latest kodi

**Comment by Sada-Mio** [comment] 2021-03-06 10:39
Shield + fresh install kodi (matrix) + pkc matrix (stable) + addon path

Having same issue playing videos as @PadelzZ. Video either doesn't play spinning icon wheel or give error about playback fail

I'm also rolling back to Kodi 18.9

**Comment by croneter** [comment] 2021-03-06 11:34
Kindly share the log file you mentioned, otherwise I can't do a single thing 😞

**Comment by Sada-Mio** [comment] 2021-03-06 12:58
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/6095336/kodi.log)

First time opening video playback would take 5-10seconds to load. Spinning wheel. In Kodi-18.9 loading is instant.

If I stop/exit the video then it can't be re-opened. This error appears.

`Playback failed: One or more items failed to play. `

I can open a different video, but would get the error again trying to resume after exiting.

**Comment by Sada-Mio** [comment] 2021-03-25 01:34
Noticed this has been marked as "Kodi Issue". Curious what changed in Kodi 19 that is causing issues with pkc addon path playback?

**Comment by Sada-Mio** [comment] 2021-05-14 23:52
Appears PKC 3.1.4 Beta has fixed this issue. 

Video plays instantly withotu delay using default addon-path. Also resuming previously played video doesn't give error msg any more. Thanks CRONETER!

**Comment by Sada-Mio** [comment] 2021-07-07 10:08
Having same issue again.

` Playback failed: One or more items failed to play.`

Kodi 19.1 on Nvidia shield & also Win10.
PKC 3.3.0 & 3.3.1 beta

* Fresh installed Kodi 19.1, 
* installed pkc 
* direct stream open video
* close video
* open same video
* get playback failed error.

**Comment by eloo** [comment] 2021-08-13 18:16
Same issue on my side. 

System: RPI3b
PKC: 4.3.0
Addon mode

:(

**Comment by Sada-Mio** [comment] 2021-09-19 07:53
pkc 3.4.4 seems to have fixed this issue. What changed?

Working on PC desktop & Android ShieldTV. 

Video plays without wait time & able to playback more than once.

**Comment by croneter** [comment] 2021-09-19 11:52
Hah - nothing 😮. That's weird. Anyone still suffering of this issue?

**Comment by eloo** [comment] 2021-09-19 11:55
I can confirm thats also working for me now. 
But for me it was working since i have changed my system from OSCM to XBIAN with Kodi Matrix.

**Closed** 2021-09-19 11:56 UTC
Labels: Kodi issue, Kodi 19 Matrix

**Comment by Sada-Mio** [comment] 2021-09-19 20:50
> Hah - nothing 😮. That's weird. Anyone still suffering of this issue?

Very weird. Composite addon also working again too with zero changes.

Kodi 19.1 hasn't changed either so only difference is Plex Server or some other kodi addon updated? 

Guess I'll keep a 18.9 setup ready to revert if 19.1 mysteriously stops working again.
