### ISSUE TITLE
Language selection like in Plex (Web) App?

### ISSUE THREAD

**Issue by loeffelpan** [croneter/PlexKodiConnect#738] opened 2019-02-19 21:10 UTC
Is it possible to enhance PKC to play those language and subtitle like selected on plex server, regardless of kodis language settings?
Could only work with addon path, I think.

**Comment by croneter** [comment] 2019-02-20 06:30
Duplicate of https://github.com/croneter/PlexKodiConnect/issues/594

**Closed by croneter** 2019-02-20 06:30 UTC

**Comment by loeffelpan** [comment] 2019-02-20 08:03
Indeed related to #594 but not exactly an duplicate.
Here I'm talking about subtitle **and** audio.

Maybe you better close #594 and work on this here?

**Comment by croneter** [comment] 2019-02-20 08:13
True, Audio is a new feature request. Please open one here with all the other feature requests and vote for it http://feathub.com/croneter/PlexKodiConnect

**Comment by loeffelpan** [comment] 2019-02-21 16:00
Done.
https://feathub.com/croneter/PlexKodiConnect/+51
