### ISSUE TITLE
PKC ignores home users' access after updates

### ISSUE THREAD

**Issue by joswart** [croneter/PlexKodiConnect#824] opened 2019-04-09 20:13 UTC
As reported in the past (https://github.com/croneter/PlexKodiConnect/issues/723) I have a couple of users that are "home user" only; they don't have an individual login to plex, they are just generated on the "home user" tab in Plex.

These users have limited (kids) rights.

Since reporting it last time: after each major update of either PKC or Kodi (18.0 -> 18.1) all libraries are available to all home users, regardless of their settings in Plex. 

It seems like PKC is implementing the user rights itself and is not using the filtering that Plex normally executes as all Plex clients don't seem to have this problem.

After a fullscan has been executed, I am not able to reproduce the problem. But every new update triggers it again.

Using Librelec (latest), Kodi for Android and Kodi on Ubuntu, all with the same result.

**Comment by croneter** [comment] 2019-04-10 12:41
So can you reproduce this issue by installing an older PKC version, synching for a specific home user, then upgrading PKC?

That would extremely help since I haven't been able to reproduce this issue yet...

**Comment by joswart** [comment] 2019-04-17 07:20
Sorry, late reply, been swamped with work.

With me, just going into the PKC settings and starting "all over" (deleting the databases) will normally trigger a full scan of all content.

I might have found an easier way (less time consuming) to trigger the same effect: create a new library in plex and don't share it with anyone. On my systems this library will be accessible by all home users.

**Comment by croneter** [comment] 2019-04-17 14:13
I'm so sorry, but I cannot reproduce your issue! 

In Kodi, a Plex Managed Home User ("Töm Tester") is logged in. A create a new Plex library that is NOT shared with the user. It will never show up. 

Can you give me a detailed, foolprove step-by-step guide how I can reproduce your issue please? Screenshots might also help. 

![2019-04-17_160911](https://user-images.githubusercontent.com/4637940/56294363-2e501900-612b-11e9-9402-9952a6b6bd32.png)

**Comment by joswart** [comment] 2019-04-17 18:59
Hmmm... after reproducing it twice, it fails now on my system as well. *bangingheadagainstthewall*.

I am going to give up. I am turning off the home sharing options. With PKC the use is actually pretty limited. Naturally this will mean that I cannot no longer provide you with information, so you might as well close the issue.

Thanks for the ongoing support. Really appreciated!

**Comment by joswart** [comment] 2019-04-17 22:41
One last comment: my home user was a "real" home user, not an existing Plex user invited into home. Not sure if that could make a difference.

**Comment by croneter** [comment] 2019-06-05 06:47
I'm going to close this issue as I can't reproduce it unfortunately

**Closed by croneter** 2019-06-05 06:47 UTC
