### ISSUE TITLE
Broken if there's the same title, that's later replaced.

### ISSUE THREAD

**Issue by KyleSanderson** [croneter/PlexKodiConnect#1994] opened 2023-09-20 19:23 UTC
## Help yourself
* I did try to restart Kodi :-)
* I checked the [PKC Frequently Asked Questions on the PKC wiki](https://github.com/croneter/PlexKodiConnect/wiki/faq)
* I did try to reset the Kodi database by going to `PKC Settings -> Advanced -> "Reset the database and optionally reset PlexKodiConnect"` and then hitting YES, NO
* I did check the [existing issues on Github](https://github.com/croneter/PlexKodiConnect/issues)

## Describe the bug
Orphaned files are retained forever in Kodi, and all new library updates are ignored from Plex.

## To Reproduce
1. Sync the Kodi library with PKC.
2. Replace the file in Plex with a better quality one.
3. Play the library file in PKC, and receive an error because the file is gone.
4. Sync the Kodi library with PKC.
5. Play the library file in PKC, and see that PKC ignored the library update from Plex.
6. Start the File in Plex, which clearly plays no problem.
7. Go into Video Addons, go to "What's On Deck", and play the impossible file on Kodi, with the library still broken.

## Expected behavior
Playback of media.

I am aware that I can delete Plex tokens that I accidentially posted by following the [instructions on the PKC wiki](https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug#i-published-my-plex-token-to-some-forum-or-github-anyone-can-now-access-my-plex-server)

**Comment by StanislavAlexandrov** [comment] 2023-09-22 12:36
I am having the same issue. Currently, I resolve the issue by restarting Kodi each time it occurs. Also, I'm not entirely sure, but it appears that the issue resolves itself if enough time passes after the file upgrade.

**Comment by doomwithdon** [comment] 2023-09-25 02:43
This is a known issue. Can be fixed by running the Analyze option on the file. That updates the last update date for the file in plex and forces a sync with kodi

**Comment by KyleSanderson** [comment] 2023-09-25 03:14
Admittedly I don't use this anymore (flipped to mariadb, for now). Will keep it open for the rest, but I'm not going to be able to add any additional information at this time.

**Comment by croneter** [comment] 2024-01-20 16:55
This is a duplicate of https://github.com/croneter/PlexKodiConnect/issues/1893, thus closing this one. There is nothing I can do about that currently, as Plex simply does not tell that it got a new file and the old one is gone :-(. You need to reset the Kodi database in the PKC settings to get rid of this.

**Closed as completed by croneter** 2024-01-20 16:55 UTC
Labels: Plex issue

**Comment by croneter** [comment] 2024-01-20 16:57
> Also, I'm not entirely sure, but it appears that the issue resolves itself if enough time passes after the file upgrade.

@doomwithdon Yes with "enough time", Plex at some point updates the movie with e.g. new metadata. Plex tells about this (as opposed to a changed movie file :cry:), then PKC grabs the new data. Issue solved for now
