### ISSUE TITLE
Kodi shows wrong release year of some Movies. Different year as the year Plex is showing.

### ISSUE THREAD

**Issue by paponius** [croneter/PlexKodiConnect#1395] opened 2021-03-14 07:15 UTC
setup:
NAS: intel QNAP, Plex server version 1.20.1.3252 
client: multiple versions and platforms.

### On Plex Server side:
Plex scraps _year_ and sometimes also  _originallyAvailableAt_ dates from information provider service.
Plex shows date below movie title, e.g. here: **2013**:
![image](https://user-images.githubusercontent.com/14345371/111059267-8cf7ac00-8494-11eb-8293-2da097cc883f.png)

If **originallyAvailableAt** is not obtained, current date of when a movie was added is used as _Originally Available_,
e.g. here: **2020-06-30**
![image](https://user-images.githubusercontent.com/14345371/111059322-01324f80-8495-11eb-8230-a2886c7e78aa.png)

XML in Plex has these properties of `<Video>` element:
year="2013"
originallyAvailableAt="2020-06-30"

### On Kodi side:
**Expected behavior:**
Kodi should show year 2013 as the date of a Movie

**Actual behavior:**
Kodi shows 2020 as a Movie year

Note, that on Plex, the handling and relation of these two dates, (date and year) are non logical, though consistent.
If _Originally Available_ is edited in Plex interface:
![image](https://user-images.githubusercontent.com/14345371/111059566-e3fe8080-8496-11eb-8d5a-7017822373b2.png)
XML will show: originallyAvailableAt="2013-11-08"
_year_ will start following this date in Plex, _year_ and _originallyAvailableAt_ will become inter-locked.
If you edit _Originally Available_ to 2010, _year_ shown in Plex and in XML will also be 2010.

The problem is, Kodi seems to be showing year from _originallyAvailableAt_ and not _year_
Because of the aforementioned Note, the year shown in Kodi is sometimes identical with the Release year, but sometimes it's a year when this media was added and date from then set in _Originally Available_.

**Comment by croneter** [comment] 2021-03-14 11:38
The problem is that Kodi expects a specific date incl. month and day and not only the year (e.g. potentially for sorting - not only by year). A vanilla Kodi database looks like this:
![image](https://user-images.githubusercontent.com/4637940/111066898-acf19480-84c1-11eb-9a77-7d91726f41aa.png)
On the other hand, there is a specific metadata field for when the item was added to the Plex library, e.g. `addedAt="1570983995" `.  The fringe cases you're describing thus needs to be fixed on the Plex Media Server side, not the PKC side. `12 years a slave` is fine here, by the way:
```
originallyAvailableAt="2014-03-13"
addedAt="1570983995"
updatedAt="1604586767"
```
I won't "fix" this - this is an issue on the Plex media scanner side.

**Closed by croneter** 2021-03-14 11:38 UTC

**Comment by croneter** [comment] 2021-03-14 11:39
The "root cause", by the way, is that Plex does distinguish `year` and `originallyAvailableAt`. Kodi only knows `premiered`. The `year` is extracted from that date

**Comment by paponius** [comment] 2021-03-14 22:43
Thanks for your consideration. I imagine stuff at Plex themselves got lost in the meaning of _Originally Available (originallyAvailableAt)_. It's vague and as a such it's the root of this problem, a failure against the programmer's codex.
Available to download from web? Available from Plex? From a stream service? in cinemas? In your Plex library?
And _originally_? What other adjective would make sense with _available_?
The second error in Plex is that the _year_ which is used in a sense of a premiere date does not have month and day.

`premiered` as you mentioned Kodi is using is a label right to the point. A premiere date is a date everybody is using and expecting to see next to a movie title.

Since these Plex errors are consistent, I had in mind a solution where _year_ is compared to _originallyAvailableAt_, then maybe with conjunction with other data it would be decided if _originallyAvailableAt_ represents the premiere date, if not _year_ with e.g. 01-01 would be used. 

But in regard to sorting there are two situations this would misplace a Movie, possibly creating more confusion, so I understand your decision to pass on this.
