### ISSUE TITLE
Manual Changes to Collections Don't Sync

### ISSUE THREAD

**Issue by newoski** [croneter/PlexKodiConnect#2095] opened 2024-06-27 11:23 UTC
## Describe the bug
While manual changes to content, such as changing a movie poster on Plex, sync to Kodi, manual changes to Sets (such as adding a movie to an existing set or removing it) never sync unless I do a manual database reset

## To Reproduce
1. Add a few movies to a new, custom movie set
2. Try to get them to sync without doing a database reset

## Expected behavior
I would expect changes to movie sets to sync in the background etc, just like all other changes to content

**Comment by newoski** [comment] 2024-06-27 11:57
(I realize this is a different platform, but it's the same issue so maybe same root problem?)

https://emby.media/community/index.php?/topic/37458-collections-not-updating/

**Comment by croneter** [comment] 2024-06-27 12:31
This is a duplicate of https://github.com/croneter/PlexKodiConnect/issues/689. Unfortunately, there is **no way** of detecting you having changed a collection as Plex does not mark this as "this movie has been changed"

**Closed as completed by croneter** 2024-06-27 12:31 UTC

**Comment by newoski** [comment] 2024-06-27 12:35
Is there any way to automate/call the "repair database" function via cron/JSON etc?
