### ISSUE TITLE
In Kodi Krypton, PKC is not passing the movie year to Kodi

### ISSUE THREAD

**Issue by bartolomesoriano** [croneter/PlexKodiConnect#118] opened 2016-09-30 20:24 UTC
PKC does not pass the movie year to Kodi Krypton.  I am using PKC version 1.3.8 and Kodi Krypton Beta 3.  I reported a similar issue to the Emby for Kodi addon team (which PKC is based on), and they were able to fix it, so perhaps you can find out from them what the issue is.  Thanks.

**Comment by croneter** [comment] 2016-10-09 16:00
Duplicate of #79

**Closed by croneter** 2016-10-09 16:00 UTC
