### ISSUE TITLE
crashing with u'Title error

### ISSUE THREAD

**Issue by atilavat** [croneter/PlexKodiConnect#1129] opened 2020-02-24 06:42 UTC
Logs below

`020-02-23 22:37:53.246 T:9330  NOTICE: PLEX.default: plugin.video.plexkodiconnect started
2020-02-23 22:37:53.691 T:9330  NOTICE: PLEX.download: Request session does not exist: start one
2020-02-23 22:37:53.700 T:9330  NOTICE: PLEX.clientinfo: Unique device Id plex_client_Id loaded: c4c76b09-3aaf-4486-af8f-164456e8fadf
2020-02-23 22:37:55.100 T:9290  NOTICE: PLEX.artwork: ---===### Stopped ImageCachingThread ###===---
2020-02-23 22:37:55.483 T:9338  NOTICE: [plugin.video.youtube] Running: YouTube (6.6.0) on Leia (Kodi-18.5) with Python 2.7.15
                                            	Path: /kodion/search/query/
                                            	Params: {'q': 'india+news', 'search_type': 'video', 'event_type': 'live', 'reload': '2020022406371720200224063357'}
2020-02-23 22:38:00.061 T:9330  NOTICE: PLEX.default: plugin.video.plexkodiconnect stopped
2020-02-23 22:38:02.544 T:9406  NOTICE: [plugin.video.youtube] Running: YouTube (6.6.0) on Leia (Kodi-18.5) with Python 2.7.15
                                            	Path: /kodion/search/query/
                                            	Params: {'q': 'live, gujarati+news', 'search_type': 'video', 'event_type': 'live', 'reload': '2020022406371720200224063357'}
2020-02-23 22:38:05.796 T:9418  NOTICE: PLEX.default: plugin.video.plexkodiconnect started
2020-02-23 22:38:06.094 T:9418  NOTICE: PLEX.download: Request session does not exist: start one
2020-02-23 22:38:06.111 T:9418  NOTICE: PLEX.clientinfo: Unique device Id plex_client_Id loaded: c4c76b09-3aaf-4486-af8f-164456e8fadf
2020-02-23 22:38:06.824 T:9418   ERROR: PLEX.widget: xml that caused the crash: "Video": {u'grandparentTitle': u'NBC Bay Area News at 6', u'grandparentKey': u'/library/metadata/47899', u'parentTitle': u'Season 2020', u'addedAt': u'1582512545', u'year': u'2020', u'ratingKey': u'47903', u'parentIndex': u'2020', u'key': u'/library/metadata/47903', u'updatedAt': u'1582512548', u'duration': u'1331499', u'summary': u'Local news, sports and weather.', u'grandparentRatingKey': u'47899', u'grandparentThumb': u'/library/metadata/47899/thumb/1582426627', u'guid': u'plex://episode/5e437a842387a9003b02dc98', u'thumb': u'/library/metadata/47903/thumb/1582512548', u'skipParent': u'1', u'title': u'NBC Bay Area News at 6', u'originallyAvailableAt': u'2020-02-23', u'parentGuid': u'plex://season/5cffa6d41d6377001dc4c917/2020', u'grandparentGuid': u'plex://show/5cffa6d41d6377001dc4c917', u'type': u'episode'}
2020-02-23 22:38:09.054 T:9430  NOTICE: ResolveURL: Initializing ResolveURL version: 5.0.38
2020-02-23 22:38:09.397 T:9418   ERROR: PLEX.utils: Error encountered:  - u'title'
2020-02-23 22:38:09.603 T:9418   ERROR: PLEX.utils: _____________________________________________________________
2020-02-23 22:38:09.603 T:9418   ERROR: PLEX.utils:     Traceback (most recent call last):
2020-02-23 22:38:09.603 T:9418   ERROR: PLEX.utils:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/widgets.py", line 72, in generate_item
2020-02-23 22:38:09.603 T:9418   ERROR: PLEX.utils:         return _generate_content(api)
2020-02-23 22:38:09.603 T:9418   ERROR: PLEX.utils:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/widgets.py", line 212, in _generate_content
2020-02-23 22:38:09.603 T:9418   ERROR: PLEX.utils:         item['label'] = item['title']
2020-02-23 22:38:09.603 T:9418   ERROR: PLEX.utils:     KeyError: u'title'
2020-02-23 22:38:09.604 T:9418   ERROR: PLEX.utils: _____________________________________________________________
2020-02-23 22:38:09.611 T:9418   ERROR: PLEX.widget: xml that caused the crash: "Video": {u'grandparentTitle': u'KPIX 5 News at 6:00PM', u'grandparentKey': u'/library/metadata/47838', u'parentTitle': u'Season 2020', u'addedAt': u'1582515241', u'year': u'2020', u'ratingKey': u'47904', u'parentIndex': u'2020', u'key': u'/library/metadata/47904', u'updatedAt': u'1582515243', u'duration': u'2857579', u'summary': u'Local news, sports and weather.', u'grandparentRatingKey': u'47838', u'grandparentThumb': u'/library/metadata/47838/thumb/1581389101', u'guid': u'plex://episode/5e4377ed58bbe8003d3fa11d', u'thumb': u'/library/metadata/47904/thumb/1582515243', u'skipParent': u'1', u'title': u'KPIX 5 News at 6:00PM', u'originallyAvailableAt': u'2020-02-23', u'parentGuid': u'plex://season/5cffa6d4e56e71001efae109/2020', u'grandparentGuid': u'plex://show/5cffa6d4e56e71001efae109', u'type': u'episode'}
2020-02-23 22:38:09.627 T:9418   ERROR: PLEX.utils: Error encountered:  - u'title'
2020-02-23 22:38:10.647 T:9418   ERROR: PLEX.utils: _____________________________________________________________
2020-02-23 22:38:10.648 T:9418   ERROR: PLEX.utils:     Traceback (most recent call last):
2020-02-23 22:38:10.648 T:9418   ERROR: PLEX.utils:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/widgets.py", line 72, in generate_item
2020-02-23 22:38:10.648 T:9418   ERROR: PLEX.utils:         return _generate_content(api)
2020-02-23 22:38:10.648 T:9418   ERROR: PLEX.utils:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/widgets.py", line 212, in _generate_content
2020-02-23 22:38:10.648 T:9418   ERROR: PLEX.utils:         item['label'] = item['title']
2020-02-23 22:38:10.649 T:9418   ERROR: PLEX.utils:     KeyError: u'title'
2020-02-23 22:38:10.649 T:9418   ERROR: PLEX.utils: _____________________________________________________________
2020-02-23 22:38:12.542 T:8651  NOTICE: VideoInfoScanner: Starting scan ..
2020-02-23 22:38:12.665 T:8651  NOTICE: VideoInfoScanner: Finished scan. Scanning for video info took 00:00
2020-02-23 22:38:12.694 T:8581 WARNING: CGUIMediaWindow::OnMessage - updating in progress
2020-02-23 22:38:14.018 T:8651  NOTICE: My Music: Scanning for music info using worker thread, operation took 00:01
2020-02-23 22:38:14.050 T:8651 WARNING: Create - unsupported protocol(activatewindow(videos,"library) in activatewindow(videos,"library://video/Plex-2/",return)
2020-02-23 22:38:14.079 T:8581 WARNING: CGUIMediaWindow::OnMessage - updating in progress
2020-02-23 22:38:16.781 T:9418  NOTICE: PLEX.default: plugin.video.plexkodiconnect stopped
`

The file is a live TV recording from Plex. The file plays ok with no issues though.

**Comment by croneter** [comment] 2020-02-24 07:10
I need the entire DEBUG log, see here: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by atilavat** [comment] 2020-02-24 08:32
> I need the entire DEBUG log, see here: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

Here is the full debug log. Hopefully it helps.  FYI I can easily reproduce the issue.
https://privatebin.net/?bbb1be68050e1361#BNjPiuEP4riEF7NQ6B8iXC5U254B2Be1iyn2JPJNr8YY

**Comment by croneter** [comment] 2020-02-25 16:50
Hmm, PKC REALLY should not crash at that point. I've been unable to reproduce this issue. 

Try to reset the PKC database by going to the PKC settings, Advanced, then `Reset the Kodi database...`. Then Yes, Then No

If that does not work: Could you please share your `MyVideos116.db` file in the [Kodi userdata directory](https://kodi.wiki/view/Userdata), subfolder `Database`

**Comment by croneter** [comment] 2020-03-01 14:05
Any news, @atilavat ?

**Comment by atilavat** [comment] 2020-03-11 02:55
[MyVideos116.db.zip](https://github.com/croneter/PlexKodiConnect/files/4315804/MyVideos116.db.zip)
The reset of PKC database didnt helped. I added the MyVideos116.db file here. The affected shows with error do not show up in Kodi but are visibile and playable in Plex.

**Comment by croneter** [comment] 2020-03-11 05:34
Can you then please share the XML file of the respective videos? See herw: https://support.plex.tv/articles/201998867-investigate-media-information-and-formats/

**Comment by atilavat** [comment] 2020-03-11 06:07
Here you go:

`<?xml version="1.0" encoding="UTF-8"?>
<MediaContainer size="1" allowSync="1" identifier="com.plexapp.plugins.library" librarySectionID="2" librarySectionTitle="TV Shows" librarySectionUUID="45c8e722-e893-43e7-8a30-b25d8b330af3" mediaTagPrefix="/system/bundle/media/flags/" mediaTagVersion="1580813708">
<Video ratingKey="48154" key="/library/metadata/48154" skipParent="1" grandparentRatingKey="47838" guid="plex://episode/5e58907c6b0a88003d1861a8" parentGuid="plex://season/5cffa6d4e56e71001efae109/2020" grandparentGuid="plex://show/5cffa6d4e56e71001efae109" type="episode" title="KPIX 5 News at 6:00PM" grandparentKey="/library/metadata/47838" librarySectionTitle="TV Shows" librarySectionID="2" librarySectionKey="/library/sections/2" grandparentTitle="KPIX 5 News at 6:00PM" parentTitle="Season 2020" summary="Local news, sports and weather." parentIndex="2020" year="2020" thumb="/library/metadata/48154/thumb/1583891140" grandparentThumb="/library/metadata/47838/thumb/1581389101" duration="1265201" originallyAvailableAt="2020-03-10" addedAt="1583891135" updatedAt="1583891140">
<Media id="49350" duration="1265201" bitrate="10592" width="1920" height="1080" aspectRatio="1.78" audioChannels="6" audioCodec="ac3" videoCodec="h264" videoResolution="1080" container="mpegts" videoFrameRate="NTSC" channelIdentifier="5.1" mediaGrabBeginsAt="1583888400" mediaGrabDevice="device://tv.plex.grabbers.hdhomerun/1054FD5C" mediaGrabOriginalDuration="1917743" mediaGrabPostProcessed="1" mediaGrabStatus="complete" origin="dvr" videoProfile="high">
<Part accessible="1" exists="1" id="49559" key="/library/parts/49559/1583891133/file.ts" duration="1265201" file="/mounts/ubuntu3/TV Shows/KPIX 5 News at 6 00PM (2004)/Season 2020/KPIX 5 News at 6 00PM (2004) - 2020-03-10 18 00 00 - KPIX 5 News at 6 00PM.ts" size="1675084888" container="mpegts" packetLength="188" videoProfile="high">
<Stream id="36687" streamType="1" codec="h264" index="0" bitrate="10208" bitDepth="8" chromaLocation="left" chromaSubsampling="4:2:0" closedCaptions="1" codedHeight="1088" codedWidth="1920" frameRate="29.970" hasScalingMatrix="0" height="1080" level="40" profile="high" refFrames="2" scanType="interlaced" streamIdentifier="256" width="1920" displayTitle="1080i (H.264)" />
<Stream id="36689" streamType="2" selected="1" codec="ac3" index="1" channels="6" bitrate="384" language="English" languageCode="eng" audioChannelLayout="5.1(side)" samplingRate="48000" streamIdentifier="257" displayTitle="English (AC3 5.1)" />
<Stream id="36688" streamType="3" selected="1" codec="eia_608" index="0" embeddedInVideo="1" streamIdentifier="256" displayTitle="Unknown (Closed Captions)" />
</Part>
</Media>
<Genre id="25512" filter="genre=25512" tag="News" />
<Genre id="25513" filter="genre=25513" tag="Newscast" />
<Extras size="0">
</Extras>
</Video>
</MediaContainer>`

`<?xml version="1.0" encoding="UTF-8"?>
<MediaContainer size="1" allowSync="1" identifier="com.plexapp.plugins.library" librarySectionID="2" librarySectionTitle="TV Shows" librarySectionUUID="45c8e722-e893-43e7-8a30-b25d8b330af3" mediaTagPrefix="/system/bundle/media/flags/" mediaTagVersion="1580813708">
<Video ratingKey="48155" key="/library/metadata/48155" skipParent="1" grandparentRatingKey="47899" guid="plex://episode/5e58937885f2ec003faf9864" parentGuid="plex://season/5cffa6d41d6377001dc4c917/2020" grandparentGuid="plex://show/5cffa6d41d6377001dc4c917" type="episode" title="NBC Bay Area News at 6" grandparentKey="/library/metadata/47899" librarySectionTitle="TV Shows" librarySectionID="2" librarySectionKey="/library/sections/2" grandparentTitle="NBC Bay Area News at 6" parentTitle="Season 2020" summary="Local news, sports and weather." parentIndex="2020" viewCount="1" lastViewedAt="1583898690" year="2020" thumb="/library/metadata/48155/thumb/1583893789" grandparentThumb="/library/metadata/47899/thumb/1582426627" duration="2618167" originallyAvailableAt="2020-03-10" addedAt="1583893788" updatedAt="1583893789">
<Media id="49351" duration="2618167" bitrate="10158" width="1920" height="1080" aspectRatio="1.78" audioChannels="6" audioCodec="ac3" videoCodec="h264" videoResolution="1080" container="mpegts" videoFrameRate="NTSC" channelIdentifier="11.3" mediaGrabBeginsAt="1583888400" mediaGrabDevice="device://tv.plex.grabbers.hdhomerun/1054FD5C" mediaGrabOriginalDuration="3717728" mediaGrabPostProcessed="1" mediaGrabStatus="complete" origin="dvr" videoProfile="high">
<Part accessible="1" exists="1" id="49560" key="/library/parts/49560/1583893786/file.ts" duration="2618167" file="/mounts/ubuntu3/TV Shows/NBC Bay Area News at 6 (2004)/Season 2020/NBC Bay Area News at 6 (2004) - 2020-03-10 18 00 00 - NBC Bay Area News at 6.ts" size="3324363768" container="mpegts" packetLength="188" videoProfile="high">
<Stream id="36690" streamType="1" codec="h264" index="0" bitrate="9774" bitDepth="8" chromaLocation="left" chromaSubsampling="4:2:0" closedCaptions="1" codedHeight="1088" codedWidth="1920" colorRange="tv" frameRate="29.970" hasScalingMatrix="0" height="1080" level="40" profile="high" refFrames="2" scanType="interlaced" streamIdentifier="256" width="1920" displayTitle="1080i (H.264)" />
<Stream id="36692" streamType="2" selected="1" codec="ac3" index="1" channels="6" bitrate="384" language="English" languageCode="eng" audioChannelLayout="5.1(side)" samplingRate="48000" streamIdentifier="257" displayTitle="English (AC3 5.1)" />
<Stream id="36691" streamType="3" selected="1" codec="eia_608" index="0" embeddedInVideo="1" streamIdentifier="256" displayTitle="Unknown (Closed Captions)" />
</Part>
</Media>
<Genre id="25512" filter="genre=25512" tag="News" />
<Genre id="25513" filter="genre=25513" tag="Newscast" />
<Extras size="0">
</Extras>
</Video>
</MediaContainer>
`

**Comment by croneter** [comment] 2020-03-13 06:51
I just can't reproduce. Could you be so kind and share at least your TV shows with me, Plex user croneter?

**Comment by atilavat** [comment] 2020-03-13 07:02
> I just can't reproduce. Could you be so kind and share at least your TV shows with me, Plex user croneter?

Sure. Done.

**Comment by croneter** [comment] 2020-03-29 13:05
@atilavat 
By the way, I've been unable to access your PMS:
![image](https://user-images.githubusercontent.com/4637940/77849818-abef2680-71ce-11ea-8e95-a318e9314b1c.png)

**Comment by MrGeeDub** [comment] 2020-04-07 16:19
The U'Title' error is happening with me too. Started suddenly. I read somewhere that it may have to do with titles that have a colon ":"  I had just recently added The Hobbit movies to my library which contain colons in the titles, so it makes sense. However, the error only happens when I use a particular type of widget. Its the "On Deck" widget from my TV library. As soon as I try to add that widget the error pops up. I hope this helps.

**Comment by croneter** [comment] 2020-04-07 18:18
@MrGeeDub could you please share your Plex library with me (croneter)?

**Comment by MrGeeDub** [comment] 2020-04-07 18:33
Happy to help. I'm new to this. Could you tell me how to share my library with you, or point me in the right direction?

**Comment by croneter** [comment] 2020-04-07 19:00
@MrGeeDub https://www.simplehelp.net/2018/01/31/how-to-share-your-plex-library-with-friends/

**Comment by croneter** [comment] 2020-04-07 19:01
Worked, thanks a lot!

**Comment by MrGeeDub** [comment] 2020-04-07 19:06
Done, I think

**Comment by MrGeeDub** [comment] 2020-04-07 20:04
Also, if this helps, I've been having trouble resuming any content. For example, if I try to play a movie or show where I left off, Kodi just stalls. I get the spinner and nothing plays. If I back out at play from the beginning, all is good. I don't know if this issue is related to this topic, but I thought it best to mention it

**Comment by atilavat** [comment] 2020-04-07 21:36
> @atilavat
> By the way, I've been unable to access your PMS:
> ![image](https://user-images.githubusercontent.com/4637940/77849818-abef2680-71ce-11ea-8e95-a318e9314b1c.png)

My library should be working now too. Please check. Thanks.

**Comment by croneter** [comment] 2020-04-08 05:09
> Also, if this helps, I've been having trouble resuming any content. For example, if I try to play a movie or show where I left off, Kodi just stalls. I get the spinner and nothing plays. If I back out at play from the beginning, all is good. I don't know if this issue is related to this topic, but I thought it best to mention it

No, not related. Please open a new issue and share your DEBUG log file according to https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by MrGeeDub** [comment] 2020-04-12 17:51
Have you been able to diagnose anything from my library?

**Comment by croneter** [comment] 2020-04-12 18:25
Not yet

**Comment by BrutuZ** [comment] 2020-06-02 23:26
I have this happen when mix and matching local metadata refreshed by Kodi (fine-tuned nfo files and extended artwork) with PKC.
Sometimes even the "big red button" (Reset Kodi database) isn't enough and I end up just deleting the DB files manually to start fresh.

**Comment by croneter** [comment] 2020-06-09 09:39
@atilavat I still can't connect to your PMS, sorry 😢 . 

I need access to a PMS where this bug occurs in order to fix it. Can anyone here share their respective library with me, `Croneter`?

**Comment by croneter** [comment] 2020-06-09 09:40
@BrutuZ 
You should NOT do a "Mix and match", using PKC/Plex as well as additional videos directly in Kodi. You'll always have issues; PKC is simply not made for that use case, sorry...

**Comment by BrutuZ** [comment] 2020-06-09 17:16
> 
> 
> @BrutuZ
> You should NOT do a "Mix and match", using PKC/Plex as well as additional videos directly in Kodi. You'll always have issues; PKC is simply not made for that use case, sorry...

Well aware, I did RTFM and you made it pretty clear there 😉

I'm sometimes experimenting with alternatives to using Plex since it became too much bloated and off-course (too focused on DVR and partnership content providers, not even a responsive Web-UI, and so on) for my "single user, single device" use case, which basically comes down to just fetch metadata and run [Sub-Zero](https://github.com/pannal/Sub-Zero.bundle).

As such, I encountered this error\warning a few times after giving up on an experiment and re-enabling PKC before properly cleaning up the databases or doing so in order to have it do the purge with its _big red button_.

Also had it happen just by going for the native "refresh metadata" option in Kodi naively thinking it would call for a Plex and PKC refresh for the item.

**Comment by BrutuZ** [comment] 2020-10-16 22:22
Fun fact: This suddenly started happening again in recent days, and I'm in a purely Plex based library for quite some time now so there goes my "mix-n-match" theory.

**Comment by simonk83** [comment] 2020-12-05 07:36
I'm also having this problem. As someone else mentioned, disabling widgets for my TV library seems to "fix" this, but not ideal obviously.

**Comment by croneter** [comment] 2021-01-02 12:27
Hopefully fixed with PKC version 2.12.6

**Closed by croneter** 2021-01-02 12:27 UTC
