### ISSUE TITLE
PlexKodiConnect hang kodi when playing a recorded video from vdr

### ISSUE THREAD

**Issue by Gilles76** [croneter/PlexKodiConnect#99] opened 2016-09-06 11:49 UTC
Hi,

It's been a long time I search a clue about some kodi's hang.
 I finally found what happened.

When I want to plays a video recorded from vdr plugin, Kodi hang, no more control is possible.

Here it is what plexKodiConnect tell me.

` NOTICE: DVDPlayer: Opening: pvr://recordings/active/Flash, TV (TF1), 20160905_221000.pvr
13:42:14 3516906.500000 T:1944092672 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
13:42:14 3516906.500000 T:1235219376  NOTICE: Creating InputStream
13:42:14 3516906.750000 T:1235219376  NOTICE: Creating Demuxer
13:42:17 3516909.250000 T:1235219376  NOTICE: Opening stream: 0 source: 256
13:42:17 3516909.250000 T:1235219376  NOTICE: Creating video thread
13:42:17 3516909.250000 T:1235219376  NOTICE: Opening stream: 1 source: 256
13:42:17 3516909.250000 T:1235219376  NOTICE: Creating audio thread
13:42:17 3516909.250000 T:1235219376  NOTICE: Opening stream: 5 source: 256
13:42:17 3516909.500000 T:1235219376  NOTICE: Opening stream: 0 source: 256
13:42:17 3516909.750000 T:1235219376  NOTICE: OMXClock using audio as reference
13:42:17 3516909.750000 T:1314907056  NOTICE: Display resolution DESKTOP : 1920x1080 (1920x1080) @ 60.00 - Full Screen (16)
13:42:18 3516911.000000 T:1820337072   ERROR: PlexKodiConnect Player -> Could not find itemId, cancelling playback report!
`
Do you think you could do someting ?
Do you need more informations, if yes don't hesitate.

Kind Regards,

Gilles.

**Comment by croneter** [comment] 2016-09-06 12:02
Yes, I need you to enable debug logging in both Kodi and the PlexKodiConnect Settings, please follow https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

Then please post your entire log here (with your Plex tokens removed), thanks.

**Comment by Gilles76** [comment] 2016-09-06 13:32
Hi,

Sorry but the xbmc log site is deadand pastebin don't acceept more than 512 ko.
so here is the log file.
I'm on a raspberry pi 2 wither raspbian 8 jessie and kodi 16.1 (jarvis).
I'm using vdr vnsi 1.5 protocol 9.

[kodi.txt](https://github.com/croneter/PlexKodiConnect/files/456790/kodi.txt)

When I play a new tv record (tv then menu recordings, then the record here it's flash) Kodi freeze but is not dead, it continue to log temp. If I restart kodi, and play again the tv record, Kodi d'on't freeze.

After trying to play a tv record in kodi.log, I see an error of ID from plexkodiconnect.

The most interesting in kodi.txt is nere 14:46.

Tell me if it's ok, or ask me some more things.

Tank you.
Gilles

**Comment by Gilles76** [comment] 2016-09-06 14:00
Just for your information, I disable PlexKodiConnect and I have the same issue.
So if I'm not wrong There is effectively an error throw by plexkodiconnect but it's not it.

Are you agree ?

**Comment by croneter** [comment] 2016-09-06 14:02
Thanks for the log. It does not look like PKC making Kodi unresponsive (it should not do that by design, anyway ;-)). Could you please try and install the PKC beta repository from [here](https://github.com/croneter/PlexKodiConnect) and try again (with debug logging) with PKC version 1.3.1?

The PKC error message you mentioned is "normal" and should not lead to PKC/Kodi crashing
```
13:42:18 3516911.000000 T:1820337072 ERROR: PlexKodiConnect Player -> Could not find itemId, cancelling playback report!
```

**Comment by croneter** [comment] 2016-09-06 14:03
Ahhh, if you disabled or even uninstalled PKC and you STILL get the same error/behavior, then it's not PKC :-D....

Closing the issue ;-)

**Closed by croneter** 2016-09-06 14:03 UTC
