### ISSUE TITLE
episode / movie sometimes marked incorrectly as fully watched

### ISSUE THREAD

**Issue by RickDB** [croneter/PlexKodiConnect#279] opened 2017-04-18 09:58 UTC
Noticed that now and again it will mark a movie or episode as fully watched even though it was only partially watched (well below the 90% threshold).

Trying to get some fresh logs as so far it seems random and mostly happening when a sync is already running while playing but not sure yet.
2 scenario's I'm trying now to reproduce it with Kodi 17:

**During playback**

- Start playing a episode you never played before (0 playcounts)
- Let PKC run a full sync
- Stop playback (tested at 10%)
- Will notice Kodi has marked it as partially played.
- Now navigate back to TV show overview
- PKC will report full sync finished, check to see if episode is marked as full watched (playcount > 0)

**Sync after restart with short playbacks**

- Start Kodi
- Start playing a episode you never played before (0 playcounts)
- Close Kodi right after
- Let PKC run sync
- Might notice the episode you just played has become fully watched

Wondering if anyone else noticed this behavior before as so far I've had this several times over various episodes and movies which suddenly became fully watched, have no other addon controlling these states (like Trakt) so must either be PKC or Kodi bug.
PKC is using direct paths with UNC paths with option set to translate them back with credentials, other than that nothing fancy.
Once I get some fresh logs with debug enabled will update post.

**Comment by croneter** [comment] 2017-04-18 10:42
This is at least partially Kodi's fault. If you start a video and pretty much immediately cancel the playback, Kodi reports the playstate back differently (I think it was in seconds instead of minutes, or something similar).

Will have another look once your logs are in ;-)

**Comment by RickDB** [comment] 2017-04-18 10:56
Also had it with Top Gear recently, played for about 20 minutes or so and after sync was marked as fully watched.
Odd thing is that in Kodi directly after playback it marks it as partially watched and only after sync it would get the fully marked indicator, maybe PKC can compare total video length vs last reported state as that might workaround the different formats (minutes vs seconds)?

Seems pretty random so far but have debug on now with that annoying top stat counter so will post once it happens again :)

**Comment by RickDB** [comment] 2017-04-19 17:50
Managed to finally reproduce the error it with Elementary where I watched  S05E18 and stopped it at 20% and shortly after it marked S05E19 as watched even though that had playcount 0 according to logs.

Since the logs contains a lot of sensitive info (token / machine id) what's the preferred way of sending or scrubbing it?

**Comment by croneter** [comment] 2017-04-19 18:07
I'd only consider the Plex token as sensitive, not the machine id, etc. But this also depends on your other Kodi addons. 

My suggestion: search & replace your `x-plex-token` then upload the log here. If you don't want to do that, you could send me a PM on the Plex forums. Up to you ;-).

**Comment by RickDB** [comment] 2017-04-19 19:06
PM sent :)

**Comment by croneter** [comment] 2017-05-10 05:52
I'm closing this as I can't reproduce this issue. 

Please reopen if you have logs showing what is happening...

**Comment by RickDB** [comment] 2017-05-10 09:18
Can upload fresher logs however since it's random reproducing is not easy.
Did notice that with managed users if you quit Kodi shortly after playback it will not save play states most of the time or report them as fully watched.
If it happens to more people can always re-open but how it works now is fine most of the time :)

**Comment by croneter** [comment] 2017-05-10 09:46
"Sync running while Kodi updates its play states" shouldn't actually be possible - e.g. if you start a playback, all sync activities are immediately cancelled. 

Looking forward to your logs 😉

**Comment by RickDB** [comment] 2017-05-10 10:26
It does sync something during playback as in Kodi noticed a view updating with either watched or partial label, was with the one from Elementary from the first log set as well but that didn't have PKC debug enabled yet sadly.
If I get it again will post logs :)

**Comment by RickDB** [comment] 2017-07-16 18:49
Found something interesting in the Kodi logs, it seems that sometimes playcount is empty and the current check would mark it as watched if not 0 so updated that here:

https://github.com/RickDB/PlexKodiConnect/commit/755e7a3179e5d2d9c540f8c96f09c015eee606cc

Tested that for a few days already and so far no more issues :)
Another change is in the library sync where there's seconds / milliseconds check:

https://github.com/croneter/PlexKodiConnect/blob/9c79a6ddca06becf415b4e8b340cffda10d12042/resources/lib/librarysync.py#L1349

since Kodi can sometimes do the same trickery (milliseconds <--> seconds) added some basis validation but need to test that a bit more first as not sure how to fix that properly (need verified data from both ends).

**Comment by croneter** [comment] 2017-07-16 19:40
Nice! Go for it

**Closed** 2017-09-01 18:32 UTC
