### ISSUE TITLE
Playback start takes AGES

### ISSUE THREAD

**Issue by iz3man** [croneter/PlexKodiConnect#1221] opened 2020-09-27 19:52 UTC
## Help yourself
* I did try to restart Kodi :-) - SURE i did
* I checked the [PKC Frequently Asked Questions on the PKC wiki](https://github.com/croneter/PlexKodiConnect/wiki/faq) YES
* I did try to reset the Kodi database YES (and it seems to help for the first one, two playbacks - sometimes)
## Describe the bug
Starting a show or movie takes AGES. Literally about 20-30s. Data resides on the Plex server with a reasonably fast cpu/memory, on an ZFS pool of 4x 3TB SAS drives.

## To Reproduce
start playback ... and wait 

## Expected behavior
Instant replay as always. I can't say when this first appeared, but it happens on both of my libreelec clients. 

## You need to attach a KODI LOG FILE!
https://pastebin.com/QiuiSYHr

**Comment by croneter** [comment] 2020-09-28 16:46
You seem to have some network issues.  
```
2020-09-27 19:33:10.375 T:139924523181824   ERROR: AddOnLog: Tvheadend HTSP Client: pvr.hts - unable to connect to 192.168.1.100:9982
2020-09-27 19:33:10.383 T:139924648974080   ERROR: CCurlFile::FillBuffer - Failed: Couldn't resolve host name(6)
2020-09-27 19:33:10.383 T:139924648974080   ERROR: CCurlFile::Open failed with code 0 for https://raw.githubusercontent.com/kodi-game/repository.kodi.game/master/release/addons.xml.md5:
2020-09-27 19:33:10.383 T:139924648974080   ERROR: Open - failed to open source <https://raw.githubusercontent.com/kodi-game/repository.kodi.game/master/release/addons.xml.md5>
2020-09-27 19:33:10.383 T:139924648974080   ERROR: CRepository: failed read 'https://raw.githubusercontent.com/kodi-game/repository.kodi.game/master/release/addons.xml.md5'
2020-09-27 19:33:10.397 T:139924648974080   ERROR: CCurlFile::FillBuffer - Failed: Couldn't resolve host name(6)
2020-09-27 19:33:10.397 T:139924648974080   ERROR: CCurlFile::Open failed with code 0 for http://mirrors.kodi.tv/addons/leia/addons.xml.gz?sha256:
2020-09-27 19:33:10.398 T:139924648974080   ERROR: Open - failed to open source <http://mirrors.kodi.tv/addons/leia/addons.xml.gz?sha256>
2020-09-27 19:33:10.398 T:139924648974080   ERROR: CRepository: failed read 'http://mirrors.kodi.tv/addons/leia/addons.xml.gz?sha256'
2020-09-27 19:33:10.406 T:139925521520384   ERROR: CCurlFile::FillBuffer - Failed: Couldn't resolve host name(6)
2020-09-27 19:33:10.406 T:139925521520384   ERROR: CCurlFile::Open failed with code 0 for https://addons.libreelec.tv/9.2.0/Generic/x86_64/addons.xml.gz.sha256:
2020-09-27 19:33:10.406 T:139925521520384   ERROR: Open - failed to open source <https://addons.libreelec.tv/9.2.0/Generic/x86_64/addons.xml.gz.sha256>
2020-09-27 19:33:10.406 T:139925521520384   ERROR: CRepository: failed read 'https://addons.libreelec.tv/9.2.0/Generic/x86_64/addons.xml.gz.sha256'
2020-09-27 19:33:10.416 T:139924648974080   ERROR: CCurlFile::FillBuffer - Failed: Couldn't resolve host name(6)
2020-09-27 19:33:10.416 T:139924648974080   ERROR: CCurlFile::Open failed with code 0 for https://raw.githubusercontent.com/louisbraun/repoaddons/master/addons.xml.md5:
2020-09-27 19:33:10.416 T:139924648974080   ERROR: Open - failed to open source <https://raw.githubusercontent.com/louisbraun/repoaddons/master/addons.xml.md5>
2020-09-27 19:33:10.416 T:139924648974080   ERROR: CRepository: failed read 'https://raw.githubusercontent.com/louisbraun/repoaddons/master/addons.xml.md5'
2020-09-27 19:33:10.511 T:139924934227712   ERROR: CCurlFile::FillBuffer - Failed: Couldn't resolve host name(6)
2020-09-27 19:33:10.511 T:139924934227712   ERROR: CCurlFile::Open failed with code 0 for https://raw.githubusercontent.com/croneter/binary_repo/master/stable/addons.xml.md5:
2020-09-27 19:33:10.511 T:139924934227712   ERROR: Open - failed to open source <https://raw.githubusercontent.com/croneter/binary_repo/master/stable/addons.xml.md5>
2020-09-27 19:33:10.511 T:139924934227712   ERROR: CRepository: failed read 'https://raw.githubusercontent.com/croneter/binary_repo/master/stable/addons.xml.md5'
2020-09-27 19:33:10.881 T:139924523181824   ERROR: AddOnLog: Tvheadend HTSP Client: pvr.hts - unable to connect to 192.168.1.100:9982
2020-09-27 19:33:13.459 T:139924889896704   ERROR: Previous line repeats 4 times.
```

```
2020-09-27 19:57:54.129 T:139925679996544  NOTICE: Samba is idle. Closing the remaining connections
2020-09-27 19:58:06.394 T:139925679996544  NOTICE: NFS is idle. Closing the remaining connections.
2020-09-27 20:00:54.749 T:139923934398208  NOTICE: COutput::OnStartup: Output Thread created
2020-09-27 20:00:54.921 T:139925679996544  NOTICE: VAAPI::Close
2020-09-27 20:00:54.921 T:139923998422784  NOTICE: COutput::OnExit: Output Thread terminated
2020-09-27 20:09:49.910 T:139923998422784  NOTICE: COutput::OnStartup: Output Thread created
2020-09-27 20:09:50.119 T:139925679996544  NOTICE: VAAPI::Close
2020-09-27 20:09:50.119 T:139923934398208  NOTICE: COutput::OnExit: Output Thread terminated
2020-09-27 20:30:36.443 T:139924934227712  NOTICE: COutput::OnStartup: Output Thread created
2020-09-27 20:30:36.582 T:139925679996544  NOTICE: VAAPI::Close
2020-09-27 20:30:36.582 T:139923998422784  NOTICE: COutput::OnExit: Output Thread terminated
2020-09-27 20:30:37.102 T:139923905042176 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
2020-09-27 20:30:52.673 T:139923998422784  NOTICE: COutput::OnStartup: Output Thread created
2020-09-27 20:30:52.772 T:139925679996544  NOTICE: VAAPI::Close
2020-09-27 20:30:52.773 T:139924934227712  NOTICE: COutput::OnExit: Output Thread terminated
2020-09-27 20:30:53.315 T:139924934227712  NOTICE: COutput::OnStartup: Output Thread created
2020-09-27 20:30:53.389 T:139925679996544  NOTICE: VAAPI::Close
2020-09-27 20:30:53.389 T:139923998422784  NOTICE: COutput::OnExit: Output Thread terminated
2020-09-27 20:31:37.779 T:139924133697280  NOTICE: COutput::OnStartup: Output Thread created
2020-09-27 20:31:37.991 T:139925679996544  NOTICE: VAAPI::Close
2020-09-27 20:31:37.991 T:139924934227712  NOTICE: COutput::OnExit: Output Thread terminated
2020-09-27 20:31:58.611 T:139924934227712  NOTICE: COutput::OnStartup: Output Thread created
2020-09-27 20:31:58.690 T:139925679996544  NOTICE: VAAPI::Close
2020-09-27 20:31:58.690 T:139924133697280  NOTICE: COutput::OnExit: Output Thread terminated
2020-09-27 20:32:19.173 T:139923934398208  NOTICE: COutput::OnStartup: Output Thread created
2020-09-27 20:32:19.336 T:139925679996544  NOTICE: VAAPI::Close
2020-09-27 20:32:19.338 T:139924934227712  NOTICE: COutput::OnExit: Output Thread terminated
2020-09-27 20:32:36.062 T:139924934227712  NOTICE: COutput::OnStartup: Output Thread created
2020-09-27 20:32:36.223 T:139925679996544  NOTICE: VAAPI::Close
2020-09-27 20:32:36.223 T:139923934398208  NOTICE: COutput::OnExit: Output Thread terminated
2020-09-27 20:32:42.615 T:139924133697280  NOTICE: COutput::OnStartup: Output Thread created
2020-09-27 20:32:42.761 T:139925679996544  NOTICE: VAAPI::Close
2020-09-27 20:32:42.762 T:139924934227712  NOTICE: COutput::OnExit: Output Thread terminated
2020-09-27 20:32:48.111 T:139923934398208  NOTICE: COutput::OnStartup: Output Thread created
2020-09-27 20:32:48.244 T:139925679996544  NOTICE: VAAPI::Close
2020-09-27 20:32:48.244 T:139924133697280  NOTICE: COutput::OnExit: Output Thread terminated
2020-09-27 20:33:47.707 T:139925679996544  NOTICE: CVideoPlayer::CloseFile()
```
Also, these 2 entries should follow each other instanteneously, and not take 6 seconds:
```
2020-09-27 19:55:06.824 T:139923998422784  NOTICE: PLEX.TVSHOWS: PKC add-on for tv shows started
2020-09-27 19:55:12.086 T:139923998422784  NOTICE: PLEX.TVSHOWS: PKC add-on for tv shows stopped
```
So:
* Do you suffer of high CPU loads?
* Did you try to reset PKC by going to the PKC settings, Advanced, Reset the Kodi DB, then hitting YES, NO?

**Comment by iz3man** [comment] 2020-09-28 17:08
High CPU loads? Not really. During TV playback (1080p content) it's 50%. There are spikes during initial media scan though.
Yes, I reset DB several times. It's a bit better afterwards sometimes, but still takes WAY longer than it was "before". 
DNS issues is a got question. Not any that I'm aware of.

**Comment by iz3man** [comment] 2020-09-28 18:00
The issue is REALLY strange. I now removed the plugin and reinstalled it. Now some items start almost instantly, and some need some time. I can't really reproduce it.

**Comment by croneter** [comment] 2020-09-28 20:21
Can you please share another debug log with playback working normally as well as abnormally?

**Comment by iz3man** [comment] 2020-09-29 18:28
I wish I could. I really can't replicate a "good" and a "bad" start. I will try. Thanks so far!!

**Comment by iz3man** [comment] 2020-09-29 18:38
Ha. I was lucky. Played around a little bit, and now I got a good one, with almost instant playback (perfect). I stopped it immediately after playback, copied the log, and started the VERY SAME ITEM only ONE MINUTE later. Took way over 30s to start.

Good one: https://pastebin.com/QiRZswZT
Bad one: https://pastebin.com/3pjR25jc

**Comment by croneter** [comment] 2020-10-01 14:15
The "bad one" is interesting:
```
2020-09-29 20:34:00.496 T:139855075501824  NOTICE: PLEX.playback_decision: PKC decided on playback method DirectPlay
2020-09-29 20:34:00.496 T:139855075501824   DEBUG: PLEX.playback_decision: Telling PMS we are not burning in any subtitles
...
5 seconds
...
2020-09-29 20:34:05.546 T:139855075501824  NOTICE: PLEX.playback_decision: Lets ask the PMS next
```
PKC needs to tell the PMS what subtitle and audio streams to use before playback. Or not to use. Telling the PMS to NOT burn in any subtitles should only take the PMS a fraction of a second to react. But it takes around 5 seconds.

Could you kindly enable PMS debug logging, share another Kodi debug log when playback start takes forever and then also share the PMS log file?

**Comment by croneter** [comment] 2020-10-01 14:19
It really seems like your PMS has a serious hickup - maybe specifically for that item that won't play quickly.

**Comment by iz3man** [comment] 2020-10-01 14:19
> enable PMS debug logging

This means: https://geekdrop.com/content/how-to-enable-or-disable-logging-in-plex-media-server-pms
Is that what you need?

Thanks!!

**Comment by croneter** [comment] 2020-10-01 17:39
Yes, verbose or the level right next to that one...

It's definitely not a PlexKodiConnect issue then

**Comment by croneter** [comment] 2020-10-02 05:49
Closing as this issue is caused by the PMS, not PKC

**Closed by croneter** 2020-10-02 05:49 UTC

**Comment by iz3man** [comment] 2020-10-05 18:00
I know you closed this thread, and I will open a PMS case, but first I'd ask you to check this log, before I make a new case @PMS and get pushed back to PKC ;)

https://pastebin.com/9cts4NX3

**Comment by iz3man** [comment] 2020-10-06 18:29
BTW: When I start the exact same files directly from the NFS share they open instantly, no issues with ff/rew and jumping is fine as well.

**Comment by croneter** [comment] 2020-10-07 15:47
I'm not seeing much in that log, seems to be only an excerpt. But the error messages at the beginning do not bode well...
```
Oct 05, 2020 19:49:51.783 [0x7f586b897700] DEBUG - NetworkServiceBrowser: SSDP departed after not being seen for 21.352754 seconds: 192.168.1.8 (Denon AVR-X1300W)
Oct 05, 2020 19:49:53.285 [0x7f5842ffd700] DEBUG - NetworkServiceBrowser: Parsing SSDP schema for http://192.168.1.8:8080/description.xml
Oct 05, 2020 19:49:53.285 [0x7f5842ffd700] DEBUG - HTTP requesting GET http://192.168.1.8:8080/description.xml
Oct 05, 2020 19:49:53.311 [0x7f5842ffd700] DEBUG - HTTP 200 response from GET http://192.168.1.8:8080/description.xml
Oct 05, 2020 19:49:53.311 [0x7f5842ffd700] ERROR - XML: namespace
Oct 05, 2020 19:49:53.311 [0x7f5842ffd700] ERROR - XML: error :
Oct 05, 2020 19:49:53.311 [0x7f5842ffd700] ERROR - XML: xmlns:ms: ' urn:microsoft-com:wmc-1-0' is not a valid URI
Oct 05, 2020 19:49:53.311 [0x7f5842ffd700] ERROR - XML:   xmlns:ms=" urn:microsoft-com:wmc-1-0"
Oct 05, 2020 19:49:53.311 [0x7f5842ffd700] ERROR - XML:   
```
You might want to try https://support.plex.tv/articles/201100678-repair-a-corrupt-database/. 
Or kindly take it up with the Plex team 😉
