### ISSUE TITLE
Kodi traceback error on any playback - element indices must be integers

### ISSUE THREAD

**Issue by simonk83** [croneter/PlexKodiConnect#1640] opened 2021-09-26 11:42 UTC
This just started happening the other day, not sure if there was a recent update for something (I'm on an Nvidia Shield, Kodi 19.1 and PKC 3.5.0). Any time I play any video in Kodi now, this pops up.

Let me know what else you need or if you need me to test anything, no worries.

`2021-09-26 21:35:03.373 T:6758    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: element indices must be integers
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/kodimonitor.py", line 71, in onNotification
                                                       self._on_av_change(data)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/kodimonitor.py", line 400, in _on_av_change
                                                       item.on_kodi_audio_stream_change(kodi_audio_stream)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/playlist_func.py", line 321, in on_kodi_audio_stream_change
                                                       plex_stream_index = int(self.audio_streams[kodi_stream_index].get('id'))
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/playlist_func.py", line 207, in audio_streams
                                                       self._process_streams()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/playlist_func.py", line 242, in _process_streams
                                                       self.api.plex_media_streams())
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/plex_api/base.py", line 263, in plex_media_streams
                                                       return self.xml[self.mediastream][self.part]
                                                   TypeError: element indices must be integers
                                                   -->End of Python script error report<--`

**Comment by croneter** [comment] 2021-09-26 12:01
Please share your ENTIRE Debug log file, see https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by croneter** [comment] 2021-09-26 12:05
Guess you're using direct paths, not add-on paths, correct?

**Comment by simonk83** [comment] 2021-09-26 12:06
Yep correct, sorry about the log, I'm actually in bed now but I'll grab that for you first thing in the morning

**Comment by simonk83** [comment] 2021-09-26 12:09
Scratch that, the wonders of the kodi webserver :). Here you go
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/7231360/kodi.log)

**Comment by croneter** [comment] 2021-09-26 15:47
Thanks but I need the entire DEBUG log file, see link above

**Comment by simonk83** [comment] 2021-09-27 02:28
Oops again, here you 
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/7232936/kodi.log)
go

**Comment by croneter** [comment] 2021-09-27 05:43
Weird, I cannot reproduce your issue. What skin are you using? How do you start playback?

**Comment by simonk83** [comment] 2021-09-27 05:58
Hmm. I’m using Aeon Silva, and I tend to just use a widget to start playback (like an on deck widget). Weirdly though, I have another shield on another tv that’s basically a clone of the other, and that one doesn’t seem to be having this issue either. Is it worth doing a reset of PKC?

**Comment by croneter** [comment] 2021-09-27 11:18
Please don't do a reset just yet - I hope to be able to fix this issue. Otherwise I won't be able to test whether the bug has been successfully fixed 😉

**Comment by simonk83** [comment] 2021-09-27 11:38
Sure, no worries :)

**Comment by croneter** [comment] 2021-09-30 13:02
Should be fixed with PKC beta version 3.5.1

**Comment by simonk83** [comment] 2021-09-30 23:30
Oh nice work, thanks. Is it worth me trying to install the beta just to test this, or should I just wait for the proper release so that it auto updates and I don't have to mess with beta repo's etc

**Comment by simonk83** [comment] 2021-10-01 10:49
Ah, sometimes when a file is played right to the end, it pops up a new exception (<class 'UnboundLocalError'>). I'll grab logs but it might need to be tomorrow

**Comment by croneter** [comment] 2021-10-01 11:26
New GitHub issue please, not here in this one  😉

**Closed** 2021-10-17 13:31 UTC
Labels: Kodi 19 Matrix
