### ISSUE TITLE
Use transcode API to get cover art - Plex Cloud fix

### ISSUE THREAD

**Issue by MarhyCZ** [croneter/PlexKodiConnect#314] opened 2017-07-01 09:14 UTC
Hi, 
There is already a thread about Plex Cloud Missing artwork, but nobody replied there, so I thought it would be good to create another thread so someone notices. 

In PKC thread on Plex forums (http://forums.plex.tv/discussion/256438/plexkodiconnect-is-unable-to-download-artwork-from-plexcloud#latest)  Plex Employee came up with probably a working solution!

MovieFan.Plex:
"I've informed the devs. Due to the way Plex Cloud works, that API doesn't quite work properly. With all the other things going on for Plex Cloud, fixing that API is a bit low on the priority list. Alternatively and the proper way to request artwork is to invoke the transcode API. If you set the size high enough, it won't bother converting the image and you will get the full size image, so you basically get the same result.

https://*.sjc.plex.services/photo/:/transcode?width=4000&height=4000&minSize=1&upscale=0&url=/library/metadata/6/thumb/1495650195?X-Plex-Token=xxx&X-Plex-Token=xxx

Will get you the same as if you used

https://*.sjc.plex.services/library/metadata/6/thumb/1495650195?X-Plex-Token=xxx

Assuming the image is smaller than 4,000 x 4,000, which for Plex Cloud, they will be."

Would it be possible to implement this?

**Comment by croneter** [comment] 2017-07-01 10:10
Duplicate of https://github.com/croneter/PlexKodiConnect/issues/189 - closing

**Closed by croneter** 2017-07-01 10:10 UTC
