### ISSUE TITLE
Locally Stored Movie Trailers Not Playing

### ISSUE THREAD

**Issue by leejk421** [croneter/PlexKodiConnect#515] opened 2018-07-26 00:01 UTC
Previously logged this under a different name, but since it was closed I opened a new one. In KODI if I navigate to the movie info screen and select the option in the skin to play a movie trailer, KODI just says buffering... please wait. It'll do that forever unless I hit the escape key a few times to make it stop, or sometimes KODI will crash. This worked fine before the last major PKC update. I do not have the option in PKC turned on to play Plex Pass trailers. I'm trying to play locally stored trailers. This should be easy to replicate:

1. If you do not have movie trailer files, either download one or just make a copy of another video file.
2. Name the files like this: movie title (year).bluray-trailer.mpg
3. Place the trailer in the same folder as the movie and let PMS scrape it.
4. Optionally play the trailer thru Plex Web to verify PMS sees it.
5. Now startup KODI and go to the movie you added the trailer to.
6. Press the i key to open the movie info screen.
7. I'm using AEON MQ7 skin, but I think most skins show a trailer play option on this screen.
8. No playback

Attached is my debug log.
[kodi.zip](https://github.com/croneter/PlexKodiConnect/files/2229934/kodi.zip)

**Comment by croneter** [comment] 2018-07-26 06:50
Which issue was that? Please link to it here

**Comment by leejk421** [comment] 2018-07-27 01:14
Sure. 
https://github.com/croneter/PlexKodiConnect/issues/492

**Comment by leejk421** [comment] 2018-07-28 04:20
Can I please get an explanation for closing this, since it is not resolved?

**Comment by croneter** [comment] 2018-07-28 07:54
Because I fixed the one crash I saw in the logs and could reproduce

**Comment by croneter** [comment] 2018-07-28 09:18
Could you please share another debug log file?

**Comment by leejk421** [comment] 2018-07-29 16:19
Sure thing 👍 

So you were able to reproduce the playback of trailers problem?

[kodi.zip](https://github.com/croneter/PlexKodiConnect/files/2238954/kodi.zip)

**Comment by croneter** [comment] 2018-07-30 10:19
Thanks for the log! Something went wrong with the repo for the latest beta versoin 2.2.17. Should be fixed now. Please make sure you got the latest PKC beta version 2.2.17 and try again. If this bug is NOT fixed, please reopen or comment - I'm being optimistic here 😉

**Comment by leejk421** [comment] 2018-08-01 03:34
Hi. Well, problem is sort of fixed. Now it at least does not just sit there. When I play a trailer from the movie info screen now, it prompts me to pick a video quality resolution for the trailer. Going by how it used to work, it shouldn’t do this. Since I have Plex trailers disabled, it should play the locally stored trailer without any prompt. If I pick a video quality it will start playing, but it is streaming it from the internet. So not sure where it got the internet trailers from. How do you want to proceed?

**Comment by leejk421** [comment] 2018-08-10 18:13
Hi, so I tested it today, and progress :)

There are a couple of issues still tho, as it still does not work seamlessly as it did prior to 2.1. Do you want me to open a separate issue or continue on this one?

**Comment by leejk421** [comment] 2018-08-10 23:40
Sorry. Using the default Estuary skin, when I click the trailer button on the movie info screen, a list of trailers pops up. If I’m using my normal skin, Aeon MQ 7, a blank screen pops up, and I have to press backspace for the trailer list to show. That’s minor, but now when using the CinemaVision add-on, when it tries to play a local trailer it’ll pop up the trailer list. That’s very undesirable when trying to emulate a theater experience.

In the pre 2.1 version of PKC if memory serves me right, I don’t think it ever showed the trailer list, but rather always played the locally stored trailer without prompting. I think this is the behavior needed for the CinemaVision addon to work correctly too. Since I have the Plex trailers option turned off in PKC settings, PKC should probably not list any PMS scraped trailers and just play the local trailer directly if it exists. Does that sound right?

**Comment by croneter** [comment] 2018-08-11 07:29
PKC always played the very first trailer and never checked whether it was local or not. This is your use case, others might have different use cases.
Does the blank screen also pop up in other skins or just Aeon?

**Comment by croneter** [comment] 2018-08-11 07:31
Do you know of the Plex context menu you can use? It will show an extras menu, which in turn shows you ALL the Plex extras

**Comment by leejk421** [comment] 2018-08-14 00:59
Hi, the blank screen, or nothing at all does happen with other skins. I tested on Titan and no screen pops up when you click the trailer button. Afterwards the trailer button disappeared, so not sure what’s going on there. An “out of the box” installed Aeon Nox Silvo seemed to work ok tho.

That new change may do the trick. In my case, if KODI will just play the local trailer instead of showing a list it may also fix the CinemaVision problem. The only scenario I can think of that might be an issue for CinemaVision is if the user doesn’t have a local trailer. In that case a scraped one would need to be played.

Yes, I know of the Plex extras menu. In fact I think that is the appropriate place to list all the available trailers. I think the default behavior of the trailer button in a skin was to play a trailer directly, either local or internet, whichever one KODI scraped first.

**Comment by leejk421** [comment] 2018-08-25 04:08
Hi,

Tried latest beta, still same problems. When clicking on trailers tab in move information it still doesn’t show anything until back button is pressed. That is minor still, but the main problem is that when using the CinemaVision addon, it still prompts user to select which trailer to play. I’m going to revert back to default KODI db behavior I think in leu of PKC. Again prior to your rewrite it worked perfectly so not sure what the culprit is.

**Comment by croneter** [comment] 2018-08-25 06:18
Make sure that "List Plex extras instead of playing trailer" is DEACTIVATED in the PKC settings under Sync

Then Reset the Kodi database, it should all work fine now.

**Comment by croneter** [comment] 2018-08-25 10:08
Does it work?

**Comment by leejk421** [comment] 2018-08-26 02:14
I reset the database. But when using the CinemaVision addon it prompts to select which trailer to play still. On the movie info screen tho it plays the local trailer directly with no prompt. That’s good. But when using the CinemaVision addon, when it gets to the trailer segment it prompts for a selection. So maybe still a part missed? Something is still preventing default KODI behavior. It’s worth noting that when the prompt window opens, it does not show the local trailer in the list.

**Comment by croneter** [comment] 2018-08-26 05:47
I can't use cinema vision, unfortunately. Could you please share another debug log file of this prompt appearing when it should not?

**Comment by croneter** [comment] 2018-08-26 06:02
Ah, before you do that - did you also reset the Cinema Vision add-on? It needs to rescan the Kodi library and the stored trailers, of course

**Comment by leejk421** [comment] 2018-08-26 17:53
Hello, I did forget to reset the CV addon db, so I did that and reset PKC again too. That cleared everything out, but now the CinemaVision addon isn't seeing any of the KODI db trailers. I have attached a debug log; not sure if there is anything useful in it. The trailers were supposed to play right before the audio bumper. I don't see any errors, so it's as if they don't exist. Is PKC storing the trailers in the KODI db, just as KODI normally would when it scrapes the movies?

[kodi.zip](https://github.com/croneter/PlexKodiConnect/files/2321747/kodi.zip)

**Comment by croneter** [comment] 2018-08-26 19:58
Playing trailers "normally" via the Kodi movie information screen works fine? Then CV is the issue, probably. Trailers are stored in the Kodi database. CV scans that DB.

Will have a look at the log file soon. I'd try to only reset CV again (PKC should be reset first as CV builds on PKC Infos)

**Comment by leejk421** [comment] 2018-08-28 03:42
It is working! Evidently I had some trash laying around in the db that only some manual file deletions would take care of. Thank you for your persistence!

**Comment by croneter** [comment] 2018-08-28 08:09
Very cool, glad it's working now :-)

**Closed by croneter** 2018-08-28 08:09 UTC
