### ISSUE TITLE
Instantaneous background sync broken in Kodi Matrix

### ISSUE THREAD

**Issue by MrRobot12** [croneter/PlexKodiConnect#1392] opened 2021-03-09 20:30 UTC
Kodi device: Chromecast with Google TV on Kodi 19 

PLEX server: Windows 10 pc on same home network. 

Issue: Enable constant background sync is enabled but when a new file is added or an old file deleted Kodi does not update the UI. Checked PLEX client and the new changes are immediately shown but Kodi doesn’t update anything until the program is closed and reopened or the update interval is changed from 60 minutes to something shorter like 1. 

I used a log viewer but being Android TV there isn’t an easy way to copy the whole thing. I went through the log and the only error message I could find was this...

ERROR <general>:PLEX.plexgdm:Unable to send client update message 

However, there is nothing on the log that shows after PLEX server updates with the new files, so it appears that rather than failing to sync Kodi is not trying to sync at all even though the option to do so is checked on in the settings.

**Comment by croneter** [comment] 2021-03-10 05:45
Entire debug log?!? https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by croneter** [comment] 2021-03-10 05:46
No log no help possible. You can simply drop the file here when replying

**Comment by maaaatteo** [comment] 2021-03-13 19:58
i have the same issue, check attached log. 

note that somewhere at 20:47 i added a file in the movie folder, it was immediately updated in plex but not in kodi.

it has been updated in kodi after couple of minutes since i set the full sync every 3min inestead of default 60min.
but backgrouynd sync is not working anymore, as the op noticed .

plex server is installed on synology nas and updated to last version.
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/6135448/kodi.log)

**Comment by croneter** [comment] 2021-03-14 11:46
@maaaatteo 
Unfortunately, you did not follow https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug . You're Plex token has thus been leaked. Please **immediately** follow https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug#i-published-my-plex-token-to-some-forum-or-github-anyone-can-now-access-my-plex-server 
Sorry for the hassle, I'd love to "fix" this but unfortunately it's impossible on the Kodi side 😢 . I did remove the link (and link only, the log is still there!) in your post. 

PlexKodiConnect simply cannot contact your PMS for background sync:
```
DEBUG <general>: PLEX.websocket_client: PMS_Websocket: Uri: wss://<PMS ID>.plex.direct:32400/:/websockets/notifications?X-Plex-Token=<TOKEN>, sslopt: {}
DEBUG <general>: PLEX.websocket_client: PMS_Websocket: WebSocketTimeoutException
```
You probably have a firewall or something else blocking this connection (secure websocket connection) on port 32400 from outside your LAN. There's **nothing** PKC can do.

**Comment by croneter** [comment] 2021-03-14 11:47
Closing this issue as @MrRobot12 has not yet provided any log

**Comment by maaaatteo** [comment] 2021-03-14 12:13
> @maaaatteo
> Unfortunately, you did not follow https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug . You're Plex token has thus been leaked. Please **immediately** follow the instructions here: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug#i-published-my-plex-token-to-some-forum-or-github-anyone-can-now-access-my-plex-server
> Sorry for the hassle, I'd love to "fix" this but unfortunately it's impossible on the Kodi side 😢 . I did remove the link (and link only, the log is still there!) in your post.

thanks, what a mistake! :( i revoked all tokens just to be sure

> 
> PlexKodiConnect simply cannot contact your PMS for background sync:
> 
> ```
> DEBUG <general>: PLEX.websocket_client: PMS_Websocket: Uri: wss://<PMS ID>.plex.direct:32400/:/websockets/notifications?X-Plex-Token=<TOKEN>, sslopt: {}
> DEBUG <general>: PLEX.websocket_client: PMS_Websocket: WebSocketTimeoutException
> ```
> 
> You probably have a firewall or something else blocking this connection (secure websocket connection) on port 32400 from outside your LAN. There's **nothing** PKC can do.

that's very strange since nothing changed on my lan, also i can access my plex server through port 32400 from outside (it's the standard port for remote access page and it works)

thanks anyway!

**Comment by croneter** [comment] 2021-03-14 12:56
@maaaatteo Was it working fine on Kodi 18 and you upgraded to 19? Nothing else changed?

**Comment by maaaatteo** [comment] 2021-03-14 15:28
> @maaaatteo Was it working fine on Kodi 18 and you upgraded to 19? Nothing else changed?

yep exactly. and this happened on all 3 nvidia shield i have on my lan (plex server is always the same)

by the way, i just tried to setup a fresh installation of kodi leia in windows, install correct addon from correct repo, and background sync was working.

after that, i made the same with matrix version (of both kodi and addon): background sync is not working :(

**Comment by croneter** [comment] 2021-03-14 16:44
Agreed. Kodi 19 Matrix completely broke the PlexKodiConnect background sync 😢. I'm on it!

**Comment by maaaatteo** [comment] 2021-03-15 11:36
> I'm on it! 

👍

**Comment by croneter** [comment] 2021-03-17 21:06
Try the new pkc beta version 3.0.17

**Comment by maaaatteo** [comment] 2021-03-17 21:23
> Try the new pkc beta version 3.0.17

it's claiming a missing dependancy from plugin.video.plexkodiconnect.movies 3.0.0

**Comment by croneter** [comment] 2021-03-17 22:07
@maaaatteo Install again from the PKC beta repo

**Comment by maaaatteo** [comment] 2021-03-17 22:13
> @maaaatteo Install again from Zip file from the PKC beta repo

same result (yes first i disinstalled all pkc-related stuff, including repo, and started from scratch)

**Comment by croneter** [comment] 2021-03-17 22:22
@maaaatteo
Follow my last comment here: https://github.com/croneter/PlexKodiConnect/issues/1359

Start from scratch for real...

**Comment by croneter** [comment] 2021-03-17 22:41
@maaaatteo just tested the update on my Android and it worked just fine

**Comment by maaaatteo** [comment] 2021-03-17 22:50
> @maaaatteo just tested the update on my Android and it worked just fine

confirmed!! background sync is back! you're the man :D

**Closed** 2021-03-19 17:56 UTC
Labels: Kodi 19 Matrix
