### ISSUE TITLE
Latest omega alpha build revved the db version so it is no longer supported by the addon

### ISSUE THREAD

**Issue by xconverge** [croneter/PlexKodiConnect#1988] opened 2023-09-11 00:33 UTC
https://kodi.tv/article/kodi-omega-alpha-3/

Pretty sure this isnt working right/supported correctly. It also doesn't handle the rev nicely because the old db was still there. When I manually cleared them I got the "this addon doesnt support this db" error which was nice

```
mdarcy:/sdcard/Android/data/org.xbmc.kodi/files/.kodi/userdata/Database $ ls -la
total 5084
drwxrwx--x  3 u0_a97 sdcard_rw    4096 2023-09-10 17:28 .
drwxrwx--x 10 u0_a97 sdcard_rw    4096 2023-09-10 17:25 ..
-rw-rw----  1 u0_a97 sdcard_rw    6148 2023-05-31 21:24 .DS_Store
-rw-rw----  1 u0_a97 sdcard_rw    4096 2023-05-31 21:24 ._.DS_Store
-rw-rw----  1 u0_a97 sdcard_rw 2048000 2023-09-10 17:00 Addons33.db
drwxrwx--x  2 u0_a97 sdcard_rw    4096 2023-05-31 21:24 CDDB
-rw-rw----  1 u0_a97 sdcard_rw   32768 2023-01-16 13:19 Epg16.db
-rw-rw----  1 u0_a97 sdcard_rw  225280 2023-05-31 21:24 MyMusic82.db
-rw-rw----  1 u0_a97 sdcard_rw  376832 2023-09-10 17:28 MyVideos122.db
-rw-rw----  1 u0_a97 sdcard_rw   53248 2023-09-10 17:28 TV43.db
-rw-rw----  1 u0_a97 sdcard_rw 1523712 2023-09-10 17:26 Textures13.db
-rw-rw----  1 u0_a97 sdcard_rw   20480 2022-11-24 12:40 ViewModes6.db
-rw-rw----  1 u0_a97 sdcard_rw  442368 2023-09-10 17:23 plex-copy.db
-rw-rw----  1 u0_a97 sdcard_rw  442368 2023-09-10 17:25 plex.db
```

https://github.com/xbmc/xbmc/pull/23346

**Comment by booleangit** [comment] 2023-09-11 12:17
Thanks! It would be really nice if this could be merged. 👍

**Comment by KyleSanderson** [comment] 2023-09-20 02:42
Ah jeez - was wondering why this completely broken. Thank you for the PR.

**Comment by xconverge** [comment] 2023-09-20 02:49
21 a3 also drove me crazy due to https://github.com/xbmc/xbmc/issues/23765, so much so I went back to 20. So I would advise anyone who wants to apply/use this patch to use a nightly after 9/19 (tonight at the time of this posting) either way.

**Comment by GG-76** [comment] 2023-09-21 21:28
Is there any way to run the PlexKodiConnect on Kodi Omega at the moment? Editing variables.py doesn't work for me :(

**Comment by KyleSanderson** [comment] 2023-09-22 00:02
> Is there any way to run the PlexKodiConnect on Kodi Omega at the moment? Editing variables.py doesn't work for me :(

You need to delete the old database manually. The script is bugged and looks for the old one first.

**Comment by GG-76** [comment] 2023-09-22 08:41
@KyleSanderson please what is the file? thank you.

**Comment by BaukeZwart** [comment] 2023-09-22 09:01
@GG-76 what isn't working, installing PKC or getting the db loaded?
Installing the modified PKC and doing a db reset from the PKC config menu fixed it for me.

**Comment by GG-76** [comment] 2023-09-22 09:54
@BaukeZwart I guess I don't understand. What is modifed PKC and where can I find it? i installed the latest version of kodi omega and PKC 3.8.1 from the library and it still says unsupported version. I didn't see anywhere that there was a modified version available for download.

**Comment by BaukeZwart** [comment] 2023-09-22 10:31
You can't find it, you need to make the change yourself.

**Comment by GG-76** [comment] 2023-09-22 10:38
@BaukeZwart  and how? i try edit variables.py but its not working :/

**Comment by BaukeZwart** [comment] 2023-09-22 10:41
That worked for me.

**Comment by GG-76** [comment] 2023-09-22 11:24
@BaukeZwart I don't know what the correct procedure is, but I have a clean install of kodi, then PKC, then edited the file, run kodi, error message, reset DB, run kodi again, but still the same error message :/

**Comment by BaukeZwart** [comment] 2023-09-22 13:11
Downloaded and unpacked PKC, edit and zip again.

Downloaded and install the following Plugins:

https://github.com/croneter/plugin.video.plexkodiconnect.movies/tree/python3

https://github.com/croneter/plugin.video.plexkodiconnect.tvshows/tree/python3

Install the modified PKC.zip 

If all that goes without errors you should be good to go.

**Comment by GG-76** [comment] 2023-09-22 13:32
@BaukeZwart  i see, ok thanks

edit: I followed the exact procedure and still the same result... Now I don't understand what the problem is...

**Comment by GG-76** [comment] 2023-09-28 07:56
@croneter Hi, when will the working version work with Kodi Omega be released please? thank you.

**Comment by TheRealBix** [comment] 2023-09-30 20:25
For god sake thanks for the fix, I almost lost my sanity between the investigation and pkc installation...

**Comment by GG-76** [comment] 2023-10-01 19:33
> For god sake thanks for the fix, I almost lost my sanity between the investigation and pkc installation...

Does the manual fix work for you too? I'm probably the only one who doesn't :/ I'm already pissed off. 

Can someone please share with me the already modified PKC zip, because I'm probably stupid if I can't modify it so that it works...

**Comment by xconverge** [comment] 2023-10-01 19:43
> > For god sake thanks for the fix, I almost lost my sanity between the investigation and pkc installation...
> 
> Does the manual fix work for you too? I'm probably the only one who doesn't :/ I'm already pissed off.
> 
> Can someone please share with me the already modified PKC zip, because I'm probably stupid if I can't modify it so that it works...

1. edit `/addons/plugin.video.plexkodiconnect/resources/lib/variables.py` to add 122 for kodi 21 like this 
```
  SUPPORTED_VIDEO_DB = {
      19: (119, ),
      20: (119, 120, 121),
      21: (121, 122, ),
  }
```
2. Delete `/userdata/Database/MyVideos121.db` if it exists (I just did rm -rf MyVideos*.db)
3. Restart kodi
4. Wait for plexkodiconenct to sync the new database

I have been running like this with no issues since alpha3 came out, but I suggest using a nightly instead of alpha 3

**Comment by TheRealBix** [comment] 2023-10-01 20:12
I did reset the database through pkc (last red setting if I remember)
I imagine it starts by deleting the 121.db first ? Anyway it's working for me yep. Just don't mess up with the edit, that's all.

A bit out of subject but why do you suggest the nightly over alpha3 ?

**Comment by xconverge** [comment] 2023-10-01 20:35
> I did reset the database through pkc (last red setting if I remember) I imagine it starts by deleting the 121.db first ? Anyway it's working for me yep. Just don't mess up with the edit, that's all.
> 
> A bit out of subject but why do you suggest the nightly over alpha3 ?

see my message above https://github.com/croneter/PlexKodiConnect/issues/1988#issuecomment-1726801106

**Comment by GG-76** [comment] 2023-10-01 20:44
I have a different situation. I have a clean install of Kodi alpha 3, a clean install of PKC and it creates /userdata/Database/MyVideos122.db and I do anything with it, it always says unsupported version...

**Comment by xconverge** [comment] 2023-10-01 21:19
> I have a different situation. I have a clean install of Kodi alpha 3, a clean install of PKC and it creates /userdata/Database/MyVideos122.db and I do anything with it, it always says unsupported version...

Then you probably did not do step 1 correctly of editing variables.py

Sorry, I would just stay on alpha 2 (or just 20.2...) until this gets merged if you continue to have problems.

**Comment by GG-76** [comment] 2023-10-01 21:56
I guess I don't understand how I didn't edit variable.py correctly. it probably doesn't even work :D I copied exactly this code and rewrote it in the original... I've done it 20 times already, so what can I do wrong???? I think the problem must be somewhere else, when the db is already 122 after the first installation, even before the modification...

**Comment by TheRealBix** [comment] 2023-10-02 18:54
Where are Kodi nighties btw ? All omega folders seems empty either for Android or windows

edit : nvm they are under "master" folder which is used for current developed branch

**Comment by GG-76** [comment] 2023-10-04 19:11
I am forced to go back to Nexus because Omega Alpha 3 causes a lot more errors compared to previous versions and a lot of things that used to work for me stopped working, it is no longer usable for me... It not unfortunately only about PKC,,,

**Comment by geropan** [comment] 2023-10-24 21:28
> > > For god sake thanks for the fix, I almost lost my sanity between the investigation and pkc installation...
> > 
> > 
> > Does the manual fix work for you too? I'm probably the only one who doesn't :/ I'm already pissed off.
> > Can someone please share with me the already modified PKC zip, because I'm probably stupid if I can't modify it so that it works...
> 
> 1. edit `/addons/plugin.video.plexkodiconnect/resources/lib/variables.py` to add 122 for kodi 21 like this
> 
> ```
>   SUPPORTED_VIDEO_DB = {
>       19: (119, ),
>       20: (119, 120, 121),
>       21: (121, 122, ),
>   }
> ```
> 
> 2. Delete `/userdata/Database/MyVideos121.db` if it exists (I just did rm -rf MyVideos*.db)
> 3. Restart kodi
> 4. Wait for plexkodiconenct to sync the new database
> 
> I have been running like this with no issues since alpha3 came out, but I suggest using a nightly instead of alpha 3

Just to add to this, on beta 1 the music database has also changed, so there is a further modification needed to the variables.py file:

```
SUPPORTED_MUSIC_DB = {
    19: (82, ),
    20: (82, ),
    21: (83, ),
}
```

**Comment by xconverge** [comment] 2023-10-25 00:53
> > > > For god sake thanks for the fix, I almost lost my sanity between the investigation and pkc installation...
> > > 
> > > 
> > > Does the manual fix work for you too? I'm probably the only one who doesn't :/ I'm already pissed off.
> > > Can someone please share with me the already modified PKC zip, because I'm probably stupid if I can't modify it so that it works...
> > 
> > 
> > 
> > 1. edit `/addons/plugin.video.plexkodiconnect/resources/lib/variables.py` to add 122 for kodi 21 like this
> > 
> > ```
> >   SUPPORTED_VIDEO_DB = {
> >       19: (119, ),
> >       20: (119, 120, 121),
> >       21: (121, 122, ),
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 2. Delete `/userdata/Database/MyVideos121.db` if it exists (I just did rm -rf MyVideos*.db)
> > 3. Restart kodi
> > 4. Wait for plexkodiconenct to sync the new database
> > 
> > I have been running like this with no issues since alpha3 came out, but I suggest using a nightly instead of alpha 3
> 
> Just to add to this, on beta 1 the music database has also changed, so there is a further modification needed to the variables.py file:
> 
> ```
> SUPPORTED_MUSIC_DB = {
>     19: (82, ),
>     20: (82, ),
>     21: (83, ),
> }
> ```

Ok I will make the change in my MR just in case @croneter pops up

**Comment by meinname** [comment] 2023-12-07 19:59
FYI: Kodi Omega is now at Version 123 for Video DB (idk where it is for music, as i only use it for movies)

**Comment by xconverge** [comment] 2023-12-10 23:40
> FYI: Kodi Omega is now at Version 123 for Video DB (idk where it is for music, as i only use it for movies)

Updated my MR, it was at 124 as of today 💀

**Comment by doomwithdon** [comment] 2024-01-02 16:39
> > FYI: Kodi Omega is now at Version 123 for Video DB (idk where it is for music, as i only use it for movies)
> 
> Updated my MR, it was at 124 as of today 💀

It's now revved to 127 last i checked on December 30th, 2023

**Comment by xconverge** [comment] 2024-01-03 01:45
Yea...FWIW you can find it here, and git blaming it gives you context on what changed along with the number change:

https://github.com/xbmc/xbmc/blob/master/xbmc/video/VideoDatabase.cpp#L6256

in a function called `int CVideoDatabase::GetSchemaVersion() const`

I will just update as I need to personally (probably sticking to betas and release candidates now, no more nightlies for me). There is also always the chance a DB change has breaking changes for plexkodiconnect that is more than a number change

I also am not infinitely far away from just using the plex frontend...

**Comment by doomwithdon** [comment] 2024-01-15 03:17
I have tried updating the variables.py and deleting the db file but i keep getting the error. Anyways I am assuming once the final version is released, PKC will get updated with a compatible release version.

**Comment by croneter** [comment] 2024-01-20 17:02
Fixed in PKC version 3.8.3 for Kodi Omega BETA. I do NOT support nightly versions - too much stuff breaks with these

**Closed as completed by croneter** 2024-01-20 17:02 UTC

**Comment by bokkoman** [comment] 2024-02-16 21:22
It seems the database is revved up to another version.
Suddenly my movies aren't visible anymore, but TV still is.
I don't know how to fix this.
The movies database name now is Movies131.db.

**Comment by xconverge** [comment] 2024-02-16 21:27
> It seems the database is revved up to another version. Suddenly my movies aren't visible anymore, but TV still is. I don't know how to fix this. The movies database name now is Movies131.db.

you can try the beta of plexkodiconnect https://github.com/croneter/PlexKodiConnect/releases/tag/3.8.4

**Comment by bokkoman** [comment] 2024-02-16 21:30
> > It seems the database is revved up to another version. Suddenly my movies aren't visible anymore, but TV still is. I don't know how to fix this. The movies database name now is Movies131.db.
> 
> you can try the beta of plexkodiconnect https://github.com/croneter/PlexKodiConnect/releases/tag/3.8.4

I have this version.
Im reinstalling it as we speak.

**Comment by bokkoman** [comment] 2024-02-16 21:42
> > It seems the database is revved up to another version. Suddenly my movies aren't visible anymore, but TV still is. I don't know how to fix this. The movies database name now is Movies131.db.
> 
> you can try the beta of plexkodiconnect https://github.com/croneter/PlexKodiConnect/releases/tag/3.8.4

Nah, it doesn't work anymore.
I'm on 21.0 beta 3 since yesterday. 
MyVideos131.db is the new filename. 

Editing variables.py doesn't work either.

**Comment by croneter** [comment] 2024-02-17 08:20
@bokkoman try resetting the PKC database. In the PKC settings go to Advanced, then hit "Reset the Kodi database" (in red). Reset the database only, do not reset the PKC add-on itself

**Comment by bokkoman** [comment] 2024-02-17 08:24
> @bokkoman try resetting the PKC database. In the PKC settings go to Advanced, then hit "Reset the Kodi database" (in red). Reset the database only, do not reset the PKC add-on itself

I tried.
I also deleted all the databases.
Tried editing the variables.py.
Tried reinstalling. 
Nothing worked. It's only the movies though, cause TV shows work fine. 
I think it's the new beta that does something differently.

**Comment by croneter** [comment] 2024-02-17 13:02
@bokkoman try re-installing Kodi completely from scratch

**Comment by bokkoman** [comment] 2024-02-17 13:03
> @bokkoman try re-installing Kodi completely from scratch

I'll do this.
But if that doesn't work, is there anything I can provide to fix it?

**Comment by bokkoman** [comment] 2024-02-17 13:31
Just a heads up, the jellyfin plugin is broken as well because of beta 3.

**Comment by bokkoman** [comment] 2024-02-17 14:21
Ok, this is confirmed broken.
Another issue thread.

https://github.com/jellyfin/jellyfin-kodi/issues/808
