### ISSUE TITLE
New Movie Sets are not replicating to Kod

### ISSUE THREAD

**Issue by NoOneReally2021** [croneter/PlexKodiConnect#1570] opened 2021-07-29 08:23 UTC
Hi

i have a problem with Movie Sets in Kodi.
When a new movie collection is created in plex it does not replicate to Kodi unless i delete the database in Kodi and let it resync with Plex

You can easily replicate this issue by creating a collection in Plex

**Comment by croneter** [comment] 2021-07-30 18:49
Duplicate of #689, please see there

**Closed by croneter** 2021-07-30 18:49 UTC
